/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  EnterpriseStressRead,
  EnterpriseStressRunCreate,
  EnterpriseStressRunSummary,
  ErrorResponse,
} from "../models/index";
import {
  EnterpriseStressReadFromJSON,
  EnterpriseStressReadToJSON,
  EnterpriseStressRunCreateFromJSON,
  EnterpriseStressRunCreateToJSON,
  EnterpriseStressRunSummaryFromJSON,
  EnterpriseStressRunSummaryToJSON,
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
} from "../models/index";

export interface GetEnterpriseStressRunRequest {
  bankId: string;
  runId: string;
}

export interface GetLatestEnterpriseStressRequest {
  bankId: string;
  reportingPeriodId: string;
  scenarioId: string;
}

export interface ListEnterpriseStressRunsRequest {
  bankId: string;
  reportingPeriodId?: string | null;
}

export interface RunEnterpriseStressRequest {
  bankId: string;
  enterpriseStressRunCreate: EnterpriseStressRunCreate;
}

/**
 *
 */
export class EnterpriseStressApi extends runtime.BaseAPI {
  /**
   * Re-open one immutable enterprise-stress run by id (docs/stress.md §4.5).
   * Get Enterprise Stress Run
   */
  async getEnterpriseStressRunRaw(
    requestParameters: GetEnterpriseStressRunRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EnterpriseStressRead>> {
    if (requestParameters["bankId"] == null) {
      throw new runtime.RequiredError(
        "bankId",
        'Required parameter "bankId" was null or undefined when calling getEnterpriseStressRun().',
      );
    }

    if (requestParameters["runId"] == null) {
      throw new runtime.RequiredError(
        "runId",
        'Required parameter "runId" was null or undefined when calling getEnterpriseStressRun().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v1/banks/{bank_id}/enterprise-stress/runs/{run_id}`
          .replace(
            `{${"bank_id"}}`,
            encodeURIComponent(String(requestParameters["bankId"])),
          )
          .replace(
            `{${"run_id"}}`,
            encodeURIComponent(String(requestParameters["runId"])),
          ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EnterpriseStressReadFromJSON(jsonValue),
    );
  }

  /**
   * Re-open one immutable enterprise-stress run by id (docs/stress.md §4.5).
   * Get Enterprise Stress Run
   */
  async getEnterpriseStressRun(
    requestParameters: GetEnterpriseStressRunRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EnterpriseStressRead> {
    const response = await this.getEnterpriseStressRunRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Latest Enterprise Stress
   */
  async getLatestEnterpriseStressRaw(
    requestParameters: GetLatestEnterpriseStressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EnterpriseStressRead>> {
    if (requestParameters["bankId"] == null) {
      throw new runtime.RequiredError(
        "bankId",
        'Required parameter "bankId" was null or undefined when calling getLatestEnterpriseStress().',
      );
    }

    if (requestParameters["reportingPeriodId"] == null) {
      throw new runtime.RequiredError(
        "reportingPeriodId",
        'Required parameter "reportingPeriodId" was null or undefined when calling getLatestEnterpriseStress().',
      );
    }

    if (requestParameters["scenarioId"] == null) {
      throw new runtime.RequiredError(
        "scenarioId",
        'Required parameter "scenarioId" was null or undefined when calling getLatestEnterpriseStress().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["reportingPeriodId"] != null) {
      queryParameters["reporting_period_id"] =
        requestParameters["reportingPeriodId"];
    }

    if (requestParameters["scenarioId"] != null) {
      queryParameters["scenario_id"] = requestParameters["scenarioId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v1/banks/{bank_id}/enterprise-stress/latest`.replace(
          `{${"bank_id"}}`,
          encodeURIComponent(String(requestParameters["bankId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EnterpriseStressReadFromJSON(jsonValue),
    );
  }

  /**
   * Get Latest Enterprise Stress
   */
  async getLatestEnterpriseStress(
    requestParameters: GetLatestEnterpriseStressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EnterpriseStressRead> {
    const response = await this.getLatestEnterpriseStressRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * The run registry: full enterprise-stress run history (docs/stress.md §4.5).
   * List Enterprise Stress Runs
   */
  async listEnterpriseStressRunsRaw(
    requestParameters: ListEnterpriseStressRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<EnterpriseStressRunSummary>>> {
    if (requestParameters["bankId"] == null) {
      throw new runtime.RequiredError(
        "bankId",
        'Required parameter "bankId" was null or undefined when calling listEnterpriseStressRuns().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["reportingPeriodId"] != null) {
      queryParameters["reporting_period_id"] =
        requestParameters["reportingPeriodId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v1/banks/{bank_id}/enterprise-stress/runs`.replace(
          `{${"bank_id"}}`,
          encodeURIComponent(String(requestParameters["bankId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(EnterpriseStressRunSummaryFromJSON),
    );
  }

  /**
   * The run registry: full enterprise-stress run history (docs/stress.md §4.5).
   * List Enterprise Stress Runs
   */
  async listEnterpriseStressRuns(
    requestParameters: ListEnterpriseStressRunsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<EnterpriseStressRunSummary>> {
    const response = await this.listEnterpriseStressRunsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Run Enterprise Stress
   */
  async runEnterpriseStressRaw(
    requestParameters: RunEnterpriseStressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EnterpriseStressRead>> {
    if (requestParameters["bankId"] == null) {
      throw new runtime.RequiredError(
        "bankId",
        'Required parameter "bankId" was null or undefined when calling runEnterpriseStress().',
      );
    }

    if (requestParameters["enterpriseStressRunCreate"] == null) {
      throw new runtime.RequiredError(
        "enterpriseStressRunCreate",
        'Required parameter "enterpriseStressRunCreate" was null or undefined when calling runEnterpriseStress().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v1/banks/{bank_id}/enterprise-stress/runs`.replace(
          `{${"bank_id"}}`,
          encodeURIComponent(String(requestParameters["bankId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: EnterpriseStressRunCreateToJSON(
          requestParameters["enterpriseStressRunCreate"],
        ),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      EnterpriseStressReadFromJSON(jsonValue),
    );
  }

  /**
   * Run Enterprise Stress
   */
  async runEnterpriseStress(
    requestParameters: RunEnterpriseStressRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EnterpriseStressRead> {
    const response = await this.runEnterpriseStressRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
