/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ErrorResponse,
  EvidenceRead,
  FindingCreate,
  FindingRead,
  FindingUpdate,
} from "../models/index";
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  EvidenceReadFromJSON,
  EvidenceReadToJSON,
  FindingCreateFromJSON,
  FindingCreateToJSON,
  FindingReadFromJSON,
  FindingReadToJSON,
  FindingUpdateFromJSON,
  FindingUpdateToJSON,
} from "../models/index";

export interface CreateCaseFindingRequest {
  caseId: string;
  xOrgId: string;
  findingCreate: FindingCreate;
  xUserId?: string | null;
}

export interface GetFindingRequest {
  findingId: string;
  xOrgId: string;
  xUserId?: string | null;
}

export interface GetFindingEvidenceRequest {
  findingId: string;
  xOrgId: string;
  xUserId?: string | null;
}

export interface ListAssessmentFindingsRequest {
  assessmentId: string;
  xOrgId: string;
  xUserId?: string | null;
}

export interface ListCaseFindingsRequest {
  caseId: string;
  xOrgId: string;
  xUserId?: string | null;
}

export interface ListFindingsRequest {
  xOrgId: string;
  caseId?: string | null;
  assessmentId?: string | null;
  status?: string | null;
  severity?: string | null;
  riskType?: string | null;
  xUserId?: string | null;
}

export interface UpdateFindingRequest {
  findingId: string;
  xOrgId: string;
  findingUpdate: FindingUpdate;
  xUserId?: string | null;
}

/**
 *
 */
export class FindingsApi extends runtime.BaseAPI {
  /**
   * Create Case Finding
   */
  async createCaseFindingRaw(
    requestParameters: CreateCaseFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindingRead>> {
    if (requestParameters["caseId"] == null) {
      throw new runtime.RequiredError(
        "caseId",
        'Required parameter "caseId" was null or undefined when calling createCaseFinding().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling createCaseFinding().',
      );
    }

    if (requestParameters["findingCreate"] == null) {
      throw new runtime.RequiredError(
        "findingCreate",
        'Required parameter "findingCreate" was null or undefined when calling createCaseFinding().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/cases/{case_id}/findings`.replace(
          `{${"case_id"}}`,
          encodeURIComponent(String(requestParameters["caseId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: FindingCreateToJSON(requestParameters["findingCreate"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindingReadFromJSON(jsonValue),
    );
  }

  /**
   * Create Case Finding
   */
  async createCaseFinding(
    requestParameters: CreateCaseFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindingRead> {
    const response = await this.createCaseFindingRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Finding
   */
  async getFindingRaw(
    requestParameters: GetFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindingRead>> {
    if (requestParameters["findingId"] == null) {
      throw new runtime.RequiredError(
        "findingId",
        'Required parameter "findingId" was null or undefined when calling getFinding().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling getFinding().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/findings/{finding_id}`.replace(
          `{${"finding_id"}}`,
          encodeURIComponent(String(requestParameters["findingId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindingReadFromJSON(jsonValue),
    );
  }

  /**
   * Get Finding
   */
  async getFinding(
    requestParameters: GetFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindingRead> {
    const response = await this.getFindingRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Finding Evidence
   */
  async getFindingEvidenceRaw(
    requestParameters: GetFindingEvidenceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<EvidenceRead>>> {
    if (requestParameters["findingId"] == null) {
      throw new runtime.RequiredError(
        "findingId",
        'Required parameter "findingId" was null or undefined when calling getFindingEvidence().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling getFindingEvidence().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/findings/{finding_id}/evidence`.replace(
          `{${"finding_id"}}`,
          encodeURIComponent(String(requestParameters["findingId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(EvidenceReadFromJSON),
    );
  }

  /**
   * Get Finding Evidence
   */
  async getFindingEvidence(
    requestParameters: GetFindingEvidenceRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<EvidenceRead>> {
    const response = await this.getFindingEvidenceRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * List Assessment Findings
   */
  async listAssessmentFindingsRaw(
    requestParameters: ListAssessmentFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<FindingRead>>> {
    if (requestParameters["assessmentId"] == null) {
      throw new runtime.RequiredError(
        "assessmentId",
        'Required parameter "assessmentId" was null or undefined when calling listAssessmentFindings().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling listAssessmentFindings().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/assessments/{assessment_id}/findings`.replace(
          `{${"assessment_id"}}`,
          encodeURIComponent(String(requestParameters["assessmentId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(FindingReadFromJSON),
    );
  }

  /**
   * List Assessment Findings
   */
  async listAssessmentFindings(
    requestParameters: ListAssessmentFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<FindingRead>> {
    const response = await this.listAssessmentFindingsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * List Case Findings
   */
  async listCaseFindingsRaw(
    requestParameters: ListCaseFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<FindingRead>>> {
    if (requestParameters["caseId"] == null) {
      throw new runtime.RequiredError(
        "caseId",
        'Required parameter "caseId" was null or undefined when calling listCaseFindings().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling listCaseFindings().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/cases/{case_id}/findings`.replace(
          `{${"case_id"}}`,
          encodeURIComponent(String(requestParameters["caseId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(FindingReadFromJSON),
    );
  }

  /**
   * List Case Findings
   */
  async listCaseFindings(
    requestParameters: ListCaseFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<FindingRead>> {
    const response = await this.listCaseFindingsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * List Findings
   */
  async listFindingsRaw(
    requestParameters: ListFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<FindingRead>>> {
    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling listFindings().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["caseId"] != null) {
      queryParameters["case_id"] = requestParameters["caseId"];
    }

    if (requestParameters["assessmentId"] != null) {
      queryParameters["assessment_id"] = requestParameters["assessmentId"];
    }

    if (requestParameters["status"] != null) {
      queryParameters["status"] = requestParameters["status"];
    }

    if (requestParameters["severity"] != null) {
      queryParameters["severity"] = requestParameters["severity"];
    }

    if (requestParameters["riskType"] != null) {
      queryParameters["risk_type"] = requestParameters["riskType"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/findings`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(FindingReadFromJSON),
    );
  }

  /**
   * List Findings
   */
  async listFindings(
    requestParameters: ListFindingsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<FindingRead>> {
    const response = await this.listFindingsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Update Finding
   */
  async updateFindingRaw(
    requestParameters: UpdateFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<FindingRead>> {
    if (requestParameters["findingId"] == null) {
      throw new runtime.RequiredError(
        "findingId",
        'Required parameter "findingId" was null or undefined when calling updateFinding().',
      );
    }

    if (requestParameters["xOrgId"] == null) {
      throw new runtime.RequiredError(
        "xOrgId",
        'Required parameter "xOrgId" was null or undefined when calling updateFinding().',
      );
    }

    if (requestParameters["findingUpdate"] == null) {
      throw new runtime.RequiredError(
        "findingUpdate",
        'Required parameter "findingUpdate" was null or undefined when calling updateFinding().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (requestParameters["xOrgId"] != null) {
      headerParameters["X-Org-Id"] = String(requestParameters["xOrgId"]);
    }

    if (requestParameters["xUserId"] != null) {
      headerParameters["X-User-Id"] = String(requestParameters["xUserId"]);
    }

    const response = await this.request(
      {
        path: `/api/v1/findings/{finding_id}`.replace(
          `{${"finding_id"}}`,
          encodeURIComponent(String(requestParameters["findingId"])),
        ),
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: FindingUpdateToJSON(requestParameters["findingUpdate"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      FindingReadFromJSON(jsonValue),
    );
  }

  /**
   * Update Finding
   */
  async updateFinding(
    requestParameters: UpdateFindingRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<FindingRead> {
    const response = await this.updateFindingRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
