/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { ErrorResponse, WindowAnalyticsRead } from "../models/index";
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  WindowAnalyticsReadFromJSON,
  WindowAnalyticsReadToJSON,
} from "../models/index";

export interface ComputeWindowAnalyticsRequest {
  bankId: string;
  startDate: Date;
  endDate: Date;
}

/**
 *
 */
export class WindowAnalyticsApi extends runtime.BaseAPI {
  /**
   * Engine-computed analytics over [start_date, end_date]: per-period ratio series (stored baseline runs first, inline fallback), window statistics, and daily-snapshot aggregates per module.
   * Compute Window Analytics
   */
  async computeWindowAnalyticsRaw(
    requestParameters: ComputeWindowAnalyticsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WindowAnalyticsRead>> {
    if (requestParameters["bankId"] == null) {
      throw new runtime.RequiredError(
        "bankId",
        'Required parameter "bankId" was null or undefined when calling computeWindowAnalytics().',
      );
    }

    if (requestParameters["startDate"] == null) {
      throw new runtime.RequiredError(
        "startDate",
        'Required parameter "startDate" was null or undefined when calling computeWindowAnalytics().',
      );
    }

    if (requestParameters["endDate"] == null) {
      throw new runtime.RequiredError(
        "endDate",
        'Required parameter "endDate" was null or undefined when calling computeWindowAnalytics().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["startDate"] != null) {
      queryParameters["start_date"] = (requestParameters["startDate"] as any)
        .toISOString()
        .substring(0, 10);
    }

    if (requestParameters["endDate"] != null) {
      queryParameters["end_date"] = (requestParameters["endDate"] as any)
        .toISOString()
        .substring(0, 10);
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("HTTPBearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/v1/banks/{bank_id}/analytics/window`.replace(
          `{${"bank_id"}}`,
          encodeURIComponent(String(requestParameters["bankId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WindowAnalyticsReadFromJSON(jsonValue),
    );
  }

  /**
   * Engine-computed analytics over [start_date, end_date]: per-period ratio series (stored baseline runs first, inline fallback), window statistics, and daily-snapshot aggregates per module.
   * Compute Window Analytics
   */
  async computeWindowAnalytics(
    requestParameters: ComputeWindowAnalyticsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WindowAnalyticsRead> {
    const response = await this.computeWindowAnalyticsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
