/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SensitivityScope } from "./SensitivityScope";
import {
  SensitivityScopeFromJSON,
  SensitivityScopeFromJSONTyped,
  SensitivityScopeToJSON,
  SensitivityScopeToJSONTyped,
} from "./SensitivityScope";
import type { Reference } from "./Reference";
import {
  ReferenceFromJSON,
  ReferenceFromJSONTyped,
  ReferenceToJSON,
  ReferenceToJSONTyped,
} from "./Reference";
import type { InstitutionScope } from "./InstitutionScope";
import {
  InstitutionScopeFromJSON,
  InstitutionScopeFromJSONTyped,
  InstitutionScopeToJSON,
  InstitutionScopeToJSONTyped,
} from "./InstitutionScope";
import type { ModuleScope } from "./ModuleScope";
import {
  ModuleScopeFromJSON,
  ModuleScopeFromJSONTyped,
  ModuleScopeToJSON,
  ModuleScopeToJSONTyped,
} from "./ModuleScope";
import type { GrantReasonCategory } from "./GrantReasonCategory";
import {
  GrantReasonCategoryFromJSON,
  GrantReasonCategoryFromJSONTyped,
  GrantReasonCategoryToJSON,
  GrantReasonCategoryToJSONTyped,
} from "./GrantReasonCategory";
import type { GrantTargetInstitutionID } from "./GrantTargetInstitutionID";
import {
  GrantTargetInstitutionIDFromJSON,
  GrantTargetInstitutionIDFromJSONTyped,
  GrantTargetInstitutionIDToJSON,
  GrantTargetInstitutionIDToJSONTyped,
} from "./GrantTargetInstitutionID";
import type { ValidUntil } from "./ValidUntil";
import {
  ValidUntilFromJSON,
  ValidUntilFromJSONTyped,
  ValidUntilToJSON,
  ValidUntilToJSONTyped,
} from "./ValidUntil";

/**
 *
 * @export
 * @interface AccessRequestApprove
 */
export interface AccessRequestApprove {
  /**
   *
   * @type {string}
   * @memberof AccessRequestApprove
   */
  expectedAuthoritySentence: string;
  /**
   *
   * @type {GrantTargetInstitutionID}
   * @memberof AccessRequestApprove
   */
  institutionId?: GrantTargetInstitutionID;
  /**
   *
   * @type {InstitutionScope}
   * @memberof AccessRequestApprove
   */
  institutionScope: InstitutionScope;
  /**
   *
   * @type {ModuleScope}
   * @memberof AccessRequestApprove
   */
  moduleScope: ModuleScope;
  /**
   *
   * @type {GrantReasonCategory}
   * @memberof AccessRequestApprove
   */
  reasonCategory: GrantReasonCategory;
  /**
   *
   * @type {string}
   * @memberof AccessRequestApprove
   */
  reasonDetail?: string;
  /**
   *
   * @type {Reference}
   * @memberof AccessRequestApprove
   */
  reference?: Reference;
  /**
   *
   * @type {string}
   * @memberof AccessRequestApprove
   */
  roleBundle: AccessRequestApproveRoleBundleEnum;
  /**
   *
   * @type {SensitivityScope}
   * @memberof AccessRequestApprove
   */
  sensitivityScope: SensitivityScope;
  /**
   *
   * @type {ValidUntil}
   * @memberof AccessRequestApprove
   */
  validUntil?: ValidUntil;
}

/**
 * @export
 */
export const AccessRequestApproveRoleBundleEnum = {
  Viewer: "viewer",
  Auditor: "auditor",
  Analyst: "analyst",
  Approver: "approver",
  Validator: "validator",
  AccountAdmin: "account_admin",
} as const;
export type AccessRequestApproveRoleBundleEnum =
  (typeof AccessRequestApproveRoleBundleEnum)[keyof typeof AccessRequestApproveRoleBundleEnum];

/**
 * Check if a given object implements the AccessRequestApprove interface.
 */
export function instanceOfAccessRequestApprove(
  value: object,
): value is AccessRequestApprove {
  if (
    !("expectedAuthoritySentence" in value) ||
    value["expectedAuthoritySentence"] === undefined
  )
    return false;
  if (!("institutionScope" in value) || value["institutionScope"] === undefined)
    return false;
  if (!("moduleScope" in value) || value["moduleScope"] === undefined)
    return false;
  if (!("reasonCategory" in value) || value["reasonCategory"] === undefined)
    return false;
  if (!("roleBundle" in value) || value["roleBundle"] === undefined)
    return false;
  if (!("sensitivityScope" in value) || value["sensitivityScope"] === undefined)
    return false;
  return true;
}

export function AccessRequestApproveFromJSON(json: any): AccessRequestApprove {
  return AccessRequestApproveFromJSONTyped(json, false);
}

export function AccessRequestApproveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AccessRequestApprove {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    expectedAuthoritySentence: json["expected_authority_sentence"],
    institutionId:
      json["institution_id"] == null
        ? undefined
        : GrantTargetInstitutionIDFromJSON(json["institution_id"]),
    institutionScope: InstitutionScopeFromJSON(json["institution_scope"]),
    moduleScope: ModuleScopeFromJSON(json["module_scope"]),
    reasonCategory: GrantReasonCategoryFromJSON(json["reason_category"]),
    reasonDetail:
      json["reason_detail"] == null ? undefined : json["reason_detail"],
    reference:
      json["reference"] == null
        ? undefined
        : ReferenceFromJSON(json["reference"]),
    roleBundle: json["role_bundle"],
    sensitivityScope: SensitivityScopeFromJSON(json["sensitivity_scope"]),
    validUntil:
      json["valid_until"] == null
        ? undefined
        : ValidUntilFromJSON(json["valid_until"]),
  };
}

export function AccessRequestApproveToJSON(json: any): AccessRequestApprove {
  return AccessRequestApproveToJSONTyped(json, false);
}

export function AccessRequestApproveToJSONTyped(
  value?: AccessRequestApprove | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    expected_authority_sentence: value["expectedAuthoritySentence"],
    institution_id: GrantTargetInstitutionIDToJSON(value["institutionId"]),
    institution_scope: InstitutionScopeToJSON(value["institutionScope"]),
    module_scope: ModuleScopeToJSON(value["moduleScope"]),
    reason_category: GrantReasonCategoryToJSON(value["reasonCategory"]),
    reason_detail: value["reasonDetail"],
    reference: ReferenceToJSON(value["reference"]),
    role_bundle: value["roleBundle"],
    sensitivity_scope: SensitivityScopeToJSON(value["sensitivityScope"]),
    valid_until: ValidUntilToJSON(value["validUntil"]),
  };
}
