/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AccountName
 */
export interface AccountName {}

/**
 * Check if a given object implements the AccountName interface.
 */
export function instanceOfAccountName(value: object): value is AccountName {
  return true;
}

export function AccountNameFromJSON(json: any): AccountName {
  return AccountNameFromJSONTyped(json, false);
}

export function AccountNameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AccountName {
  return json;
}

export function AccountNameToJSON(json: any): AccountName {
  return AccountNameToJSONTyped(json, false);
}

export function AccountNameToJSONTyped(
  value?: AccountName | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
