/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActivationPeriodLabel
 */
export type ActivationPeriodLabel = string | null;

/**
 * Check if a given object implements the ActivationPeriodLabel interface.
 */
export function instanceOfActivationPeriodLabel(
  value: unknown,
): value is ActivationPeriodLabel {
  return typeof value === "string" || value === null;
}

export function ActivationPeriodLabelFromJSON(
  json: any,
): ActivationPeriodLabel {
  return ActivationPeriodLabelFromJSONTyped(json, false);
}

export function ActivationPeriodLabelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivationPeriodLabel {
  return json;
}

export function ActivationPeriodLabelToJSON(json: any): ActivationPeriodLabel {
  return ActivationPeriodLabelToJSONTyped(json, false);
}

export function ActivationPeriodLabelToJSONTyped(
  value?: ActivationPeriodLabel | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
