/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActivationFactsCreated
 */
export type ActivationFactsCreated = number | null;

/**
 * Check if a given object implements the ActivationFactsCreated interface.
 */
export function instanceOfActivationFactsCreated(
  value: unknown,
): value is ActivationFactsCreated {
  return typeof value === "number" || value === null;
}

export function ActivationFactsCreatedFromJSON(
  json: any,
): ActivationFactsCreated {
  return ActivationFactsCreatedFromJSONTyped(json, false);
}

export function ActivationFactsCreatedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivationFactsCreated {
  return json;
}

export function ActivationFactsCreatedToJSON(
  json: any,
): ActivationFactsCreated {
  return ActivationFactsCreatedToJSONTyped(json, false);
}

export function ActivationFactsCreatedToJSONTyped(
  value?: ActivationFactsCreated | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
