/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActivationModulesSucceeded
 */
export type ActivationModulesSucceeded = number | null;

/**
 * Check if a given object implements the ActivationModulesSucceeded interface.
 */
export function instanceOfActivationModulesSucceeded(
  value: unknown,
): value is ActivationModulesSucceeded {
  return typeof value === "number" || value === null;
}

export function ActivationModulesSucceededFromJSON(
  json: any,
): ActivationModulesSucceeded {
  return ActivationModulesSucceededFromJSONTyped(json, false);
}

export function ActivationModulesSucceededFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActivationModulesSucceeded {
  return json;
}

export function ActivationModulesSucceededToJSON(
  json: any,
): ActivationModulesSucceeded {
  return ActivationModulesSucceededToJSONTyped(json, false);
}

export function ActivationModulesSucceededToJSONTyped(
  value?: ActivationModulesSucceeded | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
