/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ActualGhs
 */
export type ActualGhs = string | null;

/**
 * Check if a given object implements the ActualGhs interface.
 */
export function instanceOfActualGhs(value: unknown): value is ActualGhs {
  return typeof value === "string" || value === null;
}

export function ActualGhsFromJSON(json: any): ActualGhs {
  return ActualGhsFromJSONTyped(json, false);
}

export function ActualGhsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ActualGhs {
  return json;
}

export function ActualGhsToJSON(json: any): ActualGhs {
  return ActualGhsToJSONTyped(json, false);
}

export function ActualGhsToJSONTyped(
  value?: ActualGhs | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
