/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AnnualFees
 */
export type AnnualFees = number | string | null;

/**
 * Check if a given object implements the AnnualFees interface.
 */
export function instanceOfAnnualFees(value: unknown): value is AnnualFees {
  return (
    typeof value === "number" || typeof value === "string" || value === null
  );
}

export function AnnualFeesFromJSON(json: any): AnnualFees {
  return AnnualFeesFromJSONTyped(json, false);
}

export function AnnualFeesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AnnualFees {
  return json;
}

export function AnnualFeesToJSON(json: any): AnnualFees {
  return AnnualFeesToJSONTyped(json, false);
}

export function AnnualFeesToJSONTyped(
  value?: AnnualFees | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
