/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApprovalExpiresAt
 */
export type ApprovalExpiresAt = string | null;

/**
 * Check if a given object implements the ApprovalExpiresAt interface.
 */
export function instanceOfApprovalExpiresAt(
  value: unknown,
): value is ApprovalExpiresAt {
  return typeof value === "string" || value === null;
}

export function ApprovalExpiresAtFromJSON(json: any): ApprovalExpiresAt {
  return ApprovalExpiresAtFromJSONTyped(json, false);
}

export function ApprovalExpiresAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ApprovalExpiresAt {
  return json;
}

export function ApprovalExpiresAtToJSON(json: any): ApprovalExpiresAt {
  return ApprovalExpiresAtToJSONTyped(json, false);
}

export function ApprovalExpiresAtToJSONTyped(
  value?: ApprovalExpiresAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
