/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ArtifactFormat
 */
export type ArtifactFormat = "csv" | "xlsx" | "pdf" | null;

/**
 * Check if a given object implements the ArtifactFormat interface.
 */
export function instanceOfArtifactFormat(
  value: unknown,
): value is ArtifactFormat {
  return (
    ["csv", "xlsx", "pdf"].indexOf(value as never) !== -1 || value === null
  );
}

export function ArtifactFormatFromJSON(json: any): ArtifactFormat {
  return ArtifactFormatFromJSONTyped(json, false);
}

export function ArtifactFormatFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ArtifactFormat {
  return json;
}

export function ArtifactFormatToJSON(json: any): ArtifactFormat {
  return ArtifactFormatToJSONTyped(json, false);
}

export function ArtifactFormatToJSONTyped(
  value?: ArtifactFormat | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
