/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AssumptionApproverName
 */
export type AssumptionApproverName = string | null;

/**
 * Check if a given object implements the AssumptionApproverName interface.
 */
export function instanceOfAssumptionApproverName(
  value: unknown,
): value is AssumptionApproverName {
  return typeof value === "string" || value === null;
}

export function AssumptionApproverNameFromJSON(
  json: any,
): AssumptionApproverName {
  return AssumptionApproverNameFromJSONTyped(json, false);
}

export function AssumptionApproverNameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssumptionApproverName {
  return json;
}

export function AssumptionApproverNameToJSON(
  json: any,
): AssumptionApproverName {
  return AssumptionApproverNameToJSONTyped(json, false);
}

export function AssumptionApproverNameToJSONTyped(
  value?: AssumptionApproverName | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
