/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssumptionValue } from "./AssumptionValue";
import {
  AssumptionValueFromJSON,
  AssumptionValueFromJSONTyped,
  AssumptionValueToJSON,
  AssumptionValueToJSONTyped,
} from "./AssumptionValue";
import type { AssumptionCategory } from "./AssumptionCategory";
import {
  AssumptionCategoryFromJSON,
  AssumptionCategoryFromJSONTyped,
  AssumptionCategoryToJSON,
  AssumptionCategoryToJSONTyped,
} from "./AssumptionCategory";
import type { Unit } from "./Unit";
import {
  UnitFromJSON,
  UnitFromJSONTyped,
  UnitToJSON,
  UnitToJSONTyped,
} from "./Unit";

/**
 *
 * @export
 * @interface AssumptionUpdate
 */
export interface AssumptionUpdate {
  /**
   *
   * @type {AssumptionCategory}
   * @memberof AssumptionUpdate
   */
  category?: AssumptionCategory;
  /**
   *
   * @type {string}
   * @memberof AssumptionUpdate
   */
  label?: string;
  /**
   *
   * @type {{ [key: string]: AssumptionValue; }}
   * @memberof AssumptionUpdate
   */
  provenance?: { [key: string]: AssumptionValue };
  /**
   *
   * @type {string}
   * @memberof AssumptionUpdate
   */
  reason: string;
  /**
   *
   * @type {Unit}
   * @memberof AssumptionUpdate
   */
  unit?: Unit;
  /**
   *
   * @type {AssumptionValue}
   * @memberof AssumptionUpdate
   */
  value?: AssumptionValue | null;
}

/**
 * Check if a given object implements the AssumptionUpdate interface.
 */
export function instanceOfAssumptionUpdate(
  value: object,
): value is AssumptionUpdate {
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function AssumptionUpdateFromJSON(json: any): AssumptionUpdate {
  return AssumptionUpdateFromJSONTyped(json, false);
}

export function AssumptionUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssumptionUpdate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    category:
      json["category"] == null
        ? undefined
        : AssumptionCategoryFromJSON(json["category"]),
    label: json["label"] == null ? undefined : json["label"],
    provenance:
      json["provenance"] == null
        ? undefined
        : mapValues(json["provenance"], AssumptionValueFromJSON),
    reason: json["reason"],
    unit: json["unit"] == null ? undefined : UnitFromJSON(json["unit"]),
    value:
      json["value"] == null
        ? undefined
        : AssumptionValueFromJSON(json["value"]),
  };
}

export function AssumptionUpdateToJSON(json: any): AssumptionUpdate {
  return AssumptionUpdateToJSONTyped(json, false);
}

export function AssumptionUpdateToJSONTyped(
  value?: AssumptionUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    category: AssumptionCategoryToJSON(value["category"]),
    label: value["label"],
    provenance:
      value["provenance"] == null
        ? undefined
        : mapValues(value["provenance"], AssumptionValueToJSON),
    reason: value["reason"],
    unit: UnitToJSON(value["unit"]),
    value: AssumptionValueToJSON(value["value"]),
  };
}
