/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const AttestationState = {
  Unsigned: "unsigned",
  PreparerCertified: "preparer_certified",
  FullyCertified: "fully_certified",
  Void: "void",
} as const;
export type AttestationState =
  (typeof AttestationState)[keyof typeof AttestationState];

export function instanceOfAttestationState(value: any): boolean {
  for (const key in AttestationState) {
    if (Object.prototype.hasOwnProperty.call(AttestationState, key)) {
      if (AttestationState[key as keyof typeof AttestationState] === value) {
        return true;
      }
    }
  }
  return false;
}

export function AttestationStateFromJSON(json: any): AttestationState {
  return AttestationStateFromJSONTyped(json, false);
}

export function AttestationStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AttestationState {
  return json as AttestationState;
}

export function AttestationStateToJSON(value?: AttestationState | null): any {
  return value as any;
}

export function AttestationStateToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): AttestationState {
  return value as AttestationState;
}
