/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BehavioralMethod } from "./BehavioralMethod";
import {
  BehavioralMethodFromJSON,
  BehavioralMethodFromJSONTyped,
  BehavioralMethodToJSON,
  BehavioralMethodToJSONTyped,
} from "./BehavioralMethod";
import type { IncentivePoint } from "./IncentivePoint";
import {
  IncentivePointFromJSON,
  IncentivePointFromJSONTyped,
  IncentivePointToJSON,
  IncentivePointToJSONTyped,
} from "./IncentivePoint";

/**
 *
 * @export
 * @interface BehavioralProductEstimate
 */
export interface BehavioralProductEstimate {
  /**
   *
   * @type {string}
   * @memberof BehavioralProductEstimate
   */
  assumptionType: string;
  /**
   *
   * @type {number}
   * @memberof BehavioralProductEstimate
   */
  confidence: number;
  /**
   *
   * @type {number}
   * @memberof BehavioralProductEstimate
   */
  corePct?: number | null;
  /**
   *
   * @type {Array<IncentivePoint>}
   * @memberof BehavioralProductEstimate
   */
  incentiveCurve?: Array<IncentivePoint> | null;
  /**
   *
   * @type {BehavioralMethod}
   * @memberof BehavioralProductEstimate
   */
  method: BehavioralMethod;
  /**
   *
   * @type {string}
   * @memberof BehavioralProductEstimate
   */
  productCode: string;
  /**
   *
   * @type {string}
   * @memberof BehavioralProductEstimate
   */
  unit: string;
  /**
   *
   * @type {number}
   * @memberof BehavioralProductEstimate
   */
  value: number;
}

/**
 * Check if a given object implements the BehavioralProductEstimate interface.
 */
export function instanceOfBehavioralProductEstimate(
  value: object,
): value is BehavioralProductEstimate {
  if (!("assumptionType" in value) || value["assumptionType"] === undefined)
    return false;
  if (!("confidence" in value) || value["confidence"] === undefined)
    return false;
  if (!("method" in value) || value["method"] === undefined) return false;
  if (!("productCode" in value) || value["productCode"] === undefined)
    return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function BehavioralProductEstimateFromJSON(
  json: any,
): BehavioralProductEstimate {
  return BehavioralProductEstimateFromJSONTyped(json, false);
}

export function BehavioralProductEstimateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BehavioralProductEstimate {
  if (json == null) {
    return json;
  }
  return {
    assumptionType: json["assumptionType"],
    confidence: json["confidence"],
    corePct: json["corePct"] == null ? undefined : json["corePct"],
    incentiveCurve:
      json["incentiveCurve"] == null
        ? undefined
        : (json["incentiveCurve"] as Array<any>).map(IncentivePointFromJSON),
    method: BehavioralMethodFromJSON(json["method"]),
    productCode: json["productCode"],
    unit: json["unit"],
    value: json["value"],
  };
}

export function BehavioralProductEstimateToJSON(
  json: any,
): BehavioralProductEstimate {
  return BehavioralProductEstimateToJSONTyped(json, false);
}

export function BehavioralProductEstimateToJSONTyped(
  value?: BehavioralProductEstimate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    assumptionType: value["assumptionType"],
    confidence: value["confidence"],
    corePct: value["corePct"],
    incentiveCurve:
      value["incentiveCurve"] == null
        ? undefined
        : (value["incentiveCurve"] as Array<any>).map(IncentivePointToJSON),
    method: BehavioralMethodToJSON(value["method"]),
    productCode: value["productCode"],
    unit: value["unit"],
    value: value["value"],
  };
}
