/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BiPackQueryPivot } from "./BiPackQueryPivot";
import {
  BiPackQueryPivotFromJSON,
  BiPackQueryPivotFromJSONTyped,
  BiPackQueryPivotToJSON,
  BiPackQueryPivotToJSONTyped,
} from "./BiPackQueryPivot";
import type { BiQuery } from "./BiQuery";
import {
  BiQueryFromJSON,
  BiQueryFromJSONTyped,
  BiQueryToJSON,
  BiQueryToJSONTyped,
} from "./BiQuery";
import type { BiFilter } from "./BiFilter";
import {
  BiFilterFromJSON,
  BiFilterFromJSONTyped,
  BiFilterToJSON,
  BiFilterToJSONTyped,
} from "./BiFilter";
import type { BiSort } from "./BiSort";
import {
  BiSortFromJSON,
  BiSortFromJSONTyped,
  BiSortToJSON,
  BiSortToJSONTyped,
} from "./BiSort";
import type { BiTime } from "./BiTime";
import {
  BiTimeFromJSON,
  BiTimeFromJSONTyped,
  BiTimeToJSON,
  BiTimeToJSONTyped,
} from "./BiTime";
import type { Limit } from "./Limit";
import {
  LimitFromJSON,
  LimitFromJSONTyped,
  LimitToJSON,
  LimitToJSONTyped,
} from "./Limit";
import type { BiPackQueryTopN } from "./BiPackQueryTopN";
import {
  BiPackQueryTopNFromJSON,
  BiPackQueryTopNFromJSONTyped,
  BiPackQueryTopNToJSON,
  BiPackQueryTopNToJSONTyped,
} from "./BiPackQueryTopN";

/**
 *
 * @export
 * @interface BiAskReadQuery
 */
export interface BiAskReadQuery {
  /**
   *
   * @type {Array<string>}
   * @memberof BiAskReadQuery
   */
  dimensions?: Array<string>;
  /**
   *
   * @type {Array<BiFilter>}
   * @memberof BiAskReadQuery
   */
  filters?: Array<BiFilter>;
  /**
   *
   * @type {Limit}
   * @memberof BiAskReadQuery
   */
  limit?: Limit;
  /**
   *
   * @type {Array<string>}
   * @memberof BiAskReadQuery
   */
  measures: Array<string>;
  /**
   *
   * @type {number}
   * @memberof BiAskReadQuery
   */
  offset?: number;
  /**
   *
   * @type {BiPackQueryPivot}
   * @memberof BiAskReadQuery
   */
  pivot?: BiPackQueryPivot;
  /**
   *
   * @type {Array<BiSort>}
   * @memberof BiAskReadQuery
   */
  sort?: Array<BiSort>;
  /**
   *
   * @type {boolean}
   * @memberof BiAskReadQuery
   */
  subtotals?: boolean;
  /**
   *
   * @type {BiTime}
   * @memberof BiAskReadQuery
   */
  time: BiTime;
  /**
   *
   * @type {BiPackQueryTopN}
   * @memberof BiAskReadQuery
   */
  topN?: BiPackQueryTopN;
}

/**
 * Check if a given object implements the BiAskReadQuery interface.
 */
export function instanceOfBiAskReadQuery(
  value: object,
): value is BiAskReadQuery {
  if (!("measures" in value) || value["measures"] === undefined) return false;
  if (!("time" in value) || value["time"] === undefined) return false;
  return true;
}

export function BiAskReadQueryFromJSON(json: any): BiAskReadQuery {
  return BiAskReadQueryFromJSONTyped(json, false);
}

export function BiAskReadQueryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BiAskReadQuery {
  if (json == null) {
    return json;
  }
  return {
    dimensions: json["dimensions"] == null ? undefined : json["dimensions"],
    filters:
      json["filters"] == null
        ? undefined
        : (json["filters"] as Array<any>).map(BiFilterFromJSON),
    limit: json["limit"] == null ? undefined : LimitFromJSON(json["limit"]),
    measures: json["measures"],
    offset: json["offset"] == null ? undefined : json["offset"],
    pivot:
      json["pivot"] == null
        ? undefined
        : BiPackQueryPivotFromJSON(json["pivot"]),
    sort:
      json["sort"] == null
        ? undefined
        : (json["sort"] as Array<any>).map(BiSortFromJSON),
    subtotals: json["subtotals"] == null ? undefined : json["subtotals"],
    time: BiTimeFromJSON(json["time"]),
    topN:
      json["top_n"] == null
        ? undefined
        : BiPackQueryTopNFromJSON(json["top_n"]),
  };
}

export function BiAskReadQueryToJSON(json: any): BiAskReadQuery {
  return BiAskReadQueryToJSONTyped(json, false);
}

export function BiAskReadQueryToJSONTyped(
  value?: BiAskReadQuery | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    dimensions: value["dimensions"],
    filters:
      value["filters"] == null
        ? undefined
        : (value["filters"] as Array<any>).map(BiFilterToJSON),
    limit: LimitToJSON(value["limit"]),
    measures: value["measures"],
    offset: value["offset"],
    pivot: BiPackQueryPivotToJSON(value["pivot"]),
    sort:
      value["sort"] == null
        ? undefined
        : (value["sort"] as Array<any>).map(BiSortToJSON),
    subtotals: value["subtotals"],
    time: BiTimeToJSON(value["time"]),
    top_n: BiPackQueryTopNToJSON(value["topN"]),
  };
}
