/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The complete set of identities a ``users``-visibility dashboard reaches.
 *
 * Replacing the whole set rather than adding one at a time makes revocation an
 * ordinary save: an identity absent from the list loses reachability in the
 * same transaction the rest keep it.
 * @export
 * @interface BiDashboardShareRequest
 */
export interface BiDashboardShareRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof BiDashboardShareRequest
   */
  userIds?: Array<string>;
}

/**
 * Check if a given object implements the BiDashboardShareRequest interface.
 */
export function instanceOfBiDashboardShareRequest(
  value: object,
): value is BiDashboardShareRequest {
  return true;
}

export function BiDashboardShareRequestFromJSON(
  json: any,
): BiDashboardShareRequest {
  return BiDashboardShareRequestFromJSONTyped(json, false);
}

export function BiDashboardShareRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BiDashboardShareRequest {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    userIds: json["user_ids"] == null ? undefined : json["user_ids"],
  };
}

export function BiDashboardShareRequestToJSON(
  json: any,
): BiDashboardShareRequest {
  return BiDashboardShareRequestToJSONTyped(json, false);
}

export function BiDashboardShareRequestToJSONTyped(
  value?: BiDashboardShareRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    user_ids: value["userIds"],
  };
}
