/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DisplayName } from "./DisplayName";
import {
  DisplayNameFromJSON,
  DisplayNameFromJSONTyped,
  DisplayNameToJSON,
  DisplayNameToJSONTyped,
} from "./DisplayName";

/**
 * One identity a dashboard is reachable by.
 * @export
 * @interface BiDashboardShareRead
 */
export interface BiDashboardShareRead {
  /**
   *
   * @type {DisplayName}
   * @memberof BiDashboardShareRead
   */
  displayName: DisplayName;
  /**
   *
   * @type {string}
   * @memberof BiDashboardShareRead
   */
  email: string;
  /**
   *
   * @type {Date}
   * @memberof BiDashboardShareRead
   */
  sharedAt: Date;
  /**
   *
   * @type {string}
   * @memberof BiDashboardShareRead
   */
  userId: string;
}

/**
 * Check if a given object implements the BiDashboardShareRead interface.
 */
export function instanceOfBiDashboardShareRead(
  value: object,
): value is BiDashboardShareRead {
  if (!("displayName" in value) || value["displayName"] === undefined)
    return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("sharedAt" in value) || value["sharedAt"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  return true;
}

export function BiDashboardShareReadFromJSON(json: any): BiDashboardShareRead {
  return BiDashboardShareReadFromJSONTyped(json, false);
}

export function BiDashboardShareReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BiDashboardShareRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    displayName: DisplayNameFromJSON(json["display_name"]),
    email: json["email"],
    sharedAt: new Date(json["shared_at"]),
    userId: json["user_id"],
  };
}

export function BiDashboardShareReadToJSON(json: any): BiDashboardShareRead {
  return BiDashboardShareReadToJSONTyped(json, false);
}

export function BiDashboardShareReadToJSONTyped(
  value?: BiDashboardShareRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    display_name: DisplayNameToJSON(value["displayName"]),
    email: value["email"],
    shared_at: value["sharedAt"].toISOString(),
    user_id: value["userId"],
  };
}
