/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { VisibilityRole } from "./VisibilityRole";
import {
  VisibilityRoleFromJSON,
  VisibilityRoleFromJSONTyped,
  VisibilityRoleToJSON,
  VisibilityRoleToJSONTyped,
} from "./VisibilityRole";
import type { BiDashboardSpec } from "./BiDashboardSpec";
import {
  BiDashboardSpecFromJSON,
  BiDashboardSpecFromJSONTyped,
  BiDashboardSpecToJSON,
  BiDashboardSpecToJSONTyped,
} from "./BiDashboardSpec";

/**
 * Replace a dashboard's canvas and its reachability, appending a version.
 *
 * Complete rather than partial: a canvas is edited as a whole, and a PATCH of
 * one widget would leave the append-only history holding fragments that no
 * version ever rendered.
 * @export
 * @interface BiDashboardUpdateRequest
 */
export interface BiDashboardUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof BiDashboardUpdateRequest
   */
  changeNote?: string;
  /**
   *
   * @type {string}
   * @memberof BiDashboardUpdateRequest
   */
  description?: string;
  /**
   *
   * @type {BiDashboardSpec}
   * @memberof BiDashboardUpdateRequest
   */
  spec: BiDashboardSpec;
  /**
   *
   * @type {string}
   * @memberof BiDashboardUpdateRequest
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof BiDashboardUpdateRequest
   */
  visibility: BiDashboardUpdateRequestVisibilityEnum;
  /**
   *
   * @type {VisibilityRole}
   * @memberof BiDashboardUpdateRequest
   */
  visibilityRole?: VisibilityRole;
}

/**
 * @export
 */
export const BiDashboardUpdateRequestVisibilityEnum = {
  Private: "private",
  Users: "users",
  Role: "role",
  Org: "org",
} as const;
export type BiDashboardUpdateRequestVisibilityEnum =
  (typeof BiDashboardUpdateRequestVisibilityEnum)[keyof typeof BiDashboardUpdateRequestVisibilityEnum];

/**
 * Check if a given object implements the BiDashboardUpdateRequest interface.
 */
export function instanceOfBiDashboardUpdateRequest(
  value: object,
): value is BiDashboardUpdateRequest {
  if (!("spec" in value) || value["spec"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (!("visibility" in value) || value["visibility"] === undefined)
    return false;
  return true;
}

export function BiDashboardUpdateRequestFromJSON(
  json: any,
): BiDashboardUpdateRequest {
  return BiDashboardUpdateRequestFromJSONTyped(json, false);
}

export function BiDashboardUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BiDashboardUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    changeNote: json["change_note"] == null ? undefined : json["change_note"],
    description: json["description"] == null ? undefined : json["description"],
    spec: BiDashboardSpecFromJSON(json["spec"]),
    title: json["title"],
    visibility: json["visibility"],
    visibilityRole:
      json["visibility_role"] == null
        ? undefined
        : VisibilityRoleFromJSON(json["visibility_role"]),
  };
}

export function BiDashboardUpdateRequestToJSON(
  json: any,
): BiDashboardUpdateRequest {
  return BiDashboardUpdateRequestToJSONTyped(json, false);
}

export function BiDashboardUpdateRequestToJSONTyped(
  value?: BiDashboardUpdateRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    change_note: value["changeNote"],
    description: value["description"],
    spec: BiDashboardSpecToJSON(value["spec"]),
    title: value["title"],
    visibility: value["visibility"],
    visibility_role: VisibilityRoleToJSON(value["visibilityRole"]),
  };
}
