/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AdvisoryDesignation } from "./AdvisoryDesignation";
import {
  AdvisoryDesignationFromJSON,
  AdvisoryDesignationFromJSONTyped,
  AdvisoryDesignationToJSON,
  AdvisoryDesignationToJSONTyped,
} from "./AdvisoryDesignation";

/**
 * One statement the platform is prepared to make about a reporting date.
 * @export
 * @interface BiInsightRead
 */
export interface BiInsightRead {
  /**
   *
   * @type {AdvisoryDesignation}
   * @memberof BiInsightRead
   */
  advisoryDesignation?: AdvisoryDesignation;
  /**
   *
   * @type {Date}
   * @memberof BiInsightRead
   */
  asOf: Date;
  /**
   *
   * @type {boolean}
   * @memberof BiInsightRead
   */
  certified: boolean;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  detail: string;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  emphasis: BiInsightReadEmphasisEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof BiInsightRead
   */
  evidence: Array<string>;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  favourability: BiInsightReadFavourabilityEnum;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  headline: string;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  id: string;
  /**
   *
   * @type {Array<string>}
   * @memberof BiInsightRead
   */
  measureIds: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof BiInsightRead
   */
  qualifiers: Array<string>;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  ruleId: string;
  /**
   *
   * @type {string}
   * @memberof BiInsightRead
   */
  statementClass: BiInsightReadStatementClassEnum;
}

/**
 * @export
 */
export const BiInsightReadEmphasisEnum = {
  High: "high",
  Normal: "normal",
  Low: "low",
} as const;
export type BiInsightReadEmphasisEnum =
  (typeof BiInsightReadEmphasisEnum)[keyof typeof BiInsightReadEmphasisEnum];

/**
 * @export
 */
export const BiInsightReadFavourabilityEnum = {
  Favourable: "favourable",
  Adverse: "adverse",
  Neutral: "neutral",
} as const;
export type BiInsightReadFavourabilityEnum =
  (typeof BiInsightReadFavourabilityEnum)[keyof typeof BiInsightReadFavourabilityEnum];

/**
 * @export
 */
export const BiInsightReadStatementClassEnum = {
  Movement: "movement",
  Attribution: "attribution",
  Projection: "projection",
  DataGap: "data_gap",
} as const;
export type BiInsightReadStatementClassEnum =
  (typeof BiInsightReadStatementClassEnum)[keyof typeof BiInsightReadStatementClassEnum];

/**
 * Check if a given object implements the BiInsightRead interface.
 */
export function instanceOfBiInsightRead(value: object): value is BiInsightRead {
  if (!("asOf" in value) || value["asOf"] === undefined) return false;
  if (!("certified" in value) || value["certified"] === undefined) return false;
  if (!("detail" in value) || value["detail"] === undefined) return false;
  if (!("emphasis" in value) || value["emphasis"] === undefined) return false;
  if (!("evidence" in value) || value["evidence"] === undefined) return false;
  if (!("favourability" in value) || value["favourability"] === undefined)
    return false;
  if (!("headline" in value) || value["headline"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("measureIds" in value) || value["measureIds"] === undefined)
    return false;
  if (!("qualifiers" in value) || value["qualifiers"] === undefined)
    return false;
  if (!("ruleId" in value) || value["ruleId"] === undefined) return false;
  if (!("statementClass" in value) || value["statementClass"] === undefined)
    return false;
  return true;
}

export function BiInsightReadFromJSON(json: any): BiInsightRead {
  return BiInsightReadFromJSONTyped(json, false);
}

export function BiInsightReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BiInsightRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    advisoryDesignation:
      json["advisory_designation"] == null
        ? undefined
        : AdvisoryDesignationFromJSON(json["advisory_designation"]),
    asOf: new Date(json["as_of"]),
    certified: json["certified"],
    detail: json["detail"],
    emphasis: json["emphasis"],
    evidence: json["evidence"],
    favourability: json["favourability"],
    headline: json["headline"],
    id: json["id"],
    measureIds: json["measure_ids"],
    qualifiers: json["qualifiers"],
    ruleId: json["rule_id"],
    statementClass: json["statement_class"],
  };
}

export function BiInsightReadToJSON(json: any): BiInsightRead {
  return BiInsightReadToJSONTyped(json, false);
}

export function BiInsightReadToJSONTyped(
  value?: BiInsightRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    advisory_designation: AdvisoryDesignationToJSON(
      value["advisoryDesignation"],
    ),
    as_of: value["asOf"].toISOString().substring(0, 10),
    certified: value["certified"],
    detail: value["detail"],
    emphasis: value["emphasis"],
    evidence: value["evidence"],
    favourability: value["favourability"],
    headline: value["headline"],
    id: value["id"],
    measure_ids: value["measureIds"],
    qualifiers: value["qualifiers"],
    rule_id: value["ruleId"],
    statement_class: value["statementClass"],
  };
}
