/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BoardRegisterPct
 */
export type BoardRegisterPct = string | null;

/**
 * Check if a given object implements the BoardRegisterPct interface.
 */
export function instanceOfBoardRegisterPct(
  value: unknown,
): value is BoardRegisterPct {
  return typeof value === "string" || value === null;
}

export function BoardRegisterPctFromJSON(json: any): BoardRegisterPct {
  return BoardRegisterPctFromJSONTyped(json, false);
}

export function BoardRegisterPctFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BoardRegisterPct {
  return json;
}

export function BoardRegisterPctToJSON(json: any): BoardRegisterPct {
  return BoardRegisterPctToJSONTyped(json, false);
}

export function BoardRegisterPctToJSONTyped(
  value?: BoardRegisterPct | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
