/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CalculationRerunCreate
 */
export interface CalculationRerunCreate {
  /**
   *
   * @type {Date}
   * @memberof CalculationRerunCreate
   */
  asOfDate?: Date | null;
  /**
   *
   * @type {number}
   * @memberof CalculationRerunCreate
   */
  forecastPeriods?: number | null;
}

/**
 * Check if a given object implements the CalculationRerunCreate interface.
 */
export function instanceOfCalculationRerunCreate(
  value: object,
): value is CalculationRerunCreate {
  return true;
}

export function CalculationRerunCreateFromJSON(
  json: any,
): CalculationRerunCreate {
  return CalculationRerunCreateFromJSONTyped(json, false);
}

export function CalculationRerunCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CalculationRerunCreate {
  if (json == null) {
    return json;
  }
  return {
    asOfDate:
      json["as_of_date"] == null ? undefined : new Date(json["as_of_date"]),
    forecastPeriods:
      json["forecast_periods"] == null ? undefined : json["forecast_periods"],
  };
}

export function CalculationRerunCreateToJSON(
  json: any,
): CalculationRerunCreate {
  return CalculationRerunCreateToJSONTyped(json, false);
}

export function CalculationRerunCreateToJSONTyped(
  value?: CalculationRerunCreate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of_date:
      value["asOfDate"] == null
        ? undefined
        : (value["asOfDate"] as any).toISOString().substring(0, 10),
    forecast_periods: value["forecastPeriods"],
  };
}
