/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AsOfDate } from "./AsOfDate";
import {
  AsOfDateFromJSON,
  AsOfDateFromJSONTyped,
  AsOfDateToJSON,
  AsOfDateToJSONTyped,
} from "./AsOfDate";

/**
 *
 * @export
 * @interface CalculationRunCreate
 */
export interface CalculationRunCreate {
  /**
   *
   * @type {AsOfDate}
   * @memberof CalculationRunCreate
   */
  asOfDate?: AsOfDate;
  /**
   *
   * @type {number}
   * @memberof CalculationRunCreate
   */
  forecastPeriods?: number;
  /**
   *
   * @type {string}
   * @memberof CalculationRunCreate
   */
  scenarioId: string;
}

/**
 * Check if a given object implements the CalculationRunCreate interface.
 */
export function instanceOfCalculationRunCreate(
  value: object,
): value is CalculationRunCreate {
  if (!("scenarioId" in value) || value["scenarioId"] === undefined)
    return false;
  return true;
}

export function CalculationRunCreateFromJSON(json: any): CalculationRunCreate {
  return CalculationRunCreateFromJSONTyped(json, false);
}

export function CalculationRunCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CalculationRunCreate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    asOfDate:
      json["as_of_date"] == null
        ? undefined
        : AsOfDateFromJSON(json["as_of_date"]),
    forecastPeriods:
      json["forecast_periods"] == null ? undefined : json["forecast_periods"],
    scenarioId: json["scenario_id"],
  };
}

export function CalculationRunCreateToJSON(json: any): CalculationRunCreate {
  return CalculationRunCreateToJSONTyped(json, false);
}

export function CalculationRunCreateToJSONTyped(
  value?: CalculationRunCreate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of_date: AsOfDateToJSON(value["asOfDate"]),
    forecast_periods: value["forecastPeriods"],
    scenario_id: value["scenarioId"],
  };
}
