/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Current-generation canonical record counts for one bank.
 * @export
 * @interface CanonicalCountsRead
 */
export interface CanonicalCountsRead {
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  counterparties: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  glAccounts: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  positionSnapshots: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  positions: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  products: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalCountsRead
   */
  referenceRows: number;
}

/**
 * Check if a given object implements the CanonicalCountsRead interface.
 */
export function instanceOfCanonicalCountsRead(
  value: object,
): value is CanonicalCountsRead {
  if (!("counterparties" in value) || value["counterparties"] === undefined)
    return false;
  if (!("glAccounts" in value) || value["glAccounts"] === undefined)
    return false;
  if (
    !("positionSnapshots" in value) ||
    value["positionSnapshots"] === undefined
  )
    return false;
  if (!("positions" in value) || value["positions"] === undefined) return false;
  if (!("products" in value) || value["products"] === undefined) return false;
  if (!("referenceRows" in value) || value["referenceRows"] === undefined)
    return false;
  return true;
}

export function CanonicalCountsReadFromJSON(json: any): CanonicalCountsRead {
  return CanonicalCountsReadFromJSONTyped(json, false);
}

export function CanonicalCountsReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CanonicalCountsRead {
  if (json == null) {
    return json;
  }
  return {
    counterparties: json["counterparties"],
    glAccounts: json["gl_accounts"],
    positionSnapshots: json["position_snapshots"],
    positions: json["positions"],
    products: json["products"],
    referenceRows: json["reference_rows"],
  };
}

export function CanonicalCountsReadToJSON(json: any): CanonicalCountsRead {
  return CanonicalCountsReadToJSONTyped(json, false);
}

export function CanonicalCountsReadToJSONTyped(
  value?: CanonicalCountsRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    counterparties: value["counterparties"],
    gl_accounts: value["glAccounts"],
    position_snapshots: value["positionSnapshots"],
    positions: value["positions"],
    products: value["products"],
    reference_rows: value["referenceRows"],
  };
}
