/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CanonicalPositionRead } from "./CanonicalPositionRead";
import {
  CanonicalPositionReadFromJSON,
  CanonicalPositionReadFromJSONTyped,
  CanonicalPositionReadToJSON,
  CanonicalPositionReadToJSONTyped,
} from "./CanonicalPositionRead";

/**
 *
 * @export
 * @interface CanonicalPositionListRead
 */
export interface CanonicalPositionListRead {
  /**
   *
   * @type {Date}
   * @memberof CanonicalPositionListRead
   */
  asOfDate: Date | null;
  /**
   *
   * @type {string}
   * @memberof CanonicalPositionListRead
   */
  bankId: string;
  /**
   *
   * @type {number}
   * @memberof CanonicalPositionListRead
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof CanonicalPositionListRead
   */
  offset: number;
  /**
   *
   * @type {Array<CanonicalPositionRead>}
   * @memberof CanonicalPositionListRead
   */
  positions: Array<CanonicalPositionRead>;
  /**
   *
   * @type {number}
   * @memberof CanonicalPositionListRead
   */
  total: number;
}

/**
 * Check if a given object implements the CanonicalPositionListRead interface.
 */
export function instanceOfCanonicalPositionListRead(
  value: object,
): value is CanonicalPositionListRead {
  if (!("asOfDate" in value) || value["asOfDate"] === undefined) return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("offset" in value) || value["offset"] === undefined) return false;
  if (!("positions" in value) || value["positions"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  return true;
}

export function CanonicalPositionListReadFromJSON(
  json: any,
): CanonicalPositionListRead {
  return CanonicalPositionListReadFromJSONTyped(json, false);
}

export function CanonicalPositionListReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CanonicalPositionListRead {
  if (json == null) {
    return json;
  }
  return {
    asOfDate: json["as_of_date"] == null ? null : new Date(json["as_of_date"]),
    bankId: json["bank_id"],
    limit: json["limit"],
    offset: json["offset"],
    positions: (json["positions"] as Array<any>).map(
      CanonicalPositionReadFromJSON,
    ),
    total: json["total"],
  };
}

export function CanonicalPositionListReadToJSON(
  json: any,
): CanonicalPositionListRead {
  return CanonicalPositionListReadToJSONTyped(json, false);
}

export function CanonicalPositionListReadToJSONTyped(
  value?: CanonicalPositionListRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of_date:
      value["asOfDate"] == null
        ? null
        : (value["asOfDate"] as any).toISOString().substring(0, 10),
    bank_id: value["bankId"],
    limit: value["limit"],
    offset: value["offset"],
    positions: (value["positions"] as Array<any>).map(
      CanonicalPositionReadToJSON,
    ),
    total: value["total"],
  };
}
