/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CanonicalWithdrawalApproveRequest
 */
export interface CanonicalWithdrawalApproveRequest {
  /**
   *
   * @type {string}
   * @memberof CanonicalWithdrawalApproveRequest
   */
  approvedBy: string;
}

/**
 * Check if a given object implements the CanonicalWithdrawalApproveRequest interface.
 */
export function instanceOfCanonicalWithdrawalApproveRequest(
  value: object,
): value is CanonicalWithdrawalApproveRequest {
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  return true;
}

export function CanonicalWithdrawalApproveRequestFromJSON(
  json: any,
): CanonicalWithdrawalApproveRequest {
  return CanonicalWithdrawalApproveRequestFromJSONTyped(json, false);
}

export function CanonicalWithdrawalApproveRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CanonicalWithdrawalApproveRequest {
  if (json == null) {
    return json;
  }
  return {
    approvedBy: json["approved_by"],
  };
}

export function CanonicalWithdrawalApproveRequestToJSON(
  json: any,
): CanonicalWithdrawalApproveRequest {
  return CanonicalWithdrawalApproveRequestToJSONTyped(json, false);
}

export function CanonicalWithdrawalApproveRequestToJSONTyped(
  value?: CanonicalWithdrawalApproveRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approved_by: value["approvedBy"],
  };
}
