/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CapitalComparisonBasisRead
 */
export interface CapitalComparisonBasisRead {
  /**
   *
   * @type {Date}
   * @memberof CapitalComparisonBasisRead
   */
  asOfDate: Date;
  /**
   *
   * @type {number}
   * @memberof CapitalComparisonBasisRead
   */
  forecastHorizon: number;
  /**
   *
   * @type {string}
   * @memberof CapitalComparisonBasisRead
   */
  reportingCurrency: string;
}

/**
 * Check if a given object implements the CapitalComparisonBasisRead interface.
 */
export function instanceOfCapitalComparisonBasisRead(
  value: object,
): value is CapitalComparisonBasisRead {
  if (!("asOfDate" in value) || value["asOfDate"] === undefined) return false;
  if (!("forecastHorizon" in value) || value["forecastHorizon"] === undefined)
    return false;
  if (
    !("reportingCurrency" in value) ||
    value["reportingCurrency"] === undefined
  )
    return false;
  return true;
}

export function CapitalComparisonBasisReadFromJSON(
  json: any,
): CapitalComparisonBasisRead {
  return CapitalComparisonBasisReadFromJSONTyped(json, false);
}

export function CapitalComparisonBasisReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CapitalComparisonBasisRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    asOfDate: new Date(json["as_of_date"]),
    forecastHorizon: json["forecast_horizon"],
    reportingCurrency: json["reporting_currency"],
  };
}

export function CapitalComparisonBasisReadToJSON(
  json: any,
): CapitalComparisonBasisRead {
  return CapitalComparisonBasisReadToJSONTyped(json, false);
}

export function CapitalComparisonBasisReadToJSONTyped(
  value?: CapitalComparisonBasisRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of_date: value["asOfDate"].toISOString().substring(0, 10),
    forecast_horizon: value["forecastHorizon"],
    reporting_currency: value["reportingCurrency"],
  };
}
