/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CaseQueueItemRead } from "./CaseQueueItemRead";
import {
  CaseQueueItemReadFromJSON,
  CaseQueueItemReadFromJSONTyped,
  CaseQueueItemReadToJSON,
  CaseQueueItemReadToJSONTyped,
} from "./CaseQueueItemRead";

/**
 *
 * @export
 * @interface CaseListRead
 */
export interface CaseListRead {
  /**
   *
   * @type {boolean}
   * @memberof CaseListRead
   */
  hasMore: boolean;
  /**
   *
   * @type {Array<CaseQueueItemRead>}
   * @memberof CaseListRead
   */
  items: Array<CaseQueueItemRead>;
  /**
   *
   * @type {number}
   * @memberof CaseListRead
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof CaseListRead
   */
  offset: number;
  /**
   *
   * @type {number}
   * @memberof CaseListRead
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof CaseListRead
   */
  pages: number;
  /**
   *
   * @type {number}
   * @memberof CaseListRead
   */
  total: number;
}

/**
 * Check if a given object implements the CaseListRead interface.
 */
export function instanceOfCaseListRead(value: object): value is CaseListRead {
  if (!("hasMore" in value) || value["hasMore"] === undefined) return false;
  if (!("items" in value) || value["items"] === undefined) return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("offset" in value) || value["offset"] === undefined) return false;
  if (!("page" in value) || value["page"] === undefined) return false;
  if (!("pages" in value) || value["pages"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  return true;
}

export function CaseListReadFromJSON(json: any): CaseListRead {
  return CaseListReadFromJSONTyped(json, false);
}

export function CaseListReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CaseListRead {
  if (json == null) {
    return json;
  }
  return {
    hasMore: json["has_more"],
    items: (json["items"] as Array<any>).map(CaseQueueItemReadFromJSON),
    limit: json["limit"],
    offset: json["offset"],
    page: json["page"],
    pages: json["pages"],
    total: json["total"],
  };
}

export function CaseListReadToJSON(json: any): CaseListRead {
  return CaseListReadToJSONTyped(json, false);
}

export function CaseListReadToJSONTyped(
  value?: CaseListRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    has_more: value["hasMore"],
    items: (value["items"] as Array<any>).map(CaseQueueItemReadToJSON),
    limit: value["limit"],
    offset: value["offset"],
    page: value["page"],
    pages: value["pages"],
    total: value["total"],
  };
}
