/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CaseTaxonomyRead
 */
export interface CaseTaxonomyRead {
  /**
   *
   * @type {Array<string>}
   * @memberof CaseTaxonomyRead
   */
  decisions: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof CaseTaxonomyRead
   */
  riskLevels: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof CaseTaxonomyRead
   */
  sortOptions: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof CaseTaxonomyRead
   */
  statuses: Array<string>;
}

/**
 * Check if a given object implements the CaseTaxonomyRead interface.
 */
export function instanceOfCaseTaxonomyRead(
  value: object,
): value is CaseTaxonomyRead {
  if (!("decisions" in value) || value["decisions"] === undefined) return false;
  if (!("riskLevels" in value) || value["riskLevels"] === undefined)
    return false;
  if (!("sortOptions" in value) || value["sortOptions"] === undefined)
    return false;
  if (!("statuses" in value) || value["statuses"] === undefined) return false;
  return true;
}

export function CaseTaxonomyReadFromJSON(json: any): CaseTaxonomyRead {
  return CaseTaxonomyReadFromJSONTyped(json, false);
}

export function CaseTaxonomyReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CaseTaxonomyRead {
  if (json == null) {
    return json;
  }
  return {
    decisions: json["decisions"],
    riskLevels: json["risk_levels"],
    sortOptions: json["sort_options"],
    statuses: json["statuses"],
  };
}

export function CaseTaxonomyReadToJSON(json: any): CaseTaxonomyRead {
  return CaseTaxonomyReadToJSONTyped(json, false);
}

export function CaseTaxonomyReadToJSONTyped(
  value?: CaseTaxonomyRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    decisions: value["decisions"],
    risk_levels: value["riskLevels"],
    sort_options: value["sortOptions"],
    statuses: value["statuses"],
  };
}
