/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CaseDecision } from "./CaseDecision";
import {
  CaseDecisionFromJSON,
  CaseDecisionFromJSONTyped,
  CaseDecisionToJSON,
  CaseDecisionToJSONTyped,
} from "./CaseDecision";

/**
 *
 * @export
 * @interface CaseDecisionRead
 */
export interface CaseDecisionRead {
  /**
   *
   * @type {string}
   * @memberof CaseDecisionRead
   */
  caseId: string;
  /**
   *
   * @type {Date}
   * @memberof CaseDecisionRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof CaseDecisionRead
   */
  decidedBy: string | null;
  /**
   *
   * @type {CaseDecision}
   * @memberof CaseDecisionRead
   */
  decision: CaseDecision;
  /**
   *
   * @type {string}
   * @memberof CaseDecisionRead
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CaseDecisionRead
   */
  organizationId: string;
  /**
   *
   * @type {CaseDecision}
   * @memberof CaseDecisionRead
   */
  previousDecision: CaseDecision | null;
  /**
   *
   * @type {string}
   * @memberof CaseDecisionRead
   */
  reason: string | null;
}

/**
 * Check if a given object implements the CaseDecisionRead interface.
 */
export function instanceOfCaseDecisionRead(
  value: object,
): value is CaseDecisionRead {
  if (!("caseId" in value) || value["caseId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("decidedBy" in value) || value["decidedBy"] === undefined) return false;
  if (!("decision" in value) || value["decision"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined)
    return false;
  if (!("previousDecision" in value) || value["previousDecision"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function CaseDecisionReadFromJSON(json: any): CaseDecisionRead {
  return CaseDecisionReadFromJSONTyped(json, false);
}

export function CaseDecisionReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CaseDecisionRead {
  if (json == null) {
    return json;
  }
  return {
    caseId: json["case_id"],
    createdAt: new Date(json["created_at"]),
    decidedBy: json["decided_by"],
    decision: CaseDecisionFromJSON(json["decision"]),
    id: json["id"],
    organizationId: json["organization_id"],
    previousDecision: CaseDecisionFromJSON(json["previous_decision"]),
    reason: json["reason"],
  };
}

export function CaseDecisionReadToJSON(json: any): CaseDecisionRead {
  return CaseDecisionReadToJSONTyped(json, false);
}

export function CaseDecisionReadToJSONTyped(
  value?: CaseDecisionRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    case_id: value["caseId"],
    created_at: value["createdAt"].toISOString(),
    decided_by: value["decidedBy"],
    decision: CaseDecisionToJSON(value["decision"]),
    id: value["id"],
    organization_id: value["organizationId"],
    previous_decision: CaseDecisionToJSON(value["previousDecision"]),
    reason: value["reason"],
  };
}
