/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CashflowForecastPointRead
 */
export interface CashflowForecastPointRead {
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  behavioralNetFlow: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  contractualNetFlow: number;
  /**
   *
   * @type {Date}
   * @memberof CashflowForecastPointRead
   */
  date: Date;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  day: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  lower: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  netFlow: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  p5: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  p50: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  p95: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  scenarioAdjustment: number;
  /**
   *
   * @type {number}
   * @memberof CashflowForecastPointRead
   */
  upper: number;
}

/**
 * Check if a given object implements the CashflowForecastPointRead interface.
 */
export function instanceOfCashflowForecastPointRead(
  value: object,
): value is CashflowForecastPointRead {
  if (
    !("behavioralNetFlow" in value) ||
    value["behavioralNetFlow"] === undefined
  )
    return false;
  if (
    !("contractualNetFlow" in value) ||
    value["contractualNetFlow"] === undefined
  )
    return false;
  if (!("date" in value) || value["date"] === undefined) return false;
  if (!("day" in value) || value["day"] === undefined) return false;
  if (!("lower" in value) || value["lower"] === undefined) return false;
  if (!("netFlow" in value) || value["netFlow"] === undefined) return false;
  if (!("p5" in value) || value["p5"] === undefined) return false;
  if (!("p50" in value) || value["p50"] === undefined) return false;
  if (!("p95" in value) || value["p95"] === undefined) return false;
  if (
    !("scenarioAdjustment" in value) ||
    value["scenarioAdjustment"] === undefined
  )
    return false;
  if (!("upper" in value) || value["upper"] === undefined) return false;
  return true;
}

export function CashflowForecastPointReadFromJSON(
  json: any,
): CashflowForecastPointRead {
  return CashflowForecastPointReadFromJSONTyped(json, false);
}

export function CashflowForecastPointReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CashflowForecastPointRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    behavioralNetFlow: json["behavioralNetFlow"],
    contractualNetFlow: json["contractualNetFlow"],
    date: new Date(json["date"]),
    day: json["day"],
    lower: json["lower"],
    netFlow: json["netFlow"],
    p5: json["p5"],
    p50: json["p50"],
    p95: json["p95"],
    scenarioAdjustment: json["scenarioAdjustment"],
    upper: json["upper"],
  };
}

export function CashflowForecastPointReadToJSON(
  json: any,
): CashflowForecastPointRead {
  return CashflowForecastPointReadToJSONTyped(json, false);
}

export function CashflowForecastPointReadToJSONTyped(
  value?: CashflowForecastPointRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    behavioralNetFlow: value["behavioralNetFlow"],
    contractualNetFlow: value["contractualNetFlow"],
    date: value["date"].toISOString().substring(0, 10),
    day: value["day"],
    lower: value["lower"],
    netFlow: value["netFlow"],
    p5: value["p5"],
    p50: value["p50"],
    p95: value["p95"],
    scenarioAdjustment: value["scenarioAdjustment"],
    upper: value["upper"],
  };
}
