/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * One calendar month × currency cell of the contractual flow window.
 *
 * ``month`` is the first day of the calendar month. Every month of the
 * requested window appears for each currency that has at least one flow
 * inside the window (zero months included, so charts and tables stay
 * contiguous); currencies with no flows in the window are omitted entirely.
 * Amounts are in the position's own currency — never converted.
 * @export
 * @interface CashflowWindowMonthRead
 */
export interface CashflowWindowMonthRead {
  /**
   *
   * @type {string}
   * @memberof CashflowWindowMonthRead
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof CashflowWindowMonthRead
   */
  inflows: string;
  /**
   *
   * @type {Date}
   * @memberof CashflowWindowMonthRead
   */
  month: Date;
  /**
   *
   * @type {string}
   * @memberof CashflowWindowMonthRead
   */
  net: string;
  /**
   *
   * @type {string}
   * @memberof CashflowWindowMonthRead
   */
  outflows: string;
}

/**
 * Check if a given object implements the CashflowWindowMonthRead interface.
 */
export function instanceOfCashflowWindowMonthRead(
  value: object,
): value is CashflowWindowMonthRead {
  if (!("currency" in value) || value["currency"] === undefined) return false;
  if (!("inflows" in value) || value["inflows"] === undefined) return false;
  if (!("month" in value) || value["month"] === undefined) return false;
  if (!("net" in value) || value["net"] === undefined) return false;
  if (!("outflows" in value) || value["outflows"] === undefined) return false;
  return true;
}

export function CashflowWindowMonthReadFromJSON(
  json: any,
): CashflowWindowMonthRead {
  return CashflowWindowMonthReadFromJSONTyped(json, false);
}

export function CashflowWindowMonthReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CashflowWindowMonthRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    currency: json["currency"],
    inflows: json["inflows"],
    month: new Date(json["month"]),
    net: json["net"],
    outflows: json["outflows"],
  };
}

export function CashflowWindowMonthReadToJSON(
  json: any,
): CashflowWindowMonthRead {
  return CashflowWindowMonthReadToJSONTyped(json, false);
}

export function CashflowWindowMonthReadToJSONTyped(
  value?: CashflowWindowMonthRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currency: value["currency"],
    inflows: value["inflows"],
    month: value["month"].toISOString().substring(0, 10),
    net: value["net"],
    outflows: value["outflows"],
  };
}
