/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CcfPct
 */
export type CcfPct = string | null;

/**
 * Check if a given object implements the CcfPct interface.
 */
export function instanceOfCcfPct(value: unknown): value is CcfPct {
  return typeof value === "string" || value === null;
}

export function CcfPctFromJSON(json: any): CcfPct {
  return CcfPctFromJSONTyped(json, false);
}

export function CcfPctFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CcfPct {
  return json;
}

export function CcfPctToJSON(json: any): CcfPct {
  return CcfPctToJSONTyped(json, false);
}

export function CcfPctToJSONTyped(
  value?: CcfPct | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
