/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApprovalExpiresAt } from "./ApprovalExpiresAt";
import {
  ApprovalExpiresAtFromJSON,
  ApprovalExpiresAtFromJSONTyped,
  ApprovalExpiresAtToJSON,
  ApprovalExpiresAtToJSONTyped,
} from "./ApprovalExpiresAt";
import type { CfpStatus } from "./CfpStatus";
import {
  CfpStatusFromJSON,
  CfpStatusFromJSONTyped,
  CfpStatusToJSON,
  CfpStatusToJSONTyped,
} from "./CfpStatus";
import type { ApprovalReference1 } from "./ApprovalReference1";
import {
  ApprovalReference1FromJSON,
  ApprovalReference1FromJSONTyped,
  ApprovalReference1ToJSON,
  ApprovalReference1ToJSONTyped,
} from "./ApprovalReference1";
import type { ApprovalTimestamp } from "./ApprovalTimestamp";
import {
  ApprovalTimestampFromJSON,
  ApprovalTimestampFromJSONTyped,
  ApprovalTimestampToJSON,
  ApprovalTimestampToJSONTyped,
} from "./ApprovalTimestamp";
import type { ApprovedByUserId } from "./ApprovedByUserId";
import {
  ApprovedByUserIdFromJSON,
  ApprovedByUserIdFromJSONTyped,
  ApprovedByUserIdToJSON,
  ApprovedByUserIdToJSONTyped,
} from "./ApprovedByUserId";
import type { CfpContent } from "./CfpContent";
import {
  CfpContentFromJSON,
  CfpContentFromJSONTyped,
  CfpContentToJSON,
  CfpContentToJSONTyped,
} from "./CfpContent";
import type { PreparedBy } from "./PreparedBy";
import {
  PreparedByFromJSON,
  PreparedByFromJSONTyped,
  PreparedByToJSON,
  PreparedByToJSONTyped,
} from "./PreparedBy";

/**
 *
 * @export
 * @interface CfpRead
 */
export interface CfpRead {
  /**
   *
   * @type {boolean}
   * @memberof CfpRead
   */
  active?: boolean;
  /**
   *
   * @type {ApprovalExpiresAt}
   * @memberof CfpRead
   */
  approvalExpiresAt?: ApprovalExpiresAt;
  /**
   *
   * @type {boolean}
   * @memberof CfpRead
   */
  approvalOverdue?: boolean;
  /**
   *
   * @type {ApprovalReference1}
   * @memberof CfpRead
   */
  approvalReference?: ApprovalReference1;
  /**
   *
   * @type {ApprovalTimestamp}
   * @memberof CfpRead
   */
  approvalTimestamp?: ApprovalTimestamp;
  /**
   *
   * @type {ApprovedByUserId}
   * @memberof CfpRead
   */
  approvedByUserId?: ApprovedByUserId;
  /**
   *
   * @type {string}
   * @memberof CfpRead
   */
  bankId: string;
  /**
   *
   * @type {CfpContent}
   * @memberof CfpRead
   */
  content: CfpContent;
  /**
   *
   * @type {Date}
   * @memberof CfpRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof CfpRead
   */
  id: string;
  /**
   *
   * @type {PreparedBy}
   * @memberof CfpRead
   */
  preparedBy?: PreparedBy;
  /**
   *
   * @type {CfpStatus}
   * @memberof CfpRead
   */
  status: CfpStatus;
  /**
   *
   * @type {Date}
   * @memberof CfpRead
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof CfpRead
   */
  version: number;
}

/**
 * Check if a given object implements the CfpRead interface.
 */
export function instanceOfCfpRead(value: object): value is CfpRead {
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("content" in value) || value["content"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  return true;
}

export function CfpReadFromJSON(json: any): CfpRead {
  return CfpReadFromJSONTyped(json, false);
}

export function CfpReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CfpRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    active: json["active"] == null ? undefined : json["active"],
    approvalExpiresAt:
      json["approval_expires_at"] == null
        ? undefined
        : ApprovalExpiresAtFromJSON(json["approval_expires_at"]),
    approvalOverdue:
      json["approval_overdue"] == null ? undefined : json["approval_overdue"],
    approvalReference:
      json["approval_reference"] == null
        ? undefined
        : ApprovalReference1FromJSON(json["approval_reference"]),
    approvalTimestamp:
      json["approval_timestamp"] == null
        ? undefined
        : ApprovalTimestampFromJSON(json["approval_timestamp"]),
    approvedByUserId:
      json["approved_by_user_id"] == null
        ? undefined
        : ApprovedByUserIdFromJSON(json["approved_by_user_id"]),
    bankId: json["bank_id"],
    content: CfpContentFromJSON(json["content"]),
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    preparedBy:
      json["prepared_by"] == null
        ? undefined
        : PreparedByFromJSON(json["prepared_by"]),
    status: CfpStatusFromJSON(json["status"]),
    updatedAt: new Date(json["updated_at"]),
    version: json["version"],
  };
}

export function CfpReadToJSON(json: any): CfpRead {
  return CfpReadToJSONTyped(json, false);
}

export function CfpReadToJSONTyped(
  value?: CfpRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    active: value["active"],
    approval_expires_at: ApprovalExpiresAtToJSON(value["approvalExpiresAt"]),
    approval_overdue: value["approvalOverdue"],
    approval_reference: ApprovalReference1ToJSON(value["approvalReference"]),
    approval_timestamp: ApprovalTimestampToJSON(value["approvalTimestamp"]),
    approved_by_user_id: ApprovedByUserIdToJSON(value["approvedByUserId"]),
    bank_id: value["bankId"],
    content: CfpContentToJSON(value["content"]),
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    prepared_by: PreparedByToJSON(value["preparedBy"]),
    status: CfpStatusToJSON(value["status"]),
    updated_at: value["updatedAt"].toISOString(),
    version: value["version"],
  };
}
