/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CompareTo
 */
export type CompareTo = string | null;

/**
 * Check if a given object implements the CompareTo interface.
 */
export function instanceOfCompareTo(value: unknown): value is CompareTo {
  return typeof value === "string" || value === null;
}

export function CompareToFromJSON(json: any): CompareTo {
  return CompareToFromJSONTyped(json, false);
}

export function CompareToFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CompareTo {
  return json;
}

export function CompareToToJSON(json: any): CompareTo {
  return CompareToToJSONTyped(json, false);
}

export function CompareToToJSONTyped(
  value?: CompareTo | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
