/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { BucketKey } from "./BucketKey";
import {
  BucketKeyFromJSON,
  BucketKeyFromJSONTyped,
  BucketKeyToJSON,
  BucketKeyToJSONTyped,
} from "./BucketKey";
import type { Value } from "./Value";
import {
  ValueFromJSON,
  ValueFromJSONTyped,
  ValueToJSON,
  ValueToJSONTyped,
} from "./Value";

/**
 *
 * @export
 * @interface ConcentrationLimitEntry
 */
export interface ConcentrationLimitEntry {
  /**
   *
   * @type {BucketKey}
   * @memberof ConcentrationLimitEntry
   */
  bucketKey?: BucketKey;
  /**
   *
   * @type {string}
   * @memberof ConcentrationLimitEntry
   */
  dimension: string;
  /**
   *
   * @type {string}
   * @memberof ConcentrationLimitEntry
   */
  limitKind: string;
  /**
   *
   * @type {Value}
   * @memberof ConcentrationLimitEntry
   */
  value: Value;
}

/**
 * Check if a given object implements the ConcentrationLimitEntry interface.
 */
export function instanceOfConcentrationLimitEntry(
  value: object,
): value is ConcentrationLimitEntry {
  if (!("dimension" in value) || value["dimension"] === undefined) return false;
  if (!("limitKind" in value) || value["limitKind"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function ConcentrationLimitEntryFromJSON(
  json: any,
): ConcentrationLimitEntry {
  return ConcentrationLimitEntryFromJSONTyped(json, false);
}

export function ConcentrationLimitEntryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConcentrationLimitEntry {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    bucketKey:
      json["bucket_key"] == null
        ? undefined
        : BucketKeyFromJSON(json["bucket_key"]),
    dimension: json["dimension"],
    limitKind: json["limit_kind"],
    value: ValueFromJSON(json["value"]),
  };
}

export function ConcentrationLimitEntryToJSON(
  json: any,
): ConcentrationLimitEntry {
  return ConcentrationLimitEntryToJSONTyped(json, false);
}

export function ConcentrationLimitEntryToJSONTyped(
  value?: ConcentrationLimitEntry | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    bucket_key: BucketKeyToJSON(value["bucketKey"]),
    dimension: value["dimension"],
    limit_kind: value["limitKind"],
    value: ValueToJSON(value["value"]),
  };
}
