/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConnectionOptionsUpdate
 */
export type ConnectionOptionsUpdate = { [key: string]: any } | null;

/**
 * Check if a given object implements the ConnectionOptionsUpdate interface.
 */
export function instanceOfConnectionOptionsUpdate(
  value: unknown,
): value is ConnectionOptionsUpdate {
  return (
    (typeof value === "object" && value !== null && !Array.isArray(value)) ||
    value === null
  );
}

export function ConnectionOptionsUpdateFromJSON(
  json: any,
): ConnectionOptionsUpdate {
  return ConnectionOptionsUpdateFromJSONTyped(json, false);
}

export function ConnectionOptionsUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConnectionOptionsUpdate {
  return json;
}

export function ConnectionOptionsUpdateToJSON(
  json: any,
): ConnectionOptionsUpdate {
  return ConnectionOptionsUpdateToJSONTyped(json, false);
}

export function ConnectionOptionsUpdateToJSONTyped(
  value?: ConnectionOptionsUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
