/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ConnectionLastValidatedAt
 */
export type ConnectionLastValidatedAt = string | null;

/**
 * Check if a given object implements the ConnectionLastValidatedAt interface.
 */
export function instanceOfConnectionLastValidatedAt(
  value: unknown,
): value is ConnectionLastValidatedAt {
  return typeof value === "string" || value === null;
}

export function ConnectionLastValidatedAtFromJSON(
  json: any,
): ConnectionLastValidatedAt {
  return ConnectionLastValidatedAtFromJSONTyped(json, false);
}

export function ConnectionLastValidatedAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConnectionLastValidatedAt {
  return json;
}

export function ConnectionLastValidatedAtToJSON(
  json: any,
): ConnectionLastValidatedAt {
  return ConnectionLastValidatedAtToJSONTyped(json, false);
}

export function ConnectionLastValidatedAtToJSONTyped(
  value?: ConnectionLastValidatedAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
