/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreatedAt
 */
export type CreatedAt = string | null;

/**
 * Check if a given object implements the CreatedAt interface.
 */
export function instanceOfCreatedAt(value: unknown): value is CreatedAt {
  return typeof value === "string" || value === null;
}

export function CreatedAtFromJSON(json: any): CreatedAt {
  return CreatedAtFromJSONTyped(json, false);
}

export function CreatedAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreatedAt {
  return json;
}

export function CreatedAtToJSON(json: any): CreatedAt {
  return CreatedAtToJSONTyped(json, false);
}

export function CreatedAtToJSONTyped(
  value?: CreatedAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
