/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SeverityFactorsAnyOfValue } from "./SeverityFactorsAnyOfValue";
import {
  SeverityFactorsAnyOfValueFromJSON,
  SeverityFactorsAnyOfValueFromJSONTyped,
  SeverityFactorsAnyOfValueToJSON,
  SeverityFactorsAnyOfValueToJSONTyped,
} from "./SeverityFactorsAnyOfValue";

/**
 *
 * @export
 * @interface CreditThresholdUpdate
 */
export interface CreditThresholdUpdate {
  /**
   *
   * @type {string}
   * @memberof CreditThresholdUpdate
   */
  approvedBy: string;
  /**
   *
   * @type {Date}
   * @memberof CreditThresholdUpdate
   */
  effectiveFrom: Date;
  /**
   *
   * @type {string}
   * @memberof CreditThresholdUpdate
   */
  reason: string;
  /**
   *
   * @type {{ [key: string]: SeverityFactorsAnyOfValue; }}
   * @memberof CreditThresholdUpdate
   */
  thresholds: { [key: string]: SeverityFactorsAnyOfValue };
}

/**
 * Check if a given object implements the CreditThresholdUpdate interface.
 */
export function instanceOfCreditThresholdUpdate(
  value: object,
): value is CreditThresholdUpdate {
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  if (!("effectiveFrom" in value) || value["effectiveFrom"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  if (!("thresholds" in value) || value["thresholds"] === undefined)
    return false;
  return true;
}

export function CreditThresholdUpdateFromJSON(
  json: any,
): CreditThresholdUpdate {
  return CreditThresholdUpdateFromJSONTyped(json, false);
}

export function CreditThresholdUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreditThresholdUpdate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    approvedBy: json["approved_by"],
    effectiveFrom: new Date(json["effective_from"]),
    reason: json["reason"],
    thresholds: mapValues(
      json["thresholds"],
      SeverityFactorsAnyOfValueFromJSON,
    ),
  };
}

export function CreditThresholdUpdateToJSON(json: any): CreditThresholdUpdate {
  return CreditThresholdUpdateToJSONTyped(json, false);
}

export function CreditThresholdUpdateToJSONTyped(
  value?: CreditThresholdUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approved_by: value["approvedBy"],
    effective_from: value["effectiveFrom"].toISOString().substring(0, 10),
    reason: value["reason"],
    thresholds: mapValues(value["thresholds"], SeverityFactorsAnyOfValueToJSON),
  };
}
