/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DayOfMonth
 */
export type DayOfMonth = number | null;

/**
 * Check if a given object implements the DayOfMonth interface.
 */
export function instanceOfDayOfMonth(value: unknown): value is DayOfMonth {
  return typeof value === "number" || value === null;
}

export function DayOfMonthFromJSON(json: any): DayOfMonth {
  return DayOfMonthFromJSONTyped(json, false);
}

export function DayOfMonthFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DayOfMonth {
  return json;
}

export function DayOfMonthToJSON(json: any): DayOfMonth {
  return DayOfMonthToJSONTyped(json, false);
}

export function DayOfMonthToJSONTyped(
  value?: DayOfMonth | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
