/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Regime } from "./Regime";
import {
  RegimeFromJSON,
  RegimeFromJSONTyped,
  RegimeToJSON,
  RegimeToJSONTyped,
} from "./Regime";
import type { CalculationVersion } from "./CalculationVersion";
import {
  CalculationVersionFromJSON,
  CalculationVersionFromJSONTyped,
  CalculationVersionToJSON,
  CalculationVersionToJSONTyped,
} from "./CalculationVersion";
import type { Divergence } from "./Divergence";
import {
  DivergenceFromJSON,
  DivergenceFromJSONTyped,
  DivergenceToJSON,
  DivergenceToJSONTyped,
} from "./Divergence";
import type { AuthorityReference } from "./AuthorityReference";
import {
  AuthorityReferenceFromJSON,
  AuthorityReferenceFromJSONTyped,
  AuthorityReferenceToJSON,
  AuthorityReferenceToJSONTyped,
} from "./AuthorityReference";
import type { ExpectedTolerance } from "./ExpectedTolerance";
import {
  ExpectedToleranceFromJSON,
  ExpectedToleranceFromJSONTyped,
  ExpectedToleranceToJSON,
  ExpectedToleranceToJSONTyped,
} from "./ExpectedTolerance";
import type { CalculationEngine } from "./CalculationEngine";
import {
  CalculationEngineFromJSON,
  CalculationEngineFromJSONTyped,
  CalculationEngineToJSON,
  CalculationEngineToJSONTyped,
} from "./CalculationEngine";
import type { AdvisoryDesignation } from "./AdvisoryDesignation";
import {
  AdvisoryDesignationFromJSON,
  AdvisoryDesignationFromJSONTyped,
  AdvisoryDesignationToJSON,
  AdvisoryDesignationToJSONTyped,
} from "./AdvisoryDesignation";

/**
 * One "which figure does this return mean?" disclosure, typed.
 *
 * CF-1's answer to the audit's LCR question: BSD3's LCR and LMT Table 11's LCR
 * are different methodologies by design, and forcing them to agree would break
 * a correct engine. The registry has recorded that since ARCH-4 and the
 * generator has written it into ``snapshot["provenance"]`` — where, until
 * 2026-08-22, nothing read it (audit D-20). ``snapshot`` is typed
 * ``dict[str, Any]``, so an untyped blob is not a contract; this is.
 * @export
 * @interface DeclaredMethodologyRead
 */
export interface DeclaredMethodologyRead {
  /**
   *
   * @type {AdvisoryDesignation}
   * @memberof DeclaredMethodologyRead
   */
  advisoryDesignation?: AdvisoryDesignation;
  /**
   *
   * @type {Array<string>}
   * @memberof DeclaredMethodologyRead
   */
  alternateMethodologies?: Array<string>;
  /**
   *
   * @type {AuthorityReference}
   * @memberof DeclaredMethodologyRead
   */
  authorityReference?: AuthorityReference;
  /**
   *
   * @type {CalculationEngine}
   * @memberof DeclaredMethodologyRead
   */
  calculationEngine?: CalculationEngine;
  /**
   *
   * @type {CalculationVersion}
   * @memberof DeclaredMethodologyRead
   */
  calculationVersion?: CalculationVersion;
  /**
   *
   * @type {Divergence}
   * @memberof DeclaredMethodologyRead
   */
  divergence?: Divergence;
  /**
   *
   * @type {ExpectedTolerance}
   * @memberof DeclaredMethodologyRead
   */
  expectedTolerance?: ExpectedTolerance;
  /**
   *
   * @type {string}
   * @memberof DeclaredMethodologyRead
   */
  methodologyId: string;
  /**
   *
   * @type {string}
   * @memberof DeclaredMethodologyRead
   */
  metricId: string;
  /**
   *
   * @type {Regime}
   * @memberof DeclaredMethodologyRead
   */
  regime?: Regime;
  /**
   *
   * @type {string}
   * @memberof DeclaredMethodologyRead
   */
  registryStatus: string;
}

/**
 * Check if a given object implements the DeclaredMethodologyRead interface.
 */
export function instanceOfDeclaredMethodologyRead(
  value: object,
): value is DeclaredMethodologyRead {
  if (!("methodologyId" in value) || value["methodologyId"] === undefined)
    return false;
  if (!("metricId" in value) || value["metricId"] === undefined) return false;
  if (!("registryStatus" in value) || value["registryStatus"] === undefined)
    return false;
  return true;
}

export function DeclaredMethodologyReadFromJSON(
  json: any,
): DeclaredMethodologyRead {
  return DeclaredMethodologyReadFromJSONTyped(json, false);
}

export function DeclaredMethodologyReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeclaredMethodologyRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    advisoryDesignation:
      json["advisory_designation"] == null
        ? undefined
        : AdvisoryDesignationFromJSON(json["advisory_designation"]),
    alternateMethodologies:
      json["alternate_methodologies"] == null
        ? undefined
        : json["alternate_methodologies"],
    authorityReference:
      json["authority_reference"] == null
        ? undefined
        : AuthorityReferenceFromJSON(json["authority_reference"]),
    calculationEngine:
      json["calculation_engine"] == null
        ? undefined
        : CalculationEngineFromJSON(json["calculation_engine"]),
    calculationVersion:
      json["calculation_version"] == null
        ? undefined
        : CalculationVersionFromJSON(json["calculation_version"]),
    divergence:
      json["divergence"] == null
        ? undefined
        : DivergenceFromJSON(json["divergence"]),
    expectedTolerance:
      json["expected_tolerance"] == null
        ? undefined
        : ExpectedToleranceFromJSON(json["expected_tolerance"]),
    methodologyId: json["methodology_id"],
    metricId: json["metric_id"],
    regime: json["regime"] == null ? undefined : RegimeFromJSON(json["regime"]),
    registryStatus: json["registry_status"],
  };
}

export function DeclaredMethodologyReadToJSON(
  json: any,
): DeclaredMethodologyRead {
  return DeclaredMethodologyReadToJSONTyped(json, false);
}

export function DeclaredMethodologyReadToJSONTyped(
  value?: DeclaredMethodologyRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    advisory_designation: AdvisoryDesignationToJSON(
      value["advisoryDesignation"],
    ),
    alternate_methodologies: value["alternateMethodologies"],
    authority_reference: AuthorityReferenceToJSON(value["authorityReference"]),
    calculation_engine: CalculationEngineToJSON(value["calculationEngine"]),
    calculation_version: CalculationVersionToJSON(value["calculationVersion"]),
    divergence: DivergenceToJSON(value["divergence"]),
    expected_tolerance: ExpectedToleranceToJSON(value["expectedTolerance"]),
    methodology_id: value["methodologyId"],
    metric_id: value["metricId"],
    regime: RegimeToJSON(value["regime"]),
    registry_status: value["registryStatus"],
  };
}
