/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Description2
 */
export type Description2 = string | null;

/**
 * Check if a given object implements the Description2 interface.
 */
export function instanceOfDescription2(value: unknown): value is Description2 {
  return typeof value === "string" || value === null;
}

export function Description2FromJSON(json: any): Description2 {
  return Description2FromJSONTyped(json, false);
}

export function Description2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Description2 {
  return json;
}

export function Description2ToJSON(json: any): Description2 {
  return Description2ToJSONTyped(json, false);
}

export function Description2ToJSONTyped(
  value?: Description2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
