/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Details
 */
export type Details = { [key: string]: any } | null;

/**
 * Check if a given object implements the Details interface.
 */
export function instanceOfDetails(value: unknown): value is Details {
  return (
    (typeof value === "object" && value !== null && !Array.isArray(value)) ||
    value === null
  );
}

export function DetailsFromJSON(json: any): Details {
  return DetailsFromJSONTyped(json, false);
}

export function DetailsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Details {
  return json;
}

export function DetailsToJSON(json: any): Details {
  return DetailsToJSONTyped(json, false);
}

export function DetailsToJSONTyped(
  value?: Details | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
