/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DiscoveredColumn
 */
export interface DiscoveredColumn {
  /**
   *
   * @type {string}
   * @memberof DiscoveredColumn
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof DiscoveredColumn
   */
  sampleValues?: Array<string>;
}

/**
 * Check if a given object implements the DiscoveredColumn interface.
 */
export function instanceOfDiscoveredColumn(
  value: object,
): value is DiscoveredColumn {
  if (!("name" in value) || value["name"] === undefined) return false;
  return true;
}

export function DiscoveredColumnFromJSON(json: any): DiscoveredColumn {
  return DiscoveredColumnFromJSONTyped(json, false);
}

export function DiscoveredColumnFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DiscoveredColumn {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    name: json["name"],
    sampleValues:
      json["sample_values"] == null ? undefined : json["sample_values"],
  };
}

export function DiscoveredColumnToJSON(json: any): DiscoveredColumn {
  return DiscoveredColumnToJSONTyped(json, false);
}

export function DiscoveredColumnToJSONTyped(
  value?: DiscoveredColumn | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value["name"],
    sample_values: value["sampleValues"],
  };
}
