/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DisplayName2
 */
export type DisplayName2 = string | null;

/**
 * Check if a given object implements the DisplayName2 interface.
 */
export function instanceOfDisplayName2(value: unknown): value is DisplayName2 {
  return typeof value === "string" || value === null;
}

export function DisplayName2FromJSON(json: any): DisplayName2 {
  return DisplayName2FromJSONTyped(json, false);
}

export function DisplayName2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DisplayName2 {
  return json;
}

export function DisplayName2ToJSON(json: any): DisplayName2 {
  return DisplayName2ToJSONTyped(json, false);
}

export function DisplayName2ToJSONTyped(
  value?: DisplayName2 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
