/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DividendPayoutPct
 */
export type DividendPayoutPct = number | string | null;

/**
 * Check if a given object implements the DividendPayoutPct interface.
 */
export function instanceOfDividendPayoutPct(
  value: unknown,
): value is DividendPayoutPct {
  return (
    typeof value === "number" || typeof value === "string" || value === null
  );
}

export function DividendPayoutPctFromJSON(json: any): DividendPayoutPct {
  return DividendPayoutPctFromJSONTyped(json, false);
}

export function DividendPayoutPctFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DividendPayoutPct {
  return json;
}

export function DividendPayoutPctToJSON(json: any): DividendPayoutPct {
  return DividendPayoutPctToJSONTyped(json, false);
}

export function DividendPayoutPctToJSONTyped(
  value?: DividendPayoutPct | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
