/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EclAssumptionEntry } from "./EclAssumptionEntry";
import {
  EclAssumptionEntryFromJSON,
  EclAssumptionEntryFromJSONTyped,
  EclAssumptionEntryToJSON,
  EclAssumptionEntryToJSONTyped,
} from "./EclAssumptionEntry";
import type { Notes2 } from "./Notes2";
import {
  Notes2FromJSON,
  Notes2FromJSONTyped,
  Notes2ToJSON,
  Notes2ToJSONTyped,
} from "./Notes2";

/**
 *
 * @export
 * @interface EclAssumptionUpdate
 */
export interface EclAssumptionUpdate {
  /**
   *
   * @type {string}
   * @memberof EclAssumptionUpdate
   */
  approvedBy: string;
  /**
   *
   * @type {Array<EclAssumptionEntry>}
   * @memberof EclAssumptionUpdate
   */
  assumptions: Array<EclAssumptionEntry>;
  /**
   *
   * @type {Date}
   * @memberof EclAssumptionUpdate
   */
  effectiveFrom: Date;
  /**
   *
   * @type {Notes2}
   * @memberof EclAssumptionUpdate
   */
  notes?: Notes2;
  /**
   *
   * @type {string}
   * @memberof EclAssumptionUpdate
   */
  reason: string;
}

/**
 * Check if a given object implements the EclAssumptionUpdate interface.
 */
export function instanceOfEclAssumptionUpdate(
  value: object,
): value is EclAssumptionUpdate {
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  if (!("assumptions" in value) || value["assumptions"] === undefined)
    return false;
  if (!("effectiveFrom" in value) || value["effectiveFrom"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function EclAssumptionUpdateFromJSON(json: any): EclAssumptionUpdate {
  return EclAssumptionUpdateFromJSONTyped(json, false);
}

export function EclAssumptionUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EclAssumptionUpdate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    approvedBy: json["approved_by"],
    assumptions: (json["assumptions"] as Array<any>).map(
      EclAssumptionEntryFromJSON,
    ),
    effectiveFrom: new Date(json["effective_from"]),
    notes: json["notes"] == null ? undefined : Notes2FromJSON(json["notes"]),
    reason: json["reason"],
  };
}

export function EclAssumptionUpdateToJSON(json: any): EclAssumptionUpdate {
  return EclAssumptionUpdateToJSONTyped(json, false);
}

export function EclAssumptionUpdateToJSONTyped(
  value?: EclAssumptionUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approved_by: value["approvedBy"],
    assumptions: (value["assumptions"] as Array<any>).map(
      EclAssumptionEntryToJSON,
    ),
    effective_from: value["effectiveFrom"].toISOString().substring(0, 10),
    notes: Notes2ToJSON(value["notes"]),
    reason: value["reason"],
  };
}
