/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EndDate
 */
export type EndDate = string | null;

/**
 * Check if a given object implements the EndDate interface.
 */
export function instanceOfEndDate(value: unknown): value is EndDate {
  return typeof value === "string" || value === null;
}

export function EndDateFromJSON(json: any): EndDate {
  return EndDateFromJSONTyped(json, false);
}

export function EndDateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EndDate {
  return json;
}

export function EndDateToJSON(json: any): EndDate {
  return EndDateToJSONTyped(json, false);
}

export function EndDateToJSONTyped(
  value?: EndDate | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
