/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EventSubtype
 */
export type EventSubtype = string | null;

/**
 * Check if a given object implements the EventSubtype interface.
 */
export function instanceOfEventSubtype(value: unknown): value is EventSubtype {
  return typeof value === "string" || value === null;
}

export function EventSubtypeFromJSON(json: any): EventSubtype {
  return EventSubtypeFromJSONTyped(json, false);
}

export function EventSubtypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EventSubtype {
  return json;
}

export function EventSubtypeToJSON(json: any): EventSubtype {
  return EventSubtypeToJSONTyped(json, false);
}

export function EventSubtypeToJSONTyped(
  value?: EventSubtype | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
