/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExplanationBy
 */
export type ExplanationBy = string | null;

/**
 * Check if a given object implements the ExplanationBy interface.
 */
export function instanceOfExplanationBy(
  value: unknown,
): value is ExplanationBy {
  return typeof value === "string" || value === null;
}

export function ExplanationByFromJSON(json: any): ExplanationBy {
  return ExplanationByFromJSONTyped(json, false);
}

export function ExplanationByFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExplanationBy {
  return json;
}

export function ExplanationByToJSON(json: any): ExplanationBy {
  return ExplanationByToJSONTyped(json, false);
}

export function ExplanationByToJSONTyped(
  value?: ExplanationBy | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
