/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Explanation1
 */
export type Explanation1 = string | null;

/**
 * Check if a given object implements the Explanation1 interface.
 */
export function instanceOfExplanation1(value: unknown): value is Explanation1 {
  return typeof value === "string" || value === null;
}

export function Explanation1FromJSON(json: any): Explanation1 {
  return Explanation1FromJSONTyped(json, false);
}

export function Explanation1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Explanation1 {
  return json;
}

export function Explanation1ToJSON(json: any): Explanation1 {
  return Explanation1ToJSONTyped(json, false);
}

export function Explanation1ToJSONTyped(
  value?: Explanation1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
