/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Reason } from "./Reason";
import {
  ReasonFromJSON,
  ReasonFromJSONTyped,
  ReasonToJSON,
  ReasonToJSONTyped,
} from "./Reason";

/**
 *
 * @export
 * @interface FigureRefusalRead
 */
export interface FigureRefusalRead {
  /**
   *
   * @type {Reason}
   * @memberof FigureRefusalRead
   */
  reason?: Reason;
  /**
   *
   * @type {string}
   * @memberof FigureRefusalRead
   */
  reasonCode: string;
  /**
   *
   * @type {Array<number>}
   * @memberof FigureRefusalRead
   */
  rowRef: Array<number>;
  /**
   *
   * @type {string}
   * @memberof FigureRefusalRead
   */
  ruleCitation: string;
}

/**
 * Check if a given object implements the FigureRefusalRead interface.
 */
export function instanceOfFigureRefusalRead(
  value: object,
): value is FigureRefusalRead {
  if (!("reasonCode" in value) || value["reasonCode"] === undefined)
    return false;
  if (!("rowRef" in value) || value["rowRef"] === undefined) return false;
  if (!("ruleCitation" in value) || value["ruleCitation"] === undefined)
    return false;
  return true;
}

export function FigureRefusalReadFromJSON(json: any): FigureRefusalRead {
  return FigureRefusalReadFromJSONTyped(json, false);
}

export function FigureRefusalReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FigureRefusalRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    reason: json["reason"] == null ? undefined : ReasonFromJSON(json["reason"]),
    reasonCode: json["reason_code"],
    rowRef: json["row_ref"],
    ruleCitation: json["rule_citation"],
  };
}

export function FigureRefusalReadToJSON(json: any): FigureRefusalRead {
  return FigureRefusalReadToJSONTyped(json, false);
}

export function FigureRefusalReadToJSONTyped(
  value?: FigureRefusalRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    reason: ReasonToJSON(value["reason"]),
    reason_code: value["reasonCode"],
    row_ref: value["rowRef"],
    rule_citation: value["ruleCitation"],
  };
}
