/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FilingWorkflowTemplateSubmit
 */
export interface FilingWorkflowTemplateSubmit {
  /**
   *
   * @type {string}
   * @memberof FilingWorkflowTemplateSubmit
   */
  reason: string;
}

/**
 * Check if a given object implements the FilingWorkflowTemplateSubmit interface.
 */
export function instanceOfFilingWorkflowTemplateSubmit(
  value: object,
): value is FilingWorkflowTemplateSubmit {
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function FilingWorkflowTemplateSubmitFromJSON(
  json: any,
): FilingWorkflowTemplateSubmit {
  return FilingWorkflowTemplateSubmitFromJSONTyped(json, false);
}

export function FilingWorkflowTemplateSubmitFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FilingWorkflowTemplateSubmit {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    reason: json["reason"],
  };
}

export function FilingWorkflowTemplateSubmitToJSON(
  json: any,
): FilingWorkflowTemplateSubmit {
  return FilingWorkflowTemplateSubmitToJSONTyped(json, false);
}

export function FilingWorkflowTemplateSubmitToJSONTyped(
  value?: FilingWorkflowTemplateSubmit | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    reason: value["reason"],
  };
}
