/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FilingReturnCode
 */
export type FilingReturnCode = string | null;

/**
 * Check if a given object implements the FilingReturnCode interface.
 */
export function instanceOfFilingReturnCode(
  value: unknown,
): value is FilingReturnCode {
  return typeof value === "string" || value === null;
}

export function FilingReturnCodeFromJSON(json: any): FilingReturnCode {
  return FilingReturnCodeFromJSONTyped(json, false);
}

export function FilingReturnCodeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FilingReturnCode {
  return json;
}

export function FilingReturnCodeToJSON(json: any): FilingReturnCode {
  return FilingReturnCodeToJSONTyped(json, false);
}

export function FilingReturnCodeToJSONTyped(
  value?: FilingReturnCode | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
