/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FinancialValidationSummaryRead
 */
export interface FinancialValidationSummaryRead {
  /**
   *
   * @type {number}
   * @memberof FinancialValidationSummaryRead
   */
  error?: number;
  /**
   *
   * @type {number}
   * @memberof FinancialValidationSummaryRead
   */
  info?: number;
  /**
   *
   * @type {number}
   * @memberof FinancialValidationSummaryRead
   */
  total?: number;
  /**
   *
   * @type {number}
   * @memberof FinancialValidationSummaryRead
   */
  warning?: number;
}

/**
 * Check if a given object implements the FinancialValidationSummaryRead interface.
 */
export function instanceOfFinancialValidationSummaryRead(
  value: object,
): value is FinancialValidationSummaryRead {
  return true;
}

export function FinancialValidationSummaryReadFromJSON(
  json: any,
): FinancialValidationSummaryRead {
  return FinancialValidationSummaryReadFromJSONTyped(json, false);
}

export function FinancialValidationSummaryReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FinancialValidationSummaryRead {
  if (json == null) {
    return json;
  }
  return {
    error: json["error"] == null ? undefined : json["error"],
    info: json["info"] == null ? undefined : json["info"],
    total: json["total"] == null ? undefined : json["total"],
    warning: json["warning"] == null ? undefined : json["warning"],
  };
}

export function FinancialValidationSummaryReadToJSON(
  json: any,
): FinancialValidationSummaryRead {
  return FinancialValidationSummaryReadToJSONTyped(json, false);
}

export function FinancialValidationSummaryReadToJSONTyped(
  value?: FinancialValidationSummaryRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value["error"],
    info: value["info"],
    total: value["total"],
    warning: value["warning"],
  };
}
