/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FinancialCovenantComplianceStatus } from "./FinancialCovenantComplianceStatus";
import {
  FinancialCovenantComplianceStatusFromJSON,
  FinancialCovenantComplianceStatusFromJSONTyped,
  FinancialCovenantComplianceStatusToJSON,
  FinancialCovenantComplianceStatusToJSONTyped,
} from "./FinancialCovenantComplianceStatus";
import type { FinancialCovenantOperator } from "./FinancialCovenantOperator";
import {
  FinancialCovenantOperatorFromJSON,
  FinancialCovenantOperatorFromJSONTyped,
  FinancialCovenantOperatorToJSON,
  FinancialCovenantOperatorToJSONTyped,
} from "./FinancialCovenantOperator";

/**
 *
 * @export
 * @interface FinancialCovenantRead
 */
export interface FinancialCovenantRead {
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  actualValue: string | null;
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  caseId: string;
  /**
   *
   * @type {FinancialCovenantComplianceStatus}
   * @memberof FinancialCovenantRead
   */
  complianceStatus: FinancialCovenantComplianceStatus;
  /**
   *
   * @type {Date}
   * @memberof FinancialCovenantRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  id: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof FinancialCovenantRead
   */
  metadata: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  metric: string;
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  obligationId: string | null;
  /**
   *
   * @type {FinancialCovenantOperator}
   * @memberof FinancialCovenantRead
   */
  operator: FinancialCovenantOperator;
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  organizationId: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof FinancialCovenantRead
   */
  reportingContext: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  reportingPeriodId: string | null;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof FinancialCovenantRead
   */
  sourceRecord: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof FinancialCovenantRead
   */
  threshold: string;
  /**
   *
   * @type {Date}
   * @memberof FinancialCovenantRead
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the FinancialCovenantRead interface.
 */
export function instanceOfFinancialCovenantRead(
  value: object,
): value is FinancialCovenantRead {
  if (!("actualValue" in value) || value["actualValue"] === undefined)
    return false;
  if (!("caseId" in value) || value["caseId"] === undefined) return false;
  if (!("complianceStatus" in value) || value["complianceStatus"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("metadata" in value) || value["metadata"] === undefined) return false;
  if (!("metric" in value) || value["metric"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("obligationId" in value) || value["obligationId"] === undefined)
    return false;
  if (!("operator" in value) || value["operator"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined)
    return false;
  if (!("reportingContext" in value) || value["reportingContext"] === undefined)
    return false;
  if (
    !("reportingPeriodId" in value) ||
    value["reportingPeriodId"] === undefined
  )
    return false;
  if (!("sourceRecord" in value) || value["sourceRecord"] === undefined)
    return false;
  if (!("threshold" in value) || value["threshold"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function FinancialCovenantReadFromJSON(
  json: any,
): FinancialCovenantRead {
  return FinancialCovenantReadFromJSONTyped(json, false);
}

export function FinancialCovenantReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FinancialCovenantRead {
  if (json == null) {
    return json;
  }
  return {
    actualValue: json["actual_value"],
    caseId: json["case_id"],
    complianceStatus: FinancialCovenantComplianceStatusFromJSON(
      json["compliance_status"],
    ),
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    metadata: json["metadata"],
    metric: json["metric"],
    name: json["name"],
    obligationId: json["obligation_id"],
    operator: FinancialCovenantOperatorFromJSON(json["operator"]),
    organizationId: json["organization_id"],
    reportingContext: json["reporting_context"],
    reportingPeriodId: json["reporting_period_id"],
    sourceRecord: json["source_record"],
    threshold: json["threshold"],
    updatedAt: new Date(json["updated_at"]),
  };
}

export function FinancialCovenantReadToJSON(json: any): FinancialCovenantRead {
  return FinancialCovenantReadToJSONTyped(json, false);
}

export function FinancialCovenantReadToJSONTyped(
  value?: FinancialCovenantRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    actual_value: value["actualValue"],
    case_id: value["caseId"],
    compliance_status: FinancialCovenantComplianceStatusToJSON(
      value["complianceStatus"],
    ),
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    metadata: value["metadata"],
    metric: value["metric"],
    name: value["name"],
    obligation_id: value["obligationId"],
    operator: FinancialCovenantOperatorToJSON(value["operator"]),
    organization_id: value["organizationId"],
    reporting_context: value["reportingContext"],
    reporting_period_id: value["reportingPeriodId"],
    source_record: value["sourceRecord"],
    threshold: value["threshold"],
    updated_at: value["updatedAt"].toISOString(),
  };
}
