/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FinancialValidationEntityType } from "./FinancialValidationEntityType";
import {
  FinancialValidationEntityTypeFromJSON,
  FinancialValidationEntityTypeFromJSONTyped,
  FinancialValidationEntityTypeToJSON,
  FinancialValidationEntityTypeToJSONTyped,
} from "./FinancialValidationEntityType";

/**
 *
 * @export
 * @interface FinancialValidationIssueRead
 */
export interface FinancialValidationIssueRead {
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  caseId: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  code: string | null;
  /**
   *
   * @type {Date}
   * @memberof FinancialValidationIssueRead
   */
  createdAt: Date;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof FinancialValidationIssueRead
   */
  details: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  entityId: string | null;
  /**
   *
   * @type {FinancialValidationEntityType}
   * @memberof FinancialValidationIssueRead
   */
  entityType: FinancialValidationEntityType | null;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  field: string | null;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  fieldName: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  issueKey: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  organizationId: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  recordId: string | null;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  recordTable: string | null;
  /**
   *
   * @type {Date}
   * @memberof FinancialValidationIssueRead
   */
  resolvedAt: Date | null;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  ruleId: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  severity: string;
  /**
   *
   * @type {string}
   * @memberof FinancialValidationIssueRead
   */
  status: string;
}

/**
 * Check if a given object implements the FinancialValidationIssueRead interface.
 */
export function instanceOfFinancialValidationIssueRead(
  value: object,
): value is FinancialValidationIssueRead {
  if (!("caseId" in value) || value["caseId"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("details" in value) || value["details"] === undefined) return false;
  if (!("entityId" in value) || value["entityId"] === undefined) return false;
  if (!("entityType" in value) || value["entityType"] === undefined)
    return false;
  if (!("field" in value) || value["field"] === undefined) return false;
  if (!("fieldName" in value) || value["fieldName"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("issueKey" in value) || value["issueKey"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined)
    return false;
  if (!("recordId" in value) || value["recordId"] === undefined) return false;
  if (!("recordTable" in value) || value["recordTable"] === undefined)
    return false;
  if (!("resolvedAt" in value) || value["resolvedAt"] === undefined)
    return false;
  if (!("ruleId" in value) || value["ruleId"] === undefined) return false;
  if (!("severity" in value) || value["severity"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  return true;
}

export function FinancialValidationIssueReadFromJSON(
  json: any,
): FinancialValidationIssueRead {
  return FinancialValidationIssueReadFromJSONTyped(json, false);
}

export function FinancialValidationIssueReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FinancialValidationIssueRead {
  if (json == null) {
    return json;
  }
  return {
    caseId: json["case_id"],
    code: json["code"],
    createdAt: new Date(json["created_at"]),
    details: json["details"],
    entityId: json["entity_id"],
    entityType: FinancialValidationEntityTypeFromJSON(json["entity_type"]),
    field: json["field"],
    fieldName: json["field_name"],
    id: json["id"],
    issueKey: json["issue_key"],
    message: json["message"],
    organizationId: json["organization_id"],
    recordId: json["record_id"],
    recordTable: json["record_table"],
    resolvedAt:
      json["resolved_at"] == null ? null : new Date(json["resolved_at"]),
    ruleId: json["rule_id"],
    severity: json["severity"],
    status: json["status"],
  };
}

export function FinancialValidationIssueReadToJSON(
  json: any,
): FinancialValidationIssueRead {
  return FinancialValidationIssueReadToJSONTyped(json, false);
}

export function FinancialValidationIssueReadToJSONTyped(
  value?: FinancialValidationIssueRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    case_id: value["caseId"],
    code: value["code"],
    created_at: value["createdAt"].toISOString(),
    details: value["details"],
    entity_id: value["entityId"],
    entity_type: FinancialValidationEntityTypeToJSON(value["entityType"]),
    field: value["field"],
    field_name: value["fieldName"],
    id: value["id"],
    issue_key: value["issueKey"],
    message: value["message"],
    organization_id: value["organizationId"],
    record_id: value["recordId"],
    record_table: value["recordTable"],
    resolved_at:
      value["resolvedAt"] == null
        ? null
        : (value["resolvedAt"] as any).toISOString(),
    rule_id: value["ruleId"],
    severity: value["severity"],
    status: value["status"],
  };
}
