/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FirstAsOfNote
 */
export type FirstAsOfNote = string | null;

/**
 * Check if a given object implements the FirstAsOfNote interface.
 */
export function instanceOfFirstAsOfNote(
  value: unknown,
): value is FirstAsOfNote {
  return typeof value === "string" || value === null;
}

export function FirstAsOfNoteFromJSON(json: any): FirstAsOfNote {
  return FirstAsOfNoteFromJSONTyped(json, false);
}

export function FirstAsOfNoteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FirstAsOfNote {
  return json;
}

export function FirstAsOfNoteToJSON(json: any): FirstAsOfNote {
  return FirstAsOfNoteToJSONTyped(json, false);
}

export function FirstAsOfNoteToJSONTyped(
  value?: FirstAsOfNote | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
