/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ForecastPresetCode } from "./ForecastPresetCode";
import {
  ForecastPresetCodeFromJSON,
  ForecastPresetCodeFromJSONTyped,
  ForecastPresetCodeToJSON,
  ForecastPresetCodeToJSONTyped,
} from "./ForecastPresetCode";

/**
 *
 * @export
 * @interface ForecastScenarioRead
 */
export interface ForecastScenarioRead {
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof ForecastScenarioRead
   */
  assumptions: { [key: string]: string };
  /**
   *
   * @type {ForecastPresetCode}
   * @memberof ForecastScenarioRead
   */
  code: ForecastPresetCode;
}

/**
 * Check if a given object implements the ForecastScenarioRead interface.
 */
export function instanceOfForecastScenarioRead(
  value: object,
): value is ForecastScenarioRead {
  if (!("assumptions" in value) || value["assumptions"] === undefined)
    return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  return true;
}

export function ForecastScenarioReadFromJSON(json: any): ForecastScenarioRead {
  return ForecastScenarioReadFromJSONTyped(json, false);
}

export function ForecastScenarioReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForecastScenarioRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    assumptions: json["assumptions"],
    code: ForecastPresetCodeFromJSON(json["code"]),
  };
}

export function ForecastScenarioReadToJSON(json: any): ForecastScenarioRead {
  return ForecastScenarioReadToJSONTyped(json, false);
}

export function ForecastScenarioReadToJSONTyped(
  value?: ForecastScenarioRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    assumptions: value["assumptions"],
    code: ForecastPresetCodeToJSON(value["code"]),
  };
}
