/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const ForecastScenarioCode = {
  Base: "base",
  Adverse: "adverse",
  SeverelyAdverse: "severely_adverse",
  Custom: "custom",
} as const;
export type ForecastScenarioCode =
  (typeof ForecastScenarioCode)[keyof typeof ForecastScenarioCode];

export function instanceOfForecastScenarioCode(value: any): boolean {
  for (const key in ForecastScenarioCode) {
    if (Object.prototype.hasOwnProperty.call(ForecastScenarioCode, key)) {
      if (
        ForecastScenarioCode[key as keyof typeof ForecastScenarioCode] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function ForecastScenarioCodeFromJSON(json: any): ForecastScenarioCode {
  return ForecastScenarioCodeFromJSONTyped(json, false);
}

export function ForecastScenarioCodeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForecastScenarioCode {
  return json as ForecastScenarioCode;
}

export function ForecastScenarioCodeToJSON(
  value?: ForecastScenarioCode | null,
): any {
  return value as any;
}

export function ForecastScenarioCodeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): ForecastScenarioCode {
  return value as ForecastScenarioCode;
}
