/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Details } from "./Details";
import {
  DetailsFromJSON,
  DetailsFromJSONTyped,
  DetailsToJSON,
  DetailsToJSONTyped,
} from "./Details";
import type { RegulatoryRunErrorRead } from "./RegulatoryRunErrorRead";
import {
  RegulatoryRunErrorReadFromJSON,
  RegulatoryRunErrorReadFromJSONTyped,
  RegulatoryRunErrorReadToJSON,
  RegulatoryRunErrorReadToJSONTyped,
} from "./RegulatoryRunErrorRead";

/**
 *
 * @export
 * @interface ForecastRunError
 */
export interface ForecastRunError {
  /**
   *
   * @type {string}
   * @memberof ForecastRunError
   */
  code: string;
  /**
   *
   * @type {Details}
   * @memberof ForecastRunError
   */
  details?: Details;
  /**
   *
   * @type {string}
   * @memberof ForecastRunError
   */
  message: string;
}

/**
 * Check if a given object implements the ForecastRunError interface.
 */
export function instanceOfForecastRunError(
  value: object,
): value is ForecastRunError {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function ForecastRunErrorFromJSON(json: any): ForecastRunError {
  return ForecastRunErrorFromJSONTyped(json, false);
}

export function ForecastRunErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForecastRunError {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    details:
      json["details"] == null ? undefined : DetailsFromJSON(json["details"]),
    message: json["message"],
  };
}

export function ForecastRunErrorToJSON(json: any): ForecastRunError {
  return ForecastRunErrorToJSONTyped(json, false);
}

export function ForecastRunErrorToJSONTyped(
  value?: ForecastRunError | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    details: DetailsToJSON(value["details"]),
    message: value["message"],
  };
}
