/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ForecastProjectionSummary } from "./ForecastProjectionSummary";
import {
  ForecastProjectionSummaryFromJSON,
  ForecastProjectionSummaryFromJSONTyped,
  ForecastProjectionSummaryToJSON,
  ForecastProjectionSummaryToJSONTyped,
} from "./ForecastProjectionSummary";
import type { ForecastRunCompletedAt } from "./ForecastRunCompletedAt";
import {
  ForecastRunCompletedAtFromJSON,
  ForecastRunCompletedAtFromJSONTyped,
  ForecastRunCompletedAtToJSON,
  ForecastRunCompletedAtToJSONTyped,
} from "./ForecastRunCompletedAt";
import type { RegulatoryRunStatus } from "./RegulatoryRunStatus";
import {
  RegulatoryRunStatusFromJSON,
  RegulatoryRunStatusFromJSONTyped,
  RegulatoryRunStatusToJSON,
  RegulatoryRunStatusToJSONTyped,
} from "./RegulatoryRunStatus";
import type { RegulatoryMetricResultRead } from "./RegulatoryMetricResultRead";
import {
  RegulatoryMetricResultReadFromJSON,
  RegulatoryMetricResultReadFromJSONTyped,
  RegulatoryMetricResultReadToJSON,
  RegulatoryMetricResultReadToJSONTyped,
} from "./RegulatoryMetricResultRead";
import type { RegulatoryValidationRead } from "./RegulatoryValidationRead";
import {
  RegulatoryValidationReadFromJSON,
  RegulatoryValidationReadFromJSONTyped,
  RegulatoryValidationReadToJSON,
  RegulatoryValidationReadToJSONTyped,
} from "./RegulatoryValidationRead";
import type { ForecastRunStartedAt } from "./ForecastRunStartedAt";
import {
  ForecastRunStartedAtFromJSON,
  ForecastRunStartedAtFromJSONTyped,
  ForecastRunStartedAtToJSON,
  ForecastRunStartedAtToJSONTyped,
} from "./ForecastRunStartedAt";
import type { ResolvedForecastAssumptions } from "./ResolvedForecastAssumptions";
import {
  ResolvedForecastAssumptionsFromJSON,
  ResolvedForecastAssumptionsFromJSONTyped,
  ResolvedForecastAssumptionsToJSON,
  ResolvedForecastAssumptionsToJSONTyped,
} from "./ResolvedForecastAssumptions";
import type { ProjectionYearRead } from "./ProjectionYearRead";
import {
  ProjectionYearReadFromJSON,
  ProjectionYearReadFromJSONTyped,
  ProjectionYearReadToJSON,
  ProjectionYearReadToJSONTyped,
} from "./ProjectionYearRead";
import type { ForecastScenarioCode } from "./ForecastScenarioCode";
import {
  ForecastScenarioCodeFromJSON,
  ForecastScenarioCodeFromJSONTyped,
  ForecastScenarioCodeToJSON,
  ForecastScenarioCodeToJSONTyped,
} from "./ForecastScenarioCode";
import type { ForecastRunError } from "./ForecastRunError";
import {
  ForecastRunErrorFromJSON,
  ForecastRunErrorFromJSONTyped,
  ForecastRunErrorToJSON,
  ForecastRunErrorToJSONTyped,
} from "./ForecastRunError";

/**
 *
 * @export
 * @interface ForecastRunRead
 */
export interface ForecastRunRead {
  /**
   *
   * @type {ResolvedForecastAssumptions}
   * @memberof ForecastRunRead
   */
  assumptions: ResolvedForecastAssumptions;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  bankId: string;
  /**
   *
   * @type {ForecastRunCompletedAt}
   * @memberof ForecastRunRead
   */
  completedAt: ForecastRunCompletedAt;
  /**
   *
   * @type {Date}
   * @memberof ForecastRunRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  createdBy: string;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  engineVersion: string;
  /**
   *
   * @type {ForecastRunError}
   * @memberof ForecastRunRead
   */
  error: ForecastRunError;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  inputHash: string;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  inputSchemaVersion: string;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof ForecastRunRead
   */
  inputs: { [key: string]: any };
  /**
   *
   * @type {Array<RegulatoryMetricResultRead>}
   * @memberof ForecastRunRead
   */
  metricResults: Array<RegulatoryMetricResultRead>;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  module: string;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  organizationId: string;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  outputSchemaVersion: string;
  /**
   *
   * @type {Array<ProjectionYearRead>}
   * @memberof ForecastRunRead
   */
  path: Array<ProjectionYearRead>;
  /**
   *
   * @type {string}
   * @memberof ForecastRunRead
   */
  reportingPeriodId: string;
  /**
   *
   * @type {ForecastScenarioCode}
   * @memberof ForecastRunRead
   */
  scenarioCode: ForecastScenarioCode;
  /**
   *
   * @type {ForecastRunStartedAt}
   * @memberof ForecastRunRead
   */
  startedAt: ForecastRunStartedAt;
  /**
   *
   * @type {RegulatoryRunStatus}
   * @memberof ForecastRunRead
   */
  status: RegulatoryRunStatus;
  /**
   *
   * @type {ForecastProjectionSummary}
   * @memberof ForecastRunRead
   */
  summary: ForecastProjectionSummary;
  /**
   *
   * @type {Date}
   * @memberof ForecastRunRead
   */
  updatedAt: Date;
  /**
   *
   * @type {Array<RegulatoryValidationRead>}
   * @memberof ForecastRunRead
   */
  validations: Array<RegulatoryValidationRead>;
}

/**
 * Check if a given object implements the ForecastRunRead interface.
 */
export function instanceOfForecastRunRead(
  value: object,
): value is ForecastRunRead {
  if (!("assumptions" in value) || value["assumptions"] === undefined)
    return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("completedAt" in value) || value["completedAt"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
  if (!("engineVersion" in value) || value["engineVersion"] === undefined)
    return false;
  if (!("error" in value) || value["error"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("inputHash" in value) || value["inputHash"] === undefined) return false;
  if (
    !("inputSchemaVersion" in value) ||
    value["inputSchemaVersion"] === undefined
  )
    return false;
  if (!("inputs" in value) || value["inputs"] === undefined) return false;
  if (!("metricResults" in value) || value["metricResults"] === undefined)
    return false;
  if (!("module" in value) || value["module"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined)
    return false;
  if (
    !("outputSchemaVersion" in value) ||
    value["outputSchemaVersion"] === undefined
  )
    return false;
  if (!("path" in value) || value["path"] === undefined) return false;
  if (
    !("reportingPeriodId" in value) ||
    value["reportingPeriodId"] === undefined
  )
    return false;
  if (!("scenarioCode" in value) || value["scenarioCode"] === undefined)
    return false;
  if (!("startedAt" in value) || value["startedAt"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("summary" in value) || value["summary"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("validations" in value) || value["validations"] === undefined)
    return false;
  return true;
}

export function ForecastRunReadFromJSON(json: any): ForecastRunRead {
  return ForecastRunReadFromJSONTyped(json, false);
}

export function ForecastRunReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForecastRunRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    assumptions: ResolvedForecastAssumptionsFromJSON(json["assumptions"]),
    bankId: json["bank_id"],
    completedAt: ForecastRunCompletedAtFromJSON(json["completed_at"]),
    createdAt: new Date(json["created_at"]),
    createdBy: json["created_by"],
    engineVersion: json["engine_version"],
    error: ForecastRunErrorFromJSON(json["error"]),
    id: json["id"],
    inputHash: json["input_hash"],
    inputSchemaVersion: json["input_schema_version"],
    inputs: json["inputs"],
    metricResults: (json["metric_results"] as Array<any>).map(
      RegulatoryMetricResultReadFromJSON,
    ),
    module: json["module"],
    organizationId: json["organization_id"],
    outputSchemaVersion: json["output_schema_version"],
    path: (json["path"] as Array<any>).map(ProjectionYearReadFromJSON),
    reportingPeriodId: json["reporting_period_id"],
    scenarioCode: ForecastScenarioCodeFromJSON(json["scenario_code"]),
    startedAt: ForecastRunStartedAtFromJSON(json["started_at"]),
    status: RegulatoryRunStatusFromJSON(json["status"]),
    summary: ForecastProjectionSummaryFromJSON(json["summary"]),
    updatedAt: new Date(json["updated_at"]),
    validations: (json["validations"] as Array<any>).map(
      RegulatoryValidationReadFromJSON,
    ),
  };
}

export function ForecastRunReadToJSON(json: any): ForecastRunRead {
  return ForecastRunReadToJSONTyped(json, false);
}

export function ForecastRunReadToJSONTyped(
  value?: ForecastRunRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    assumptions: ResolvedForecastAssumptionsToJSON(value["assumptions"]),
    bank_id: value["bankId"],
    completed_at: ForecastRunCompletedAtToJSON(value["completedAt"]),
    created_at: value["createdAt"].toISOString(),
    created_by: value["createdBy"],
    engine_version: value["engineVersion"],
    error: ForecastRunErrorToJSON(value["error"]),
    id: value["id"],
    input_hash: value["inputHash"],
    input_schema_version: value["inputSchemaVersion"],
    inputs: value["inputs"],
    metric_results: (value["metricResults"] as Array<any>).map(
      RegulatoryMetricResultReadToJSON,
    ),
    module: value["module"],
    organization_id: value["organizationId"],
    output_schema_version: value["outputSchemaVersion"],
    path: (value["path"] as Array<any>).map(ProjectionYearReadToJSON),
    reporting_period_id: value["reportingPeriodId"],
    scenario_code: ForecastScenarioCodeToJSON(value["scenarioCode"]),
    started_at: ForecastRunStartedAtToJSON(value["startedAt"]),
    status: RegulatoryRunStatusToJSON(value["status"]),
    summary: ForecastProjectionSummaryToJSON(value["summary"]),
    updated_at: value["updatedAt"].toISOString(),
    validations: (value["validations"] as Array<any>).map(
      RegulatoryValidationReadToJSON,
    ),
  };
}
