/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ForecastPresetAssumptionsWrite } from "./ForecastPresetAssumptionsWrite";
import {
  ForecastPresetAssumptionsWriteFromJSON,
  ForecastPresetAssumptionsWriteFromJSONTyped,
  ForecastPresetAssumptionsWriteToJSON,
  ForecastPresetAssumptionsWriteToJSONTyped,
} from "./ForecastPresetAssumptionsWrite";

/**
 * A complete proposal: every preset scenario with every driver.
 * @export
 * @interface ForecastPresetSetWrite
 */
export interface ForecastPresetSetWrite {
  /**
   *
   * @type {ForecastPresetAssumptionsWrite}
   * @memberof ForecastPresetSetWrite
   */
  adverse: ForecastPresetAssumptionsWrite;
  /**
   *
   * @type {ForecastPresetAssumptionsWrite}
   * @memberof ForecastPresetSetWrite
   */
  base: ForecastPresetAssumptionsWrite;
  /**
   *
   * @type {ForecastPresetAssumptionsWrite}
   * @memberof ForecastPresetSetWrite
   */
  severelyAdverse: ForecastPresetAssumptionsWrite;
}

/**
 * Check if a given object implements the ForecastPresetSetWrite interface.
 */
export function instanceOfForecastPresetSetWrite(
  value: object,
): value is ForecastPresetSetWrite {
  if (!("adverse" in value) || value["adverse"] === undefined) return false;
  if (!("base" in value) || value["base"] === undefined) return false;
  if (!("severelyAdverse" in value) || value["severelyAdverse"] === undefined)
    return false;
  return true;
}

export function ForecastPresetSetWriteFromJSON(
  json: any,
): ForecastPresetSetWrite {
  return ForecastPresetSetWriteFromJSONTyped(json, false);
}

export function ForecastPresetSetWriteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForecastPresetSetWrite {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    adverse: ForecastPresetAssumptionsWriteFromJSON(json["adverse"]),
    base: ForecastPresetAssumptionsWriteFromJSON(json["base"]),
    severelyAdverse: ForecastPresetAssumptionsWriteFromJSON(
      json["severely_adverse"],
    ),
  };
}

export function ForecastPresetSetWriteToJSON(
  json: any,
): ForecastPresetSetWrite {
  return ForecastPresetSetWriteToJSONTyped(json, false);
}

export function ForecastPresetSetWriteToJSONTyped(
  value?: ForecastPresetSetWrite | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    adverse: ForecastPresetAssumptionsWriteToJSON(value["adverse"]),
    base: ForecastPresetAssumptionsWriteToJSON(value["base"]),
    severely_adverse: ForecastPresetAssumptionsWriteToJSON(
      value["severelyAdverse"],
    ),
  };
}
