/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * One calibrating pillar instrument from the determination's input snapshot.
 * @export
 * @interface ForwardGridPillarRead
 */
export interface ForwardGridPillarRead {
  /**
   *
   * @type {string}
   * @memberof ForwardGridPillarRead
   */
  instrument: string;
  /**
   *
   * @type {string}
   * @memberof ForwardGridPillarRead
   */
  quote: string;
  /**
   *
   * @type {string}
   * @memberof ForwardGridPillarRead
   */
  tenor: string;
}

/**
 * Check if a given object implements the ForwardGridPillarRead interface.
 */
export function instanceOfForwardGridPillarRead(
  value: object,
): value is ForwardGridPillarRead {
  if (!("instrument" in value) || value["instrument"] === undefined)
    return false;
  if (!("quote" in value) || value["quote"] === undefined) return false;
  if (!("tenor" in value) || value["tenor"] === undefined) return false;
  return true;
}

export function ForwardGridPillarReadFromJSON(
  json: any,
): ForwardGridPillarRead {
  return ForwardGridPillarReadFromJSONTyped(json, false);
}

export function ForwardGridPillarReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForwardGridPillarRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    instrument: json["instrument"],
    quote: json["quote"],
    tenor: json["tenor"],
  };
}

export function ForwardGridPillarReadToJSON(json: any): ForwardGridPillarRead {
  return ForwardGridPillarReadToJSONTyped(json, false);
}

export function ForwardGridPillarReadToJSONTyped(
  value?: ForwardGridPillarRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    instrument: value["instrument"],
    quote: value["quote"],
    tenor: value["tenor"],
  };
}
