/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FrameworkVersion
 */
export type FrameworkVersion = string | null;

/**
 * Check if a given object implements the FrameworkVersion interface.
 */
export function instanceOfFrameworkVersion(
  value: unknown,
): value is FrameworkVersion {
  return typeof value === "string" || value === null;
}

export function FrameworkVersionFromJSON(json: any): FrameworkVersion {
  return FrameworkVersionFromJSONTyped(json, false);
}

export function FrameworkVersionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FrameworkVersion {
  return json;
}

export function FrameworkVersionToJSON(json: any): FrameworkVersion {
  return FrameworkVersionToJSONTyped(json, false);
}

export function FrameworkVersionToJSONTyped(
  value?: FrameworkVersion | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
