/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FtpNmdSegmentRead
 */
export interface FtpNmdSegmentRead {
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  assignedFtpPct: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  balanceGhs: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  coreAmountGhs: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  coreFtpPct: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  corePct: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  effectiveDurationYears: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  segment: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  volatileAmountGhs: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  volatileFtpPct: string;
  /**
   *
   * @type {string}
   * @memberof FtpNmdSegmentRead
   */
  volatilePct: string;
  /**
   *
   * @type {boolean}
   * @memberof FtpNmdSegmentRead
   */
  withinPolicy: boolean;
}

/**
 * Check if a given object implements the FtpNmdSegmentRead interface.
 */
export function instanceOfFtpNmdSegmentRead(
  value: object,
): value is FtpNmdSegmentRead {
  if (!("assignedFtpPct" in value) || value["assignedFtpPct"] === undefined)
    return false;
  if (!("balanceGhs" in value) || value["balanceGhs"] === undefined)
    return false;
  if (!("coreAmountGhs" in value) || value["coreAmountGhs"] === undefined)
    return false;
  if (!("coreFtpPct" in value) || value["coreFtpPct"] === undefined)
    return false;
  if (!("corePct" in value) || value["corePct"] === undefined) return false;
  if (
    !("effectiveDurationYears" in value) ||
    value["effectiveDurationYears"] === undefined
  )
    return false;
  if (!("segment" in value) || value["segment"] === undefined) return false;
  if (
    !("volatileAmountGhs" in value) ||
    value["volatileAmountGhs"] === undefined
  )
    return false;
  if (!("volatileFtpPct" in value) || value["volatileFtpPct"] === undefined)
    return false;
  if (!("volatilePct" in value) || value["volatilePct"] === undefined)
    return false;
  if (!("withinPolicy" in value) || value["withinPolicy"] === undefined)
    return false;
  return true;
}

export function FtpNmdSegmentReadFromJSON(json: any): FtpNmdSegmentRead {
  return FtpNmdSegmentReadFromJSONTyped(json, false);
}

export function FtpNmdSegmentReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FtpNmdSegmentRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    assignedFtpPct: json["assigned_ftp_pct"],
    balanceGhs: json["balance_ghs"],
    coreAmountGhs: json["core_amount_ghs"],
    coreFtpPct: json["core_ftp_pct"],
    corePct: json["core_pct"],
    effectiveDurationYears: json["effective_duration_years"],
    segment: json["segment"],
    volatileAmountGhs: json["volatile_amount_ghs"],
    volatileFtpPct: json["volatile_ftp_pct"],
    volatilePct: json["volatile_pct"],
    withinPolicy: json["within_policy"],
  };
}

export function FtpNmdSegmentReadToJSON(json: any): FtpNmdSegmentRead {
  return FtpNmdSegmentReadToJSONTyped(json, false);
}

export function FtpNmdSegmentReadToJSONTyped(
  value?: FtpNmdSegmentRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    assigned_ftp_pct: value["assignedFtpPct"],
    balance_ghs: value["balanceGhs"],
    core_amount_ghs: value["coreAmountGhs"],
    core_ftp_pct: value["coreFtpPct"],
    core_pct: value["corePct"],
    effective_duration_years: value["effectiveDurationYears"],
    segment: value["segment"],
    volatile_amount_ghs: value["volatileAmountGhs"],
    volatile_ftp_pct: value["volatileFtpPct"],
    volatile_pct: value["volatilePct"],
    within_policy: value["withinPolicy"],
  };
}
