/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FxRateTenorMonths
 */
export type FxRateTenorMonths = number | null;

/**
 * Check if a given object implements the FxRateTenorMonths interface.
 */
export function instanceOfFxRateTenorMonths(
  value: unknown,
): value is FxRateTenorMonths {
  return typeof value === "number" || value === null;
}

export function FxRateTenorMonthsFromJSON(json: any): FxRateTenorMonths {
  return FxRateTenorMonthsFromJSONTyped(json, false);
}

export function FxRateTenorMonthsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FxRateTenorMonths {
  return json;
}

export function FxRateTenorMonthsToJSON(json: any): FxRateTenorMonths {
  return FxRateTenorMonthsToJSONTyped(json, false);
}

export function FxRateTenorMonthsToJSONTyped(
  value?: FxRateTenorMonths | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
