/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FxScenarioCode } from "./FxScenarioCode";
import {
  FxScenarioCodeFromJSON,
  FxScenarioCodeFromJSONTyped,
  FxScenarioCodeToJSON,
  FxScenarioCodeToJSONTyped,
} from "./FxScenarioCode";

/**
 *
 * @export
 * @interface FxScenarioNopRead
 */
export interface FxScenarioNopRead {
  /**
   *
   * @type {string}
   * @memberof FxScenarioNopRead
   */
  nopGhs: string;
  /**
   *
   * @type {string}
   * @memberof FxScenarioNopRead
   */
  nopPctTier1: string;
  /**
   *
   * @type {FxScenarioCode}
   * @memberof FxScenarioNopRead
   */
  scenarioCode: FxScenarioCode;
  /**
   *
   * @type {string}
   * @memberof FxScenarioNopRead
   */
  shockPct: string;
  /**
   *
   * @type {boolean}
   * @memberof FxScenarioNopRead
   */
  withinAggregateLimit: boolean;
}

/**
 * Check if a given object implements the FxScenarioNopRead interface.
 */
export function instanceOfFxScenarioNopRead(
  value: object,
): value is FxScenarioNopRead {
  if (!("nopGhs" in value) || value["nopGhs"] === undefined) return false;
  if (!("nopPctTier1" in value) || value["nopPctTier1"] === undefined)
    return false;
  if (!("scenarioCode" in value) || value["scenarioCode"] === undefined)
    return false;
  if (!("shockPct" in value) || value["shockPct"] === undefined) return false;
  if (
    !("withinAggregateLimit" in value) ||
    value["withinAggregateLimit"] === undefined
  )
    return false;
  return true;
}

export function FxScenarioNopReadFromJSON(json: any): FxScenarioNopRead {
  return FxScenarioNopReadFromJSONTyped(json, false);
}

export function FxScenarioNopReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FxScenarioNopRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    nopGhs: json["nop_ghs"],
    nopPctTier1: json["nop_pct_tier1"],
    scenarioCode: FxScenarioCodeFromJSON(json["scenario_code"]),
    shockPct: json["shock_pct"],
    withinAggregateLimit: json["within_aggregate_limit"],
  };
}

export function FxScenarioNopReadToJSON(json: any): FxScenarioNopRead {
  return FxScenarioNopReadToJSONTyped(json, false);
}

export function FxScenarioNopReadToJSONTyped(
  value?: FxScenarioNopRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    nop_ghs: value["nopGhs"],
    nop_pct_tier1: value["nopPctTier1"],
    scenario_code: FxScenarioCodeToJSON(value["scenarioCode"]),
    shock_pct: value["shockPct"],
    within_aggregate_limit: value["withinAggregateLimit"],
  };
}
