/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IcaapAiSegmentRead } from "./IcaapAiSegmentRead";
import {
  IcaapAiSegmentReadFromJSON,
  IcaapAiSegmentReadFromJSONTyped,
  IcaapAiSegmentReadToJSON,
  IcaapAiSegmentReadToJSONTyped,
} from "./IcaapAiSegmentRead";

/**
 *
 * @export
 * @interface IcaapAiParagraphRead
 */
export interface IcaapAiParagraphRead {
  /**
   *
   * @type {number}
   * @memberof IcaapAiParagraphRead
   */
  index: number;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapAiParagraphRead
   */
  requirementIds: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapAiParagraphRead
   */
  requirementLabels: Array<string>;
  /**
   *
   * @type {Array<IcaapAiSegmentRead>}
   * @memberof IcaapAiParagraphRead
   */
  segments: Array<IcaapAiSegmentRead>;
}

/**
 * Check if a given object implements the IcaapAiParagraphRead interface.
 */
export function instanceOfIcaapAiParagraphRead(
  value: object,
): value is IcaapAiParagraphRead {
  if (!("index" in value) || value["index"] === undefined) return false;
  if (!("requirementIds" in value) || value["requirementIds"] === undefined)
    return false;
  if (
    !("requirementLabels" in value) ||
    value["requirementLabels"] === undefined
  )
    return false;
  if (!("segments" in value) || value["segments"] === undefined) return false;
  return true;
}

export function IcaapAiParagraphReadFromJSON(json: any): IcaapAiParagraphRead {
  return IcaapAiParagraphReadFromJSONTyped(json, false);
}

export function IcaapAiParagraphReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapAiParagraphRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    index: json["index"],
    requirementIds: json["requirement_ids"],
    requirementLabels: json["requirement_labels"],
    segments: (json["segments"] as Array<any>).map(IcaapAiSegmentReadFromJSON),
  };
}

export function IcaapAiParagraphReadToJSON(json: any): IcaapAiParagraphRead {
  return IcaapAiParagraphReadToJSONTyped(json, false);
}

export function IcaapAiParagraphReadToJSONTyped(
  value?: IcaapAiParagraphRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    index: value["index"],
    requirement_ids: value["requirementIds"],
    requirement_labels: value["requirementLabels"],
    segments: (value["segments"] as Array<any>).map(IcaapAiSegmentReadToJSON),
  };
}
