/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Stressed } from "./Stressed";
import {
  StressedFromJSON,
  StressedFromJSONTyped,
  StressedToJSON,
  StressedToJSONTyped,
} from "./Stressed";
import type { Baseline } from "./Baseline";
import {
  BaselineFromJSON,
  BaselineFromJSONTyped,
  BaselineToJSON,
  BaselineToJSONTyped,
} from "./Baseline";

/**
 *
 * @export
 * @interface IcaapTable5RowTotalRead
 */
export interface IcaapTable5RowTotalRead {
  /**
   *
   * @type {Baseline}
   * @memberof IcaapTable5RowTotalRead
   */
  baseline?: Baseline;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapTable5RowTotalRead
   */
  itemKeys: Array<string>;
  /**
   *
   * @type {string}
   * @memberof IcaapTable5RowTotalRead
   */
  label: string;
  /**
   *
   * @type {boolean}
   * @memberof IcaapTable5RowTotalRead
   */
  partial: boolean;
  /**
   *
   * @type {string}
   * @memberof IcaapTable5RowTotalRead
   */
  row: string;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapTable5RowTotalRead
   */
  sources: Array<string>;
  /**
   *
   * @type {Stressed}
   * @memberof IcaapTable5RowTotalRead
   */
  stressed?: Stressed;
}

/**
 * Check if a given object implements the IcaapTable5RowTotalRead interface.
 */
export function instanceOfIcaapTable5RowTotalRead(
  value: object,
): value is IcaapTable5RowTotalRead {
  if (!("itemKeys" in value) || value["itemKeys"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("partial" in value) || value["partial"] === undefined) return false;
  if (!("row" in value) || value["row"] === undefined) return false;
  if (!("sources" in value) || value["sources"] === undefined) return false;
  return true;
}

export function IcaapTable5RowTotalReadFromJSON(
  json: any,
): IcaapTable5RowTotalRead {
  return IcaapTable5RowTotalReadFromJSONTyped(json, false);
}

export function IcaapTable5RowTotalReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapTable5RowTotalRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    baseline:
      json["baseline"] == null ? undefined : BaselineFromJSON(json["baseline"]),
    itemKeys: json["item_keys"],
    label: json["label"],
    partial: json["partial"],
    row: json["row"],
    sources: json["sources"],
    stressed:
      json["stressed"] == null ? undefined : StressedFromJSON(json["stressed"]),
  };
}

export function IcaapTable5RowTotalReadToJSON(
  json: any,
): IcaapTable5RowTotalRead {
  return IcaapTable5RowTotalReadToJSONTyped(json, false);
}

export function IcaapTable5RowTotalReadToJSONTyped(
  value?: IcaapTable5RowTotalRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    baseline: BaselineToJSON(value["baseline"]),
    item_keys: value["itemKeys"],
    label: value["label"],
    partial: value["partial"],
    row: value["row"],
    sources: value["sources"],
    stressed: StressedToJSON(value["stressed"]),
  };
}
