/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IcaapChallengeOutcome } from "./IcaapChallengeOutcome";
import {
  IcaapChallengeOutcomeFromJSON,
  IcaapChallengeOutcomeFromJSONTyped,
  IcaapChallengeOutcomeToJSON,
  IcaapChallengeOutcomeToJSONTyped,
} from "./IcaapChallengeOutcome";

/**
 *
 * @export
 * @interface IcaapChallengeResponseRead
 */
export interface IcaapChallengeResponseRead {
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof IcaapChallengeResponseRead
   */
  changeReferences: Array<{ [key: string]: any }>;
  /**
   *
   * @type {Date}
   * @memberof IcaapChallengeResponseRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof IcaapChallengeResponseRead
   */
  id: string;
  /**
   *
   * @type {IcaapChallengeOutcome}
   * @memberof IcaapChallengeResponseRead
   */
  outcome: IcaapChallengeOutcome;
  /**
   *
   * @type {string}
   * @memberof IcaapChallengeResponseRead
   */
  respondedBy: string;
  /**
   *
   * @type {string}
   * @memberof IcaapChallengeResponseRead
   */
  responderFunction: string;
  /**
   *
   * @type {number}
   * @memberof IcaapChallengeResponseRead
   */
  responseNo: number;
  /**
   *
   * @type {string}
   * @memberof IcaapChallengeResponseRead
   */
  responseText: string;
}

/**
 * Check if a given object implements the IcaapChallengeResponseRead interface.
 */
export function instanceOfIcaapChallengeResponseRead(
  value: object,
): value is IcaapChallengeResponseRead {
  if (!("changeReferences" in value) || value["changeReferences"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("outcome" in value) || value["outcome"] === undefined) return false;
  if (!("respondedBy" in value) || value["respondedBy"] === undefined)
    return false;
  if (
    !("responderFunction" in value) ||
    value["responderFunction"] === undefined
  )
    return false;
  if (!("responseNo" in value) || value["responseNo"] === undefined)
    return false;
  if (!("responseText" in value) || value["responseText"] === undefined)
    return false;
  return true;
}

export function IcaapChallengeResponseReadFromJSON(
  json: any,
): IcaapChallengeResponseRead {
  return IcaapChallengeResponseReadFromJSONTyped(json, false);
}

export function IcaapChallengeResponseReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapChallengeResponseRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    changeReferences: json["change_references"],
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    outcome: IcaapChallengeOutcomeFromJSON(json["outcome"]),
    respondedBy: json["responded_by"],
    responderFunction: json["responder_function"],
    responseNo: json["response_no"],
    responseText: json["response_text"],
  };
}

export function IcaapChallengeResponseReadToJSON(
  json: any,
): IcaapChallengeResponseRead {
  return IcaapChallengeResponseReadToJSONTyped(json, false);
}

export function IcaapChallengeResponseReadToJSONTyped(
  value?: IcaapChallengeResponseRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    change_references: value["changeReferences"],
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    outcome: IcaapChallengeOutcomeToJSON(value["outcome"]),
    responded_by: value["respondedBy"],
    responder_function: value["responderFunction"],
    response_no: value["responseNo"],
    response_text: value["responseText"],
  };
}
