/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IcaapWorkflowTemplateDecision
 */
export interface IcaapWorkflowTemplateDecision {
  /**
   *
   * @type {string}
   * @memberof IcaapWorkflowTemplateDecision
   */
  decision: IcaapWorkflowTemplateDecisionDecisionEnum;
  /**
   *
   * @type {string}
   * @memberof IcaapWorkflowTemplateDecision
   */
  reason: string;
}

/**
 * @export
 */
export const IcaapWorkflowTemplateDecisionDecisionEnum = {
  Approved: "approved",
  Rejected: "rejected",
} as const;
export type IcaapWorkflowTemplateDecisionDecisionEnum =
  (typeof IcaapWorkflowTemplateDecisionDecisionEnum)[keyof typeof IcaapWorkflowTemplateDecisionDecisionEnum];

/**
 * Check if a given object implements the IcaapWorkflowTemplateDecision interface.
 */
export function instanceOfIcaapWorkflowTemplateDecision(
  value: object,
): value is IcaapWorkflowTemplateDecision {
  if (!("decision" in value) || value["decision"] === undefined) return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function IcaapWorkflowTemplateDecisionFromJSON(
  json: any,
): IcaapWorkflowTemplateDecision {
  return IcaapWorkflowTemplateDecisionFromJSONTyped(json, false);
}

export function IcaapWorkflowTemplateDecisionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapWorkflowTemplateDecision {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    decision: json["decision"],
    reason: json["reason"],
  };
}

export function IcaapWorkflowTemplateDecisionToJSON(
  json: any,
): IcaapWorkflowTemplateDecision {
  return IcaapWorkflowTemplateDecisionToJSONTyped(json, false);
}

export function IcaapWorkflowTemplateDecisionToJSONTyped(
  value?: IcaapWorkflowTemplateDecision | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    decision: value["decision"],
    reason: value["reason"],
  };
}
