/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IcaapPillar2ComputeManualInputs } from "./IcaapPillar2ComputeManualInputs";
import {
  IcaapPillar2ComputeManualInputsFromJSON,
  IcaapPillar2ComputeManualInputsFromJSONTyped,
  IcaapPillar2ComputeManualInputsToJSON,
  IcaapPillar2ComputeManualInputsToJSONTyped,
} from "./IcaapPillar2ComputeManualInputs";

/**
 *
 * @export
 * @interface IcaapPillar2Compute
 */
export interface IcaapPillar2Compute {
  /**
   *
   * @type {number}
   * @memberof IcaapPillar2Compute
   */
  baseRevisionNo: number;
  /**
   *
   * @type {IcaapPillar2ComputeManualInputs}
   * @memberof IcaapPillar2Compute
   */
  manualInputs?: IcaapPillar2ComputeManualInputs;
  /**
   *
   * @type {string}
   * @memberof IcaapPillar2Compute
   */
  reason: string;
}

/**
 * Check if a given object implements the IcaapPillar2Compute interface.
 */
export function instanceOfIcaapPillar2Compute(
  value: object,
): value is IcaapPillar2Compute {
  if (!("baseRevisionNo" in value) || value["baseRevisionNo"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function IcaapPillar2ComputeFromJSON(json: any): IcaapPillar2Compute {
  return IcaapPillar2ComputeFromJSONTyped(json, false);
}

export function IcaapPillar2ComputeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapPillar2Compute {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    baseRevisionNo: json["base_revision_no"],
    manualInputs:
      json["manual_inputs"] == null
        ? undefined
        : IcaapPillar2ComputeManualInputsFromJSON(json["manual_inputs"]),
    reason: json["reason"],
  };
}

export function IcaapPillar2ComputeToJSON(json: any): IcaapPillar2Compute {
  return IcaapPillar2ComputeToJSONTyped(json, false);
}

export function IcaapPillar2ComputeToJSONTyped(
  value?: IcaapPillar2Compute | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    base_revision_no: value["baseRevisionNo"],
    manual_inputs: IcaapPillar2ComputeManualInputsToJSON(value["manualInputs"]),
    reason: value["reason"],
  };
}
