/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WorkingUpdatedAt } from "./WorkingUpdatedAt";
import {
  WorkingUpdatedAtFromJSON,
  WorkingUpdatedAtFromJSONTyped,
  WorkingUpdatedAtToJSON,
  WorkingUpdatedAtToJSONTyped,
} from "./WorkingUpdatedAt";
import type { CommittedVersionNo } from "./CommittedVersionNo";
import {
  CommittedVersionNoFromJSON,
  CommittedVersionNoFromJSONTyped,
  CommittedVersionNoToJSON,
  CommittedVersionNoToJSONTyped,
} from "./CommittedVersionNo";

/**
 *
 * @export
 * @interface IcaapSectionSummaryRead
 */
export interface IcaapSectionSummaryRead {
  /**
   *
   * @type {CommittedVersionNo}
   * @memberof IcaapSectionSummaryRead
   */
  committedVersionNo?: CommittedVersionNo;
  /**
   *
   * @type {boolean}
   * @memberof IcaapSectionSummaryRead
   */
  hasUncommittedChanges: boolean;
  /**
   *
   * @type {string}
   * @memberof IcaapSectionSummaryRead
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof IcaapSectionSummaryRead
   */
  letter: string;
  /**
   *
   * @type {number}
   * @memberof IcaapSectionSummaryRead
   */
  order: number;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof IcaapSectionSummaryRead
   */
  requirementCounts: { [key: string]: number };
  /**
   *
   * @type {string}
   * @memberof IcaapSectionSummaryRead
   */
  sourceStatus: string;
  /**
   *
   * @type {string}
   * @memberof IcaapSectionSummaryRead
   */
  title: string;
  /**
   *
   * @type {WorkingUpdatedAt}
   * @memberof IcaapSectionSummaryRead
   */
  workingUpdatedAt?: WorkingUpdatedAt;
}

/**
 * Check if a given object implements the IcaapSectionSummaryRead interface.
 */
export function instanceOfIcaapSectionSummaryRead(
  value: object,
): value is IcaapSectionSummaryRead {
  if (
    !("hasUncommittedChanges" in value) ||
    value["hasUncommittedChanges"] === undefined
  )
    return false;
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("letter" in value) || value["letter"] === undefined) return false;
  if (!("order" in value) || value["order"] === undefined) return false;
  if (
    !("requirementCounts" in value) ||
    value["requirementCounts"] === undefined
  )
    return false;
  if (!("sourceStatus" in value) || value["sourceStatus"] === undefined)
    return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  return true;
}

export function IcaapSectionSummaryReadFromJSON(
  json: any,
): IcaapSectionSummaryRead {
  return IcaapSectionSummaryReadFromJSONTyped(json, false);
}

export function IcaapSectionSummaryReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapSectionSummaryRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    committedVersionNo:
      json["committed_version_no"] == null
        ? undefined
        : CommittedVersionNoFromJSON(json["committed_version_no"]),
    hasUncommittedChanges: json["has_uncommitted_changes"],
    key: json["key"],
    letter: json["letter"],
    order: json["order"],
    requirementCounts: json["requirement_counts"],
    sourceStatus: json["source_status"],
    title: json["title"],
    workingUpdatedAt:
      json["working_updated_at"] == null
        ? undefined
        : WorkingUpdatedAtFromJSON(json["working_updated_at"]),
  };
}

export function IcaapSectionSummaryReadToJSON(
  json: any,
): IcaapSectionSummaryRead {
  return IcaapSectionSummaryReadToJSONTyped(json, false);
}

export function IcaapSectionSummaryReadToJSONTyped(
  value?: IcaapSectionSummaryRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    committed_version_no: CommittedVersionNoToJSON(value["committedVersionNo"]),
    has_uncommitted_changes: value["hasUncommittedChanges"],
    key: value["key"],
    letter: value["letter"],
    order: value["order"],
    requirement_counts: value["requirementCounts"],
    source_status: value["sourceStatus"],
    title: value["title"],
    working_updated_at: WorkingUpdatedAtToJSON(value["workingUpdatedAt"]),
  };
}
