/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IcaapReviewStatus = {
  Draft: "draft",
  Finalised: "finalised",
  Superseded: "superseded",
} as const;
export type IcaapReviewStatus =
  (typeof IcaapReviewStatus)[keyof typeof IcaapReviewStatus];

export function instanceOfIcaapReviewStatus(value: any): boolean {
  for (const key in IcaapReviewStatus) {
    if (Object.prototype.hasOwnProperty.call(IcaapReviewStatus, key)) {
      if (IcaapReviewStatus[key as keyof typeof IcaapReviewStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function IcaapReviewStatusFromJSON(json: any): IcaapReviewStatus {
  return IcaapReviewStatusFromJSONTyped(json, false);
}

export function IcaapReviewStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapReviewStatus {
  return json as IcaapReviewStatus;
}

export function IcaapReviewStatusToJSON(value?: IcaapReviewStatus | null): any {
  return value as any;
}

export function IcaapReviewStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): IcaapReviewStatus {
  return value as IcaapReviewStatus;
}
