/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { EvidenceReference } from "./EvidenceReference";
import {
  EvidenceReferenceFromJSON,
  EvidenceReferenceFromJSONTyped,
  EvidenceReferenceToJSON,
  EvidenceReferenceToJSONTyped,
} from "./EvidenceReference";
import type { EvidenceAttachmentIds } from "./EvidenceAttachmentIds";
import {
  EvidenceAttachmentIdsFromJSON,
  EvidenceAttachmentIdsFromJSONTyped,
  EvidenceAttachmentIdsToJSON,
  EvidenceAttachmentIdsToJSONTyped,
} from "./EvidenceAttachmentIds";
import type { IcaapPillar2ItemUpdateSource } from "./IcaapPillar2ItemUpdateSource";
import {
  IcaapPillar2ItemUpdateSourceFromJSON,
  IcaapPillar2ItemUpdateSourceFromJSONTyped,
  IcaapPillar2ItemUpdateSourceToJSON,
  IcaapPillar2ItemUpdateSourceToJSONTyped,
} from "./IcaapPillar2ItemUpdateSource";
import type { ZeroAmountJustification1 } from "./ZeroAmountJustification1";
import {
  ZeroAmountJustification1FromJSON,
  ZeroAmountJustification1FromJSONTyped,
  ZeroAmountJustification1ToJSON,
  ZeroAmountJustification1ToJSONTyped,
} from "./ZeroAmountJustification1";
import type { BasisValue2 } from "./BasisValue2";
import {
  BasisValue2FromJSON,
  BasisValue2FromJSONTyped,
  BasisValue2ToJSON,
  BasisValue2ToJSONTyped,
} from "./BasisValue2";
import type { IcaapPillar2ItemReadBasis } from "./IcaapPillar2ItemReadBasis";
import {
  IcaapPillar2ItemReadBasisFromJSON,
  IcaapPillar2ItemReadBasisFromJSONTyped,
  IcaapPillar2ItemReadBasisToJSON,
  IcaapPillar2ItemReadBasisToJSONTyped,
} from "./IcaapPillar2ItemReadBasis";
import type { ScenarioDefinition } from "./ScenarioDefinition";
import {
  ScenarioDefinitionFromJSON,
  ScenarioDefinitionFromJSONTyped,
  ScenarioDefinitionToJSON,
  ScenarioDefinitionToJSONTyped,
} from "./ScenarioDefinition";
import type { BaselineAmount1 } from "./BaselineAmount1";
import {
  BaselineAmount1FromJSON,
  BaselineAmount1FromJSONTyped,
  BaselineAmount1ToJSON,
  BaselineAmount1ToJSONTyped,
} from "./BaselineAmount1";
import type { IcaapPillar2ItemUpdateInputMode } from "./IcaapPillar2ItemUpdateInputMode";
import {
  IcaapPillar2ItemUpdateInputModeFromJSON,
  IcaapPillar2ItemUpdateInputModeFromJSONTyped,
  IcaapPillar2ItemUpdateInputModeToJSON,
  IcaapPillar2ItemUpdateInputModeToJSONTyped,
} from "./IcaapPillar2ItemUpdateInputMode";
import type { Method } from "./Method";
import {
  MethodFromJSON,
  MethodFromJSONTyped,
  MethodToJSON,
  MethodToJSONTyped,
} from "./Method";
import type { Rationale2 } from "./Rationale2";
import {
  Rationale2FromJSON,
  Rationale2FromJSONTyped,
  Rationale2ToJSON,
  Rationale2ToJSONTyped,
} from "./Rationale2";
import type { StressedAmount1 } from "./StressedAmount1";
import {
  StressedAmount1FromJSON,
  StressedAmount1FromJSONTyped,
  StressedAmount1ToJSON,
  StressedAmount1ToJSONTyped,
} from "./StressedAmount1";

/**
 *
 * @export
 * @interface IcaapPillar2ItemUpdate
 */
export interface IcaapPillar2ItemUpdate {
  /**
   *
   * @type {number}
   * @memberof IcaapPillar2ItemUpdate
   */
  baseRevisionNo: number;
  /**
   *
   * @type {BaselineAmount1}
   * @memberof IcaapPillar2ItemUpdate
   */
  baselineAmount?: BaselineAmount1;
  /**
   *
   * @type {IcaapPillar2ItemReadBasis}
   * @memberof IcaapPillar2ItemUpdate
   */
  basis?: IcaapPillar2ItemReadBasis;
  /**
   *
   * @type {BasisValue2}
   * @memberof IcaapPillar2ItemUpdate
   */
  basisValue?: BasisValue2;
  /**
   *
   * @type {EvidenceAttachmentIds}
   * @memberof IcaapPillar2ItemUpdate
   */
  evidenceAttachmentIds?: EvidenceAttachmentIds;
  /**
   *
   * @type {EvidenceReference}
   * @memberof IcaapPillar2ItemUpdate
   */
  evidenceReference?: EvidenceReference;
  /**
   *
   * @type {IcaapPillar2ItemUpdateInputMode}
   * @memberof IcaapPillar2ItemUpdate
   */
  inputMode?: IcaapPillar2ItemUpdateInputMode;
  /**
   *
   * @type {Method}
   * @memberof IcaapPillar2ItemUpdate
   */
  method?: Method;
  /**
   *
   * @type {Rationale2}
   * @memberof IcaapPillar2ItemUpdate
   */
  rationale?: Rationale2;
  /**
   *
   * @type {string}
   * @memberof IcaapPillar2ItemUpdate
   */
  reason: string;
  /**
   *
   * @type {ScenarioDefinition}
   * @memberof IcaapPillar2ItemUpdate
   */
  scenarioDefinition?: ScenarioDefinition;
  /**
   *
   * @type {IcaapPillar2ItemUpdateSource}
   * @memberof IcaapPillar2ItemUpdate
   */
  source?: IcaapPillar2ItemUpdateSource;
  /**
   *
   * @type {StressedAmount1}
   * @memberof IcaapPillar2ItemUpdate
   */
  stressedAmount?: StressedAmount1;
  /**
   *
   * @type {boolean}
   * @memberof IcaapPillar2ItemUpdate
   */
  stressedSameAsBaseline?: boolean;
  /**
   *
   * @type {ZeroAmountJustification1}
   * @memberof IcaapPillar2ItemUpdate
   */
  zeroAmountJustification?: ZeroAmountJustification1;
}

/**
 * Check if a given object implements the IcaapPillar2ItemUpdate interface.
 */
export function instanceOfIcaapPillar2ItemUpdate(
  value: object,
): value is IcaapPillar2ItemUpdate {
  if (!("baseRevisionNo" in value) || value["baseRevisionNo"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function IcaapPillar2ItemUpdateFromJSON(
  json: any,
): IcaapPillar2ItemUpdate {
  return IcaapPillar2ItemUpdateFromJSONTyped(json, false);
}

export function IcaapPillar2ItemUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapPillar2ItemUpdate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    baseRevisionNo: json["base_revision_no"],
    baselineAmount:
      json["baseline_amount"] == null
        ? undefined
        : BaselineAmount1FromJSON(json["baseline_amount"]),
    basis:
      json["basis"] == null
        ? undefined
        : IcaapPillar2ItemReadBasisFromJSON(json["basis"]),
    basisValue:
      json["basis_value"] == null
        ? undefined
        : BasisValue2FromJSON(json["basis_value"]),
    evidenceAttachmentIds:
      json["evidence_attachment_ids"] == null
        ? undefined
        : EvidenceAttachmentIdsFromJSON(json["evidence_attachment_ids"]),
    evidenceReference:
      json["evidence_reference"] == null
        ? undefined
        : EvidenceReferenceFromJSON(json["evidence_reference"]),
    inputMode:
      json["input_mode"] == null
        ? undefined
        : IcaapPillar2ItemUpdateInputModeFromJSON(json["input_mode"]),
    method: json["method"] == null ? undefined : MethodFromJSON(json["method"]),
    rationale:
      json["rationale"] == null
        ? undefined
        : Rationale2FromJSON(json["rationale"]),
    reason: json["reason"],
    scenarioDefinition:
      json["scenario_definition"] == null
        ? undefined
        : ScenarioDefinitionFromJSON(json["scenario_definition"]),
    source:
      json["source"] == null
        ? undefined
        : IcaapPillar2ItemUpdateSourceFromJSON(json["source"]),
    stressedAmount:
      json["stressed_amount"] == null
        ? undefined
        : StressedAmount1FromJSON(json["stressed_amount"]),
    stressedSameAsBaseline:
      json["stressed_same_as_baseline"] == null
        ? undefined
        : json["stressed_same_as_baseline"],
    zeroAmountJustification:
      json["zero_amount_justification"] == null
        ? undefined
        : ZeroAmountJustification1FromJSON(json["zero_amount_justification"]),
  };
}

export function IcaapPillar2ItemUpdateToJSON(
  json: any,
): IcaapPillar2ItemUpdate {
  return IcaapPillar2ItemUpdateToJSONTyped(json, false);
}

export function IcaapPillar2ItemUpdateToJSONTyped(
  value?: IcaapPillar2ItemUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    base_revision_no: value["baseRevisionNo"],
    baseline_amount: BaselineAmount1ToJSON(value["baselineAmount"]),
    basis: IcaapPillar2ItemReadBasisToJSON(value["basis"]),
    basis_value: BasisValue2ToJSON(value["basisValue"]),
    evidence_attachment_ids: EvidenceAttachmentIdsToJSON(
      value["evidenceAttachmentIds"],
    ),
    evidence_reference: EvidenceReferenceToJSON(value["evidenceReference"]),
    input_mode: IcaapPillar2ItemUpdateInputModeToJSON(value["inputMode"]),
    method: MethodToJSON(value["method"]),
    rationale: Rationale2ToJSON(value["rationale"]),
    reason: value["reason"],
    scenario_definition: ScenarioDefinitionToJSON(value["scenarioDefinition"]),
    source: IcaapPillar2ItemUpdateSourceToJSON(value["source"]),
    stressed_amount: StressedAmount1ToJSON(value["stressedAmount"]),
    stressed_same_as_baseline: value["stressedSameAsBaseline"],
    zero_amount_justification: ZeroAmountJustification1ToJSON(
      value["zeroAmountJustification"],
    ),
  };
}
