/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IcaapMaterialityLevelRead
 */
export interface IcaapMaterialityLevelRead {
  /**
   *
   * @type {string}
   * @memberof IcaapMaterialityLevelRead
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof IcaapMaterialityLevelRead
   */
  label: string;
  /**
   *
   * @type {number}
   * @memberof IcaapMaterialityLevelRead
   */
  score: number;
}

/**
 * Check if a given object implements the IcaapMaterialityLevelRead interface.
 */
export function instanceOfIcaapMaterialityLevelRead(
  value: object,
): value is IcaapMaterialityLevelRead {
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("score" in value) || value["score"] === undefined) return false;
  return true;
}

export function IcaapMaterialityLevelReadFromJSON(
  json: any,
): IcaapMaterialityLevelRead {
  return IcaapMaterialityLevelReadFromJSONTyped(json, false);
}

export function IcaapMaterialityLevelReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapMaterialityLevelRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    key: json["key"],
    label: json["label"],
    score: json["score"],
  };
}

export function IcaapMaterialityLevelReadToJSON(
  json: any,
): IcaapMaterialityLevelRead {
  return IcaapMaterialityLevelReadToJSONTyped(json, false);
}

export function IcaapMaterialityLevelReadToJSONTyped(
  value?: IcaapMaterialityLevelRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value["key"],
    label: value["label"],
    score: value["score"],
  };
}
