/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IcaapRiskRead } from "./IcaapRiskRead";
import {
  IcaapRiskReadFromJSON,
  IcaapRiskReadFromJSONTyped,
  IcaapRiskReadToJSON,
  IcaapRiskReadToJSONTyped,
} from "./IcaapRiskRead";
import type { IcaapMaterialityMatrixRead } from "./IcaapMaterialityMatrixRead";
import {
  IcaapMaterialityMatrixReadFromJSON,
  IcaapMaterialityMatrixReadFromJSONTyped,
  IcaapMaterialityMatrixReadToJSON,
  IcaapMaterialityMatrixReadToJSONTyped,
} from "./IcaapMaterialityMatrixRead";
import type { IcaapRiskRegisterSummaryRead } from "./IcaapRiskRegisterSummaryRead";
import {
  IcaapRiskRegisterSummaryReadFromJSON,
  IcaapRiskRegisterSummaryReadFromJSONTyped,
  IcaapRiskRegisterSummaryReadToJSON,
  IcaapRiskRegisterSummaryReadToJSONTyped,
} from "./IcaapRiskRegisterSummaryRead";

/**
 *
 * @export
 * @interface IcaapRiskRegisterRead
 */
export interface IcaapRiskRegisterRead {
  /**
   *
   * @type {string}
   * @memberof IcaapRiskRegisterRead
   */
  cycleId: string;
  /**
   *
   * @type {IcaapMaterialityMatrixRead}
   * @memberof IcaapRiskRegisterRead
   */
  matrix: IcaapMaterialityMatrixRead;
  /**
   *
   * @type {Array<IcaapRiskRead>}
   * @memberof IcaapRiskRegisterRead
   */
  risks: Array<IcaapRiskRead>;
  /**
   *
   * @type {IcaapRiskRegisterSummaryRead}
   * @memberof IcaapRiskRegisterRead
   */
  summary: IcaapRiskRegisterSummaryRead;
}

/**
 * Check if a given object implements the IcaapRiskRegisterRead interface.
 */
export function instanceOfIcaapRiskRegisterRead(
  value: object,
): value is IcaapRiskRegisterRead {
  if (!("cycleId" in value) || value["cycleId"] === undefined) return false;
  if (!("matrix" in value) || value["matrix"] === undefined) return false;
  if (!("risks" in value) || value["risks"] === undefined) return false;
  if (!("summary" in value) || value["summary"] === undefined) return false;
  return true;
}

export function IcaapRiskRegisterReadFromJSON(
  json: any,
): IcaapRiskRegisterRead {
  return IcaapRiskRegisterReadFromJSONTyped(json, false);
}

export function IcaapRiskRegisterReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapRiskRegisterRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    cycleId: json["cycle_id"],
    matrix: IcaapMaterialityMatrixReadFromJSON(json["matrix"]),
    risks: (json["risks"] as Array<any>).map(IcaapRiskReadFromJSON),
    summary: IcaapRiskRegisterSummaryReadFromJSON(json["summary"]),
  };
}

export function IcaapRiskRegisterReadToJSON(json: any): IcaapRiskRegisterRead {
  return IcaapRiskRegisterReadToJSONTyped(json, false);
}

export function IcaapRiskRegisterReadToJSONTyped(
  value?: IcaapRiskRegisterRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cycle_id: value["cycleId"],
    matrix: IcaapMaterialityMatrixReadToJSON(value["matrix"]),
    risks: (value["risks"] as Array<any>).map(IcaapRiskReadToJSON),
    summary: IcaapRiskRegisterSummaryReadToJSON(value["summary"]),
  };
}
