/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface IcaapMaterialityBandRead
 */
export interface IcaapMaterialityBandRead {
  /**
   *
   * @type {string}
   * @memberof IcaapMaterialityBandRead
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof IcaapMaterialityBandRead
   */
  label: string;
  /**
   *
   * @type {number}
   * @memberof IcaapMaterialityBandRead
   */
  maxScore: number;
  /**
   *
   * @type {number}
   * @memberof IcaapMaterialityBandRead
   */
  minScore: number;
}

/**
 * Check if a given object implements the IcaapMaterialityBandRead interface.
 */
export function instanceOfIcaapMaterialityBandRead(
  value: object,
): value is IcaapMaterialityBandRead {
  if (!("key" in value) || value["key"] === undefined) return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (!("maxScore" in value) || value["maxScore"] === undefined) return false;
  if (!("minScore" in value) || value["minScore"] === undefined) return false;
  return true;
}

export function IcaapMaterialityBandReadFromJSON(
  json: any,
): IcaapMaterialityBandRead {
  return IcaapMaterialityBandReadFromJSONTyped(json, false);
}

export function IcaapMaterialityBandReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapMaterialityBandRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    key: json["key"],
    label: json["label"],
    maxScore: json["max_score"],
    minScore: json["min_score"],
  };
}

export function IcaapMaterialityBandReadToJSON(
  json: any,
): IcaapMaterialityBandRead {
  return IcaapMaterialityBandReadToJSONTyped(json, false);
}

export function IcaapMaterialityBandReadToJSONTyped(
  value?: IcaapMaterialityBandRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    key: value["key"],
    label: value["label"],
    max_score: value["maxScore"],
    min_score: value["minScore"],
  };
}
