/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { IcaapFactChangeRead } from "./IcaapFactChangeRead";
import {
  IcaapFactChangeReadFromJSON,
  IcaapFactChangeReadFromJSONTyped,
  IcaapFactChangeReadToJSON,
  IcaapFactChangeReadToJSONTyped,
} from "./IcaapFactChangeRead";
import type { IcaapDataBlockRead } from "./IcaapDataBlockRead";
import {
  IcaapDataBlockReadFromJSON,
  IcaapDataBlockReadFromJSONTyped,
  IcaapDataBlockReadToJSON,
  IcaapDataBlockReadToJSONTyped,
} from "./IcaapDataBlockRead";
import type { Reason } from "./Reason";
import {
  ReasonFromJSON,
  ReasonFromJSONTyped,
  ReasonToJSON,
  ReasonToJSONTyped,
} from "./Reason";

/**
 *
 * @export
 * @interface IcaapBlockRefreshRead
 */
export interface IcaapBlockRefreshRead {
  /**
   *
   * @type {IcaapDataBlockRead}
   * @memberof IcaapBlockRefreshRead
   */
  block: IcaapDataBlockRead;
  /**
   *
   * @type {Array<IcaapFactChangeRead>}
   * @memberof IcaapBlockRefreshRead
   */
  changedFacts: Array<IcaapFactChangeRead>;
  /**
   *
   * @type {string}
   * @memberof IcaapBlockRefreshRead
   */
  outcome: IcaapBlockRefreshReadOutcomeEnum;
  /**
   *
   * @type {Reason}
   * @memberof IcaapBlockRefreshRead
   */
  reason?: Reason;
}

/**
 * @export
 */
export const IcaapBlockRefreshReadOutcomeEnum = {
  Bound: "bound",
  Unchanged: "unchanged",
  Unavailable: "unavailable",
} as const;
export type IcaapBlockRefreshReadOutcomeEnum =
  (typeof IcaapBlockRefreshReadOutcomeEnum)[keyof typeof IcaapBlockRefreshReadOutcomeEnum];

/**
 * Check if a given object implements the IcaapBlockRefreshRead interface.
 */
export function instanceOfIcaapBlockRefreshRead(
  value: object,
): value is IcaapBlockRefreshRead {
  if (!("block" in value) || value["block"] === undefined) return false;
  if (!("changedFacts" in value) || value["changedFacts"] === undefined)
    return false;
  if (!("outcome" in value) || value["outcome"] === undefined) return false;
  return true;
}

export function IcaapBlockRefreshReadFromJSON(
  json: any,
): IcaapBlockRefreshRead {
  return IcaapBlockRefreshReadFromJSONTyped(json, false);
}

export function IcaapBlockRefreshReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapBlockRefreshRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    block: IcaapDataBlockReadFromJSON(json["block"]),
    changedFacts: (json["changed_facts"] as Array<any>).map(
      IcaapFactChangeReadFromJSON,
    ),
    outcome: json["outcome"],
    reason: json["reason"] == null ? undefined : ReasonFromJSON(json["reason"]),
  };
}

export function IcaapBlockRefreshReadToJSON(json: any): IcaapBlockRefreshRead {
  return IcaapBlockRefreshReadToJSONTyped(json, false);
}

export function IcaapBlockRefreshReadToJSONTyped(
  value?: IcaapBlockRefreshRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    block: IcaapDataBlockReadToJSON(value["block"]),
    changed_facts: (value["changedFacts"] as Array<any>).map(
      IcaapFactChangeReadToJSON,
    ),
    outcome: value["outcome"],
    reason: ReasonToJSON(value["reason"]),
  };
}
