/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IcaapRiskTreatment = {
  Undecided: "undecided",
  Quantified: "quantified",
  FullyCoveredByPillar1: "fully_covered_by_pillar1",
  NotCapitalised: "not_capitalised",
  NotMaterial: "not_material",
} as const;
export type IcaapRiskTreatment =
  (typeof IcaapRiskTreatment)[keyof typeof IcaapRiskTreatment];

export function instanceOfIcaapRiskTreatment(value: any): boolean {
  for (const key in IcaapRiskTreatment) {
    if (Object.prototype.hasOwnProperty.call(IcaapRiskTreatment, key)) {
      if (
        IcaapRiskTreatment[key as keyof typeof IcaapRiskTreatment] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function IcaapRiskTreatmentFromJSON(json: any): IcaapRiskTreatment {
  return IcaapRiskTreatmentFromJSONTyped(json, false);
}

export function IcaapRiskTreatmentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapRiskTreatment {
  return json as IcaapRiskTreatment;
}

export function IcaapRiskTreatmentToJSON(
  value?: IcaapRiskTreatment | null,
): any {
  return value as any;
}

export function IcaapRiskTreatmentToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): IcaapRiskTreatment {
  return value as IcaapRiskTreatment;
}
