/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const IcaapChallengeTarget = {
  Cycle: "cycle",
  Section: "section",
  Risk: "risk",
  AppetiteMetric: "appetite_metric",
  Pillar2Item: "pillar2_item",
  Reconciliation: "reconciliation",
  Stress: "stress",
} as const;
export type IcaapChallengeTarget =
  (typeof IcaapChallengeTarget)[keyof typeof IcaapChallengeTarget];

export function instanceOfIcaapChallengeTarget(value: any): boolean {
  for (const key in IcaapChallengeTarget) {
    if (Object.prototype.hasOwnProperty.call(IcaapChallengeTarget, key)) {
      if (
        IcaapChallengeTarget[key as keyof typeof IcaapChallengeTarget] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function IcaapChallengeTargetFromJSON(json: any): IcaapChallengeTarget {
  return IcaapChallengeTargetFromJSONTyped(json, false);
}

export function IcaapChallengeTargetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapChallengeTarget {
  return json as IcaapChallengeTarget;
}

export function IcaapChallengeTargetToJSON(
  value?: IcaapChallengeTarget | null,
): any {
  return value as any;
}

export function IcaapChallengeTargetToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): IcaapChallengeTarget {
  return value as IcaapChallengeTarget;
}
