/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IcaapAppetiteValueSource } from "./IcaapAppetiteValueSource";
import {
  IcaapAppetiteValueSourceFromJSON,
  IcaapAppetiteValueSourceFromJSONTyped,
  IcaapAppetiteValueSourceToJSON,
  IcaapAppetiteValueSourceToJSONTyped,
} from "./IcaapAppetiteValueSource";

/**
 *
 * @export
 * @interface IcaapAppetiteMetricCreateValueSource
 */
export type IcaapAppetiteMetricCreateValueSource =
  "block_fact" | "manual" | null;

/**
 * Check if a given object implements the IcaapAppetiteMetricCreateValueSource interface.
 */
export function instanceOfIcaapAppetiteMetricCreateValueSource(
  value: unknown,
): value is IcaapAppetiteMetricCreateValueSource {
  return (
    ["block_fact", "manual"].indexOf(value as never) !== -1 || value === null
  );
}

export function IcaapAppetiteMetricCreateValueSourceFromJSON(
  json: any,
): IcaapAppetiteMetricCreateValueSource {
  return IcaapAppetiteMetricCreateValueSourceFromJSONTyped(json, false);
}

export function IcaapAppetiteMetricCreateValueSourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapAppetiteMetricCreateValueSource {
  return json;
}

export function IcaapAppetiteMetricCreateValueSourceToJSON(
  json: any,
): IcaapAppetiteMetricCreateValueSource {
  return IcaapAppetiteMetricCreateValueSourceToJSONTyped(json, false);
}

export function IcaapAppetiteMetricCreateValueSourceToJSONTyped(
  value?: IcaapAppetiteMetricCreateValueSource | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
