/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AppliesWhen } from "./AppliesWhen";
import {
  AppliesWhenFromJSON,
  AppliesWhenFromJSONTyped,
  AppliesWhenToJSON,
  AppliesWhenToJSONTyped,
} from "./AppliesWhen";
import type { IcaapCitationRead } from "./IcaapCitationRead";
import {
  IcaapCitationReadFromJSON,
  IcaapCitationReadFromJSONTyped,
  IcaapCitationReadToJSON,
  IcaapCitationReadToJSONTyped,
} from "./IcaapCitationRead";

/**
 *
 * @export
 * @interface IcaapRequirementItemRead
 */
export interface IcaapRequirementItemRead {
  /**
   *
   * @type {AppliesWhen}
   * @memberof IcaapRequirementItemRead
   */
  appliesWhen?: AppliesWhen;
  /**
   *
   * @type {Array<IcaapCitationRead>}
   * @memberof IcaapRequirementItemRead
   */
  citations: Array<IcaapCitationRead>;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapRequirementItemRead
   */
  evidence: Array<string>;
  /**
   *
   * @type {string}
   * @memberof IcaapRequirementItemRead
   */
  id: string;
  /**
   *
   * @type {Array<string>}
   * @memberof IcaapRequirementItemRead
   */
  paramRefs?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof IcaapRequirementItemRead
   */
  text: string;
  /**
   *
   * @type {boolean}
   * @memberof IcaapRequirementItemRead
   */
  waivable: boolean;
}

/**
 * Check if a given object implements the IcaapRequirementItemRead interface.
 */
export function instanceOfIcaapRequirementItemRead(
  value: object,
): value is IcaapRequirementItemRead {
  if (!("citations" in value) || value["citations"] === undefined) return false;
  if (!("evidence" in value) || value["evidence"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("text" in value) || value["text"] === undefined) return false;
  if (!("waivable" in value) || value["waivable"] === undefined) return false;
  return true;
}

export function IcaapRequirementItemReadFromJSON(
  json: any,
): IcaapRequirementItemRead {
  return IcaapRequirementItemReadFromJSONTyped(json, false);
}

export function IcaapRequirementItemReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IcaapRequirementItemRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    appliesWhen:
      json["applies_when"] == null
        ? undefined
        : AppliesWhenFromJSON(json["applies_when"]),
    citations: (json["citations"] as Array<any>).map(IcaapCitationReadFromJSON),
    evidence: json["evidence"],
    id: json["id"],
    paramRefs: json["param_refs"] == null ? undefined : json["param_refs"],
    text: json["text"],
    waivable: json["waivable"],
  };
}

export function IcaapRequirementItemReadToJSON(
  json: any,
): IcaapRequirementItemRead {
  return IcaapRequirementItemReadToJSONTyped(json, false);
}

export function IcaapRequirementItemReadToJSONTyped(
  value?: IcaapRequirementItemRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    applies_when: AppliesWhenToJSON(value["appliesWhen"]),
    citations: (value["citations"] as Array<any>).map(IcaapCitationReadToJSON),
    evidence: value["evidence"],
    id: value["id"],
    param_refs: value["paramRefs"],
    text: value["text"],
    waivable: value["waivable"],
  };
}
