/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ImageWidth
 */
export type ImageWidth = number | null;

/**
 * Check if a given object implements the ImageWidth interface.
 */
export function instanceOfImageWidth(value: unknown): value is ImageWidth {
  return typeof value === "number" || value === null;
}

export function ImageWidthFromJSON(json: any): ImageWidth {
  return ImageWidthFromJSONTyped(json, false);
}

export function ImageWidthFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ImageWidth {
  return json;
}

export function ImageWidthToJSON(json: any): ImageWidth {
  return ImageWidthToJSONTyped(json, false);
}

export function ImageWidthToJSONTyped(
  value?: ImageWidth | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
