/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Per-source-system rollup of ingestion history for one bank.
 * @export
 * @interface IngestionSourceSummaryRead
 */
export interface IngestionSourceSummaryRead {
  /**
   *
   * @type {number}
   * @memberof IngestionSourceSummaryRead
   */
  batches: number;
  /**
   *
   * @type {Date}
   * @memberof IngestionSourceSummaryRead
   */
  lastBatchAt: Date | null;
  /**
   *
   * @type {string}
   * @memberof IngestionSourceSummaryRead
   */
  lastStatus: IngestionSourceSummaryReadLastStatusEnum | null;
  /**
   *
   * @type {number}
   * @memberof IngestionSourceSummaryRead
   */
  recordsAcceptedTotal: number;
  /**
   *
   * @type {number}
   * @memberof IngestionSourceSummaryRead
   */
  recordsWarningTotal: number;
  /**
   *
   * @type {string}
   * @memberof IngestionSourceSummaryRead
   */
  sourceSystem: IngestionSourceSummaryReadSourceSystemEnum;
}

/**
 * @export
 */
export const IngestionSourceSummaryReadLastStatusEnum = {
  Created: "created",
  Extracting: "extracting",
  Translating: "translating",
  Validating: "validating",
  Accepted: "accepted",
  AcceptedWithWarnings: "accepted_with_warnings",
  Rejected: "rejected",
  Failed: "failed",
} as const;
export type IngestionSourceSummaryReadLastStatusEnum =
  (typeof IngestionSourceSummaryReadLastStatusEnum)[keyof typeof IngestionSourceSummaryReadLastStatusEnum];

/**
 * @export
 */
export const IngestionSourceSummaryReadSourceSystemEnum = {
  ExcelCsv: "EXCEL_CSV",
  T24: "T24",
  Finacle: "FINACLE",
  Flexcube: "FLEXCUBE",
  DbDirect: "DB_DIRECT",
  SftpDrop: "SFTP_DROP",
  ApiGeneric: "API_GENERIC",
  ApiPush: "API_PUSH",
  Manual: "MANUAL",
} as const;
export type IngestionSourceSummaryReadSourceSystemEnum =
  (typeof IngestionSourceSummaryReadSourceSystemEnum)[keyof typeof IngestionSourceSummaryReadSourceSystemEnum];

/**
 * Check if a given object implements the IngestionSourceSummaryRead interface.
 */
export function instanceOfIngestionSourceSummaryRead(
  value: object,
): value is IngestionSourceSummaryRead {
  if (!("batches" in value) || value["batches"] === undefined) return false;
  if (!("lastBatchAt" in value) || value["lastBatchAt"] === undefined)
    return false;
  if (!("lastStatus" in value) || value["lastStatus"] === undefined)
    return false;
  if (
    !("recordsAcceptedTotal" in value) ||
    value["recordsAcceptedTotal"] === undefined
  )
    return false;
  if (
    !("recordsWarningTotal" in value) ||
    value["recordsWarningTotal"] === undefined
  )
    return false;
  if (!("sourceSystem" in value) || value["sourceSystem"] === undefined)
    return false;
  return true;
}

export function IngestionSourceSummaryReadFromJSON(
  json: any,
): IngestionSourceSummaryRead {
  return IngestionSourceSummaryReadFromJSONTyped(json, false);
}

export function IngestionSourceSummaryReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IngestionSourceSummaryRead {
  if (json == null) {
    return json;
  }
  return {
    batches: json["batches"],
    lastBatchAt:
      json["last_batch_at"] == null ? null : new Date(json["last_batch_at"]),
    lastStatus: json["last_status"],
    recordsAcceptedTotal: json["records_accepted_total"],
    recordsWarningTotal: json["records_warning_total"],
    sourceSystem: json["source_system"],
  };
}

export function IngestionSourceSummaryReadToJSON(
  json: any,
): IngestionSourceSummaryRead {
  return IngestionSourceSummaryReadToJSONTyped(json, false);
}

export function IngestionSourceSummaryReadToJSONTyped(
  value?: IngestionSourceSummaryRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    batches: value["batches"],
    last_batch_at:
      value["lastBatchAt"] == null
        ? null
        : (value["lastBatchAt"] as any).toISOString(),
    last_status: value["lastStatus"],
    records_accepted_total: value["recordsAcceptedTotal"],
    records_warning_total: value["recordsWarningTotal"],
    source_system: value["sourceSystem"],
  };
}
