/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RegistrationNumber1 } from "./RegistrationNumber1";
import {
  RegistrationNumber1FromJSON,
  RegistrationNumber1FromJSONTyped,
  RegistrationNumber1ToJSON,
  RegistrationNumber1ToJSONTyped,
} from "./RegistrationNumber1";
import type { OwnershipForeignPct1 } from "./OwnershipForeignPct1";
import {
  OwnershipForeignPct1FromJSON,
  OwnershipForeignPct1FromJSONTyped,
  OwnershipForeignPct1ToJSON,
  OwnershipForeignPct1ToJSONTyped,
} from "./OwnershipForeignPct1";
import type { OwnershipLocalPct1 } from "./OwnershipLocalPct1";
import {
  OwnershipLocalPct1FromJSON,
  OwnershipLocalPct1FromJSONTyped,
  OwnershipLocalPct1ToJSON,
  OwnershipLocalPct1ToJSONTyped,
} from "./OwnershipLocalPct1";
import type { ExchangeName1 } from "./ExchangeName1";
import {
  ExchangeName1FromJSON,
  ExchangeName1FromJSONTyped,
  ExchangeName1ToJSON,
  ExchangeName1ToJSONTyped,
} from "./ExchangeName1";
import type { InstitutionProfileRead } from "./InstitutionProfileRead";
import {
  InstitutionProfileReadFromJSON,
  InstitutionProfileReadFromJSONTyped,
  InstitutionProfileReadToJSON,
  InstitutionProfileReadToJSONTyped,
} from "./InstitutionProfileRead";
import type { ApprovedCapital1 } from "./ApprovedCapital1";
import {
  ApprovedCapital1FromJSON,
  ApprovedCapital1FromJSONTyped,
  ApprovedCapital1ToJSON,
  ApprovedCapital1ToJSONTyped,
} from "./ApprovedCapital1";
import type { Isin1 } from "./Isin1";
import {
  Isin1FromJSON,
  Isin1FromJSONTyped,
  Isin1ToJSON,
  Isin1ToJSONTyped,
} from "./Isin1";
import type { ParentCountryCode1 } from "./ParentCountryCode1";
import {
  ParentCountryCode1FromJSON,
  ParentCountryCode1FromJSONTyped,
  ParentCountryCode1ToJSON,
  ParentCountryCode1ToJSONTyped,
} from "./ParentCountryCode1";
import type { AuthorisationDate } from "./AuthorisationDate";
import {
  AuthorisationDateFromJSON,
  AuthorisationDateFromJSONTyped,
  AuthorisationDateToJSON,
  AuthorisationDateToJSONTyped,
} from "./AuthorisationDate";
import type { IncorporationDate } from "./IncorporationDate";
import {
  IncorporationDateFromJSON,
  IncorporationDateFromJSONTyped,
  IncorporationDateToJSON,
  IncorporationDateToJSONTyped,
} from "./IncorporationDate";
import type { OrassInstitutionCode1 } from "./OrassInstitutionCode1";
import {
  OrassInstitutionCode1FromJSON,
  OrassInstitutionCode1FromJSONTyped,
  OrassInstitutionCode1ToJSON,
  OrassInstitutionCode1ToJSONTyped,
} from "./OrassInstitutionCode1";
import type { Tin1 } from "./Tin1";
import {
  Tin1FromJSON,
  Tin1FromJSONTyped,
  Tin1ToJSON,
  Tin1ToJSONTyped,
} from "./Tin1";

/**
 *
 * @export
 * @interface InstitutionProfileFullReadProfile
 */
export interface InstitutionProfileFullReadProfile {
  /**
   *
   * @type {ApprovedCapital1}
   * @memberof InstitutionProfileFullReadProfile
   */
  approvedCapital: ApprovedCapital1;
  /**
   *
   * @type {AuthorisationDate}
   * @memberof InstitutionProfileFullReadProfile
   */
  authorisationDate: AuthorisationDate;
  /**
   *
   * @type {string}
   * @memberof InstitutionProfileFullReadProfile
   */
  bankId: string;
  /**
   *
   * @type {Date}
   * @memberof InstitutionProfileFullReadProfile
   */
  createdAt: Date;
  /**
   *
   * @type {ExchangeName1}
   * @memberof InstitutionProfileFullReadProfile
   */
  exchangeName: ExchangeName1;
  /**
   *
   * @type {string}
   * @memberof InstitutionProfileFullReadProfile
   */
  id: string;
  /**
   *
   * @type {IncorporationDate}
   * @memberof InstitutionProfileFullReadProfile
   */
  incorporationDate: IncorporationDate;
  /**
   *
   * @type {string}
   * @memberof InstitutionProfileFullReadProfile
   */
  institutionType: string;
  /**
   *
   * @type {Isin1}
   * @memberof InstitutionProfileFullReadProfile
   */
  isin: Isin1;
  /**
   *
   * @type {string}
   * @memberof InstitutionProfileFullReadProfile
   */
  legalEntityStructure: string;
  /**
   *
   * @type {OrassInstitutionCode1}
   * @memberof InstitutionProfileFullReadProfile
   */
  orassInstitutionCode: OrassInstitutionCode1;
  /**
   *
   * @type {OwnershipForeignPct1}
   * @memberof InstitutionProfileFullReadProfile
   */
  ownershipForeignPct: OwnershipForeignPct1;
  /**
   *
   * @type {OwnershipLocalPct1}
   * @memberof InstitutionProfileFullReadProfile
   */
  ownershipLocalPct: OwnershipLocalPct1;
  /**
   *
   * @type {ParentCountryCode1}
   * @memberof InstitutionProfileFullReadProfile
   */
  parentCountryCode: ParentCountryCode1;
  /**
   *
   * @type {RegistrationNumber1}
   * @memberof InstitutionProfileFullReadProfile
   */
  registrationNumber: RegistrationNumber1;
  /**
   *
   * @type {Tin1}
   * @memberof InstitutionProfileFullReadProfile
   */
  tin: Tin1;
  /**
   *
   * @type {boolean}
   * @memberof InstitutionProfileFullReadProfile
   */
  tradedOnExchange: boolean;
  /**
   *
   * @type {Date}
   * @memberof InstitutionProfileFullReadProfile
   */
  updatedAt: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof InstitutionProfileFullReadProfile
   */
  warnings: Array<string>;
}

/**
 * Check if a given object implements the InstitutionProfileFullReadProfile interface.
 */
export function instanceOfInstitutionProfileFullReadProfile(
  value: object,
): value is InstitutionProfileFullReadProfile {
  if (!("approvedCapital" in value) || value["approvedCapital"] === undefined)
    return false;
  if (
    !("authorisationDate" in value) ||
    value["authorisationDate"] === undefined
  )
    return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("exchangeName" in value) || value["exchangeName"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (
    !("incorporationDate" in value) ||
    value["incorporationDate"] === undefined
  )
    return false;
  if (!("institutionType" in value) || value["institutionType"] === undefined)
    return false;
  if (!("isin" in value) || value["isin"] === undefined) return false;
  if (
    !("legalEntityStructure" in value) ||
    value["legalEntityStructure"] === undefined
  )
    return false;
  if (
    !("orassInstitutionCode" in value) ||
    value["orassInstitutionCode"] === undefined
  )
    return false;
  if (
    !("ownershipForeignPct" in value) ||
    value["ownershipForeignPct"] === undefined
  )
    return false;
  if (
    !("ownershipLocalPct" in value) ||
    value["ownershipLocalPct"] === undefined
  )
    return false;
  if (
    !("parentCountryCode" in value) ||
    value["parentCountryCode"] === undefined
  )
    return false;
  if (
    !("registrationNumber" in value) ||
    value["registrationNumber"] === undefined
  )
    return false;
  if (!("tin" in value) || value["tin"] === undefined) return false;
  if (!("tradedOnExchange" in value) || value["tradedOnExchange"] === undefined)
    return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("warnings" in value) || value["warnings"] === undefined) return false;
  return true;
}

export function InstitutionProfileFullReadProfileFromJSON(
  json: any,
): InstitutionProfileFullReadProfile {
  return InstitutionProfileFullReadProfileFromJSONTyped(json, false);
}

export function InstitutionProfileFullReadProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): InstitutionProfileFullReadProfile {
  if (json == null) {
    return json;
  }
  return {
    approvedCapital: ApprovedCapital1FromJSON(json["approved_capital"]),
    authorisationDate: AuthorisationDateFromJSON(json["authorisation_date"]),
    bankId: json["bank_id"],
    createdAt: new Date(json["created_at"]),
    exchangeName: ExchangeName1FromJSON(json["exchange_name"]),
    id: json["id"],
    incorporationDate: IncorporationDateFromJSON(json["incorporation_date"]),
    institutionType: json["institution_type"],
    isin: Isin1FromJSON(json["isin"]),
    legalEntityStructure: json["legal_entity_structure"],
    orassInstitutionCode: OrassInstitutionCode1FromJSON(
      json["orass_institution_code"],
    ),
    ownershipForeignPct: OwnershipForeignPct1FromJSON(
      json["ownership_foreign_pct"],
    ),
    ownershipLocalPct: OwnershipLocalPct1FromJSON(json["ownership_local_pct"]),
    parentCountryCode: ParentCountryCode1FromJSON(json["parent_country_code"]),
    registrationNumber: RegistrationNumber1FromJSON(
      json["registration_number"],
    ),
    tin: Tin1FromJSON(json["tin"]),
    tradedOnExchange: json["traded_on_exchange"],
    updatedAt: new Date(json["updated_at"]),
    warnings: json["warnings"],
  };
}

export function InstitutionProfileFullReadProfileToJSON(
  json: any,
): InstitutionProfileFullReadProfile {
  return InstitutionProfileFullReadProfileToJSONTyped(json, false);
}

export function InstitutionProfileFullReadProfileToJSONTyped(
  value?: InstitutionProfileFullReadProfile | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approved_capital: ApprovedCapital1ToJSON(value["approvedCapital"]),
    authorisation_date: AuthorisationDateToJSON(value["authorisationDate"]),
    bank_id: value["bankId"],
    created_at: value["createdAt"].toISOString(),
    exchange_name: ExchangeName1ToJSON(value["exchangeName"]),
    id: value["id"],
    incorporation_date: IncorporationDateToJSON(value["incorporationDate"]),
    institution_type: value["institutionType"],
    isin: Isin1ToJSON(value["isin"]),
    legal_entity_structure: value["legalEntityStructure"],
    orass_institution_code: OrassInstitutionCode1ToJSON(
      value["orassInstitutionCode"],
    ),
    ownership_foreign_pct: OwnershipForeignPct1ToJSON(
      value["ownershipForeignPct"],
    ),
    ownership_local_pct: OwnershipLocalPct1ToJSON(value["ownershipLocalPct"]),
    parent_country_code: ParentCountryCode1ToJSON(value["parentCountryCode"]),
    registration_number: RegistrationNumber1ToJSON(value["registrationNumber"]),
    tin: Tin1ToJSON(value["tin"]),
    traded_on_exchange: value["tradedOnExchange"],
    updated_at: value["updatedAt"].toISOString(),
    warnings: value["warnings"],
  };
}
