/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CompletedAt } from "./CompletedAt";
import {
  CompletedAtFromJSON,
  CompletedAtFromJSONTyped,
  CompletedAtToJSON,
  CompletedAtToJSONTyped,
} from "./CompletedAt";
import type { ErrorCode } from "./ErrorCode";
import {
  ErrorCodeFromJSON,
  ErrorCodeFromJSONTyped,
  ErrorCodeToJSON,
  ErrorCodeToJSONTyped,
} from "./ErrorCode";
import type { StartedAt } from "./StartedAt";
import {
  StartedAtFromJSON,
  StartedAtFromJSONTyped,
  StartedAtToJSON,
  StartedAtToJSONTyped,
} from "./StartedAt";

/**
 * One Standardised Framework run at a reporting date, whatever it did.
 *
 * A REFUSED attempt is a ``failed`` run, so it never reaches the result read
 * — and silence there is indistinguishable from "nobody has tried". This is
 * the summary that tells the two apart, and it carries the engine's own
 * sentence rather than the raw refusal code.
 * @export
 * @interface IrrbbSfAttemptRead
 */
export interface IrrbbSfAttemptRead {
  /**
   *
   * @type {CompletedAt}
   * @memberof IrrbbSfAttemptRead
   */
  completedAt?: CompletedAt;
  /**
   *
   * @type {Date}
   * @memberof IrrbbSfAttemptRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  engineVersion: string;
  /**
   *
   * @type {ErrorCode}
   * @memberof IrrbbSfAttemptRead
   */
  errorCode?: ErrorCode;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  inputHash: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  refusalStatement?: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  runId: string;
  /**
   *
   * @type {StartedAt}
   * @memberof IrrbbSfAttemptRead
   */
  startedAt?: StartedAt;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfAttemptRead
   */
  statusLabel: string;
}

/**
 * Check if a given object implements the IrrbbSfAttemptRead interface.
 */
export function instanceOfIrrbbSfAttemptRead(
  value: object,
): value is IrrbbSfAttemptRead {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("engineVersion" in value) || value["engineVersion"] === undefined)
    return false;
  if (!("inputHash" in value) || value["inputHash"] === undefined) return false;
  if (!("runId" in value) || value["runId"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("statusLabel" in value) || value["statusLabel"] === undefined)
    return false;
  return true;
}

export function IrrbbSfAttemptReadFromJSON(json: any): IrrbbSfAttemptRead {
  return IrrbbSfAttemptReadFromJSONTyped(json, false);
}

export function IrrbbSfAttemptReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IrrbbSfAttemptRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    completedAt:
      json["completed_at"] == null
        ? undefined
        : CompletedAtFromJSON(json["completed_at"]),
    createdAt: new Date(json["created_at"]),
    engineVersion: json["engine_version"],
    errorCode:
      json["error_code"] == null
        ? undefined
        : ErrorCodeFromJSON(json["error_code"]),
    inputHash: json["input_hash"],
    refusalStatement:
      json["refusal_statement"] == null ? undefined : json["refusal_statement"],
    runId: json["run_id"],
    startedAt:
      json["started_at"] == null
        ? undefined
        : StartedAtFromJSON(json["started_at"]),
    status: json["status"],
    statusLabel: json["status_label"],
  };
}

export function IrrbbSfAttemptReadToJSON(json: any): IrrbbSfAttemptRead {
  return IrrbbSfAttemptReadToJSONTyped(json, false);
}

export function IrrbbSfAttemptReadToJSONTyped(
  value?: IrrbbSfAttemptRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    completed_at: CompletedAtToJSON(value["completedAt"]),
    created_at: value["createdAt"].toISOString(),
    engine_version: value["engineVersion"],
    error_code: ErrorCodeToJSON(value["errorCode"]),
    input_hash: value["inputHash"],
    refusal_statement: value["refusalStatement"],
    run_id: value["runId"],
    started_at: StartedAtToJSON(value["startedAt"]),
    status: value["status"],
    status_label: value["statusLabel"],
  };
}
