/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * One governed input, with everything a reader needs to judge it.
 * @export
 * @interface IrrbbSfParameterRead
 */
export interface IrrbbSfParameterRead {
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  confirmationStatus: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  label: string;
  /**
   *
   * @type {boolean}
   * @memberof IrrbbSfParameterRead
   */
  pendingConfirmation: boolean;
  /**
   *
   * @type {boolean}
   * @memberof IrrbbSfParameterRead
   */
  representative: boolean;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  sourceCitation: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  statement: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  unit: string;
  /**
   *
   * @type {string}
   * @memberof IrrbbSfParameterRead
   */
  value: string;
}

/**
 * Check if a given object implements the IrrbbSfParameterRead interface.
 */
export function instanceOfIrrbbSfParameterRead(
  value: object,
): value is IrrbbSfParameterRead {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (
    !("confirmationStatus" in value) ||
    value["confirmationStatus"] === undefined
  )
    return false;
  if (!("label" in value) || value["label"] === undefined) return false;
  if (
    !("pendingConfirmation" in value) ||
    value["pendingConfirmation"] === undefined
  )
    return false;
  if (!("representative" in value) || value["representative"] === undefined)
    return false;
  if (!("sourceCitation" in value) || value["sourceCitation"] === undefined)
    return false;
  if (!("statement" in value) || value["statement"] === undefined) return false;
  if (!("unit" in value) || value["unit"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function IrrbbSfParameterReadFromJSON(json: any): IrrbbSfParameterRead {
  return IrrbbSfParameterReadFromJSONTyped(json, false);
}

export function IrrbbSfParameterReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): IrrbbSfParameterRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    code: json["code"],
    confirmationStatus: json["confirmation_status"],
    label: json["label"],
    pendingConfirmation: json["pending_confirmation"],
    representative: json["representative"],
    sourceCitation: json["source_citation"],
    statement: json["statement"],
    unit: json["unit"],
    value: json["value"],
  };
}

export function IrrbbSfParameterReadToJSON(json: any): IrrbbSfParameterRead {
  return IrrbbSfParameterReadToJSONTyped(json, false);
}

export function IrrbbSfParameterReadToJSONTyped(
  value?: IrrbbSfParameterRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    confirmation_status: value["confirmationStatus"],
    label: value["label"],
    pending_confirmation: value["pendingConfirmation"],
    representative: value["representative"],
    source_citation: value["sourceCitation"],
    statement: value["statement"],
    unit: value["unit"],
    value: value["value"],
  };
}
