/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Isin1
 */
export type Isin1 = string | null;

/**
 * Check if a given object implements the Isin1 interface.
 */
export function instanceOfIsin1(value: unknown): value is Isin1 {
  return typeof value === "string" || value === null;
}

export function Isin1FromJSON(json: any): Isin1 {
  return Isin1FromJSONTyped(json, false);
}

export function Isin1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Isin1 {
  return json;
}

export function Isin1ToJSON(json: any): Isin1 {
  return Isin1ToJSONTyped(json, false);
}

export function Isin1ToJSONTyped(
  value?: Isin1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
