/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { RegulatoryValidationSeverity } from "./RegulatoryValidationSeverity";
import {
  RegulatoryValidationSeverityFromJSON,
  RegulatoryValidationSeverityFromJSONTyped,
  RegulatoryValidationSeverityToJSON,
  RegulatoryValidationSeverityToJSONTyped,
} from "./RegulatoryValidationSeverity";

/**
 *
 * @export
 * @interface LiquidityValidationRead
 */
export interface LiquidityValidationRead {
  /**
   *
   * @type {string}
   * @memberof LiquidityValidationRead
   */
  message: string;
  /**
   *
   * @type {boolean}
   * @memberof LiquidityValidationRead
   */
  passed: boolean;
  /**
   *
   * @type {string}
   * @memberof LiquidityValidationRead
   */
  ruleCode: string;
  /**
   *
   * @type {RegulatoryValidationSeverity}
   * @memberof LiquidityValidationRead
   */
  severity: RegulatoryValidationSeverity;
}

/**
 * Check if a given object implements the LiquidityValidationRead interface.
 */
export function instanceOfLiquidityValidationRead(
  value: object,
): value is LiquidityValidationRead {
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("passed" in value) || value["passed"] === undefined) return false;
  if (!("ruleCode" in value) || value["ruleCode"] === undefined) return false;
  if (!("severity" in value) || value["severity"] === undefined) return false;
  return true;
}

export function LiquidityValidationReadFromJSON(
  json: any,
): LiquidityValidationRead {
  return LiquidityValidationReadFromJSONTyped(json, false);
}

export function LiquidityValidationReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LiquidityValidationRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    message: json["message"],
    passed: json["passed"],
    ruleCode: json["rule_code"],
    severity: RegulatoryValidationSeverityFromJSON(json["severity"]),
  };
}

export function LiquidityValidationReadToJSON(
  json: any,
): LiquidityValidationRead {
  return LiquidityValidationReadToJSONTyped(json, false);
}

export function LiquidityValidationReadToJSONTyped(
  value?: LiquidityValidationRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    message: value["message"],
    passed: value["passed"],
    rule_code: value["ruleCode"],
    severity: RegulatoryValidationSeverityToJSON(value["severity"]),
  };
}
