/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ActionItemInMinSeverity } from "./ActionItemInMinSeverity";
import {
  ActionItemInMinSeverityFromJSON,
  ActionItemInMinSeverityFromJSONTyped,
  ActionItemInMinSeverityToJSON,
  ActionItemInMinSeverityToJSONTyped,
} from "./ActionItemInMinSeverity";
import type { Description1 } from "./Description1";
import {
  Description1FromJSON,
  Description1FromJSONTyped,
  Description1ToJSON,
  Description1ToJSONTyped,
} from "./Description1";
import type { Source1 } from "./Source1";
import {
  Source1FromJSON,
  Source1FromJSONTyped,
  Source1ToJSON,
  Source1ToJSONTyped,
} from "./Source1";
import type { Narrative } from "./Narrative";
import {
  NarrativeFromJSON,
  NarrativeFromJSONTyped,
  NarrativeToJSON,
  NarrativeToJSONTyped,
} from "./Narrative";
import type { HorizonYears } from "./HorizonYears";
import {
  HorizonYearsFromJSON,
  HorizonYearsFromJSONTyped,
  HorizonYearsToJSON,
  HorizonYearsToJSONTyped,
} from "./HorizonYears";
import type { InstitutionTypeApplicability } from "./InstitutionTypeApplicability";
import {
  InstitutionTypeApplicabilityFromJSON,
  InstitutionTypeApplicabilityFromJSONTyped,
  InstitutionTypeApplicabilityToJSON,
  InstitutionTypeApplicabilityToJSONTyped,
} from "./InstitutionTypeApplicability";
import type { Paths } from "./Paths";
import {
  PathsFromJSON,
  PathsFromJSONTyped,
  PathsToJSON,
  PathsToJSONTyped,
} from "./Paths";
import type { MacroScenarioUpdateScenarioType } from "./MacroScenarioUpdateScenarioType";
import {
  MacroScenarioUpdateScenarioTypeFromJSON,
  MacroScenarioUpdateScenarioTypeFromJSONTyped,
  MacroScenarioUpdateScenarioTypeToJSON,
  MacroScenarioUpdateScenarioTypeToJSONTyped,
} from "./MacroScenarioUpdateScenarioType";
import type { Name } from "./Name";
import {
  NameFromJSON,
  NameFromJSONTyped,
  NameToJSON,
  NameToJSONTyped,
} from "./Name";

/**
 * Draft-only edit. Any provided ``paths`` REPLACES the full path set.
 * @export
 * @interface MacroScenarioUpdate
 */
export interface MacroScenarioUpdate {
  /**
   *
   * @type {Description1}
   * @memberof MacroScenarioUpdate
   */
  description?: Description1;
  /**
   *
   * @type {HorizonYears}
   * @memberof MacroScenarioUpdate
   */
  horizonYears?: HorizonYears;
  /**
   *
   * @type {InstitutionTypeApplicability}
   * @memberof MacroScenarioUpdate
   */
  institutionTypeApplicability?: InstitutionTypeApplicability;
  /**
   *
   * @type {Name}
   * @memberof MacroScenarioUpdate
   */
  name?: Name;
  /**
   *
   * @type {Narrative}
   * @memberof MacroScenarioUpdate
   */
  narrative?: Narrative;
  /**
   *
   * @type {Paths}
   * @memberof MacroScenarioUpdate
   */
  paths?: Paths;
  /**
   *
   * @type {string}
   * @memberof MacroScenarioUpdate
   */
  reason: string;
  /**
   *
   * @type {MacroScenarioUpdateScenarioType}
   * @memberof MacroScenarioUpdate
   */
  scenarioType?: MacroScenarioUpdateScenarioType;
  /**
   *
   * @type {ActionItemInMinSeverity}
   * @memberof MacroScenarioUpdate
   */
  severity?: ActionItemInMinSeverity;
  /**
   *
   * @type {Source1}
   * @memberof MacroScenarioUpdate
   */
  source?: Source1;
}

/**
 * Check if a given object implements the MacroScenarioUpdate interface.
 */
export function instanceOfMacroScenarioUpdate(
  value: object,
): value is MacroScenarioUpdate {
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function MacroScenarioUpdateFromJSON(json: any): MacroScenarioUpdate {
  return MacroScenarioUpdateFromJSONTyped(json, false);
}

export function MacroScenarioUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MacroScenarioUpdate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    description:
      json["description"] == null
        ? undefined
        : Description1FromJSON(json["description"]),
    horizonYears:
      json["horizon_years"] == null
        ? undefined
        : HorizonYearsFromJSON(json["horizon_years"]),
    institutionTypeApplicability:
      json["institution_type_applicability"] == null
        ? undefined
        : InstitutionTypeApplicabilityFromJSON(
            json["institution_type_applicability"],
          ),
    name: json["name"] == null ? undefined : NameFromJSON(json["name"]),
    narrative:
      json["narrative"] == null
        ? undefined
        : NarrativeFromJSON(json["narrative"]),
    paths: json["paths"] == null ? undefined : PathsFromJSON(json["paths"]),
    reason: json["reason"],
    scenarioType:
      json["scenario_type"] == null
        ? undefined
        : MacroScenarioUpdateScenarioTypeFromJSON(json["scenario_type"]),
    severity:
      json["severity"] == null
        ? undefined
        : ActionItemInMinSeverityFromJSON(json["severity"]),
    source:
      json["source"] == null ? undefined : Source1FromJSON(json["source"]),
  };
}

export function MacroScenarioUpdateToJSON(json: any): MacroScenarioUpdate {
  return MacroScenarioUpdateToJSONTyped(json, false);
}

export function MacroScenarioUpdateToJSONTyped(
  value?: MacroScenarioUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    description: Description1ToJSON(value["description"]),
    horizon_years: HorizonYearsToJSON(value["horizonYears"]),
    institution_type_applicability: InstitutionTypeApplicabilityToJSON(
      value["institutionTypeApplicability"],
    ),
    name: NameToJSON(value["name"]),
    narrative: NarrativeToJSON(value["narrative"]),
    paths: PathsToJSON(value["paths"]),
    reason: value["reason"],
    scenario_type: MacroScenarioUpdateScenarioTypeToJSON(value["scenarioType"]),
    severity: ActionItemInMinSeverityToJSON(value["severity"]),
    source: Source1ToJSON(value["source"]),
  };
}
