/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ActionItemInMinSeverity } from "./ActionItemInMinSeverity";
import {
  ActionItemInMinSeverityFromJSON,
  ActionItemInMinSeverityFromJSONTyped,
  ActionItemInMinSeverityToJSON,
  ActionItemInMinSeverityToJSONTyped,
} from "./ActionItemInMinSeverity";
import type { MacroPathRead } from "./MacroPathRead";
import {
  MacroPathReadFromJSON,
  MacroPathReadFromJSONTyped,
  MacroPathReadToJSON,
  MacroPathReadToJSONTyped,
} from "./MacroPathRead";
import type { Source2 } from "./Source2";
import {
  Source2FromJSON,
  Source2FromJSONTyped,
  Source2ToJSON,
  Source2ToJSONTyped,
} from "./Source2";
import type { CreatedBy } from "./CreatedBy";
import {
  CreatedByFromJSON,
  CreatedByFromJSONTyped,
  CreatedByToJSON,
  CreatedByToJSONTyped,
} from "./CreatedBy";
import type { Description } from "./Description";
import {
  DescriptionFromJSON,
  DescriptionFromJSONTyped,
  DescriptionToJSON,
  DescriptionToJSONTyped,
} from "./Description";
import type { ApprovedBy1 } from "./ApprovedBy1";
import {
  ApprovedBy1FromJSON,
  ApprovedBy1FromJSONTyped,
  ApprovedBy1ToJSON,
  ApprovedBy1ToJSONTyped,
} from "./ApprovedBy1";
import type { ApprovalTimestamp } from "./ApprovalTimestamp";
import {
  ApprovalTimestampFromJSON,
  ApprovalTimestampFromJSONTyped,
  ApprovalTimestampToJSON,
  ApprovalTimestampToJSONTyped,
} from "./ApprovalTimestamp";
import type { InstitutionTypeApplicability } from "./InstitutionTypeApplicability";
import {
  InstitutionTypeApplicabilityFromJSON,
  InstitutionTypeApplicabilityFromJSONTyped,
  InstitutionTypeApplicabilityToJSON,
  InstitutionTypeApplicabilityToJSONTyped,
} from "./InstitutionTypeApplicability";
import type { Narrative1 } from "./Narrative1";
import {
  Narrative1FromJSON,
  Narrative1FromJSONTyped,
  Narrative1ToJSON,
  Narrative1ToJSONTyped,
} from "./Narrative1";
import type { BankId1 } from "./BankId1";
import {
  BankId1FromJSON,
  BankId1FromJSONTyped,
  BankId1ToJSON,
  BankId1ToJSONTyped,
} from "./BankId1";
import type { AppSchemasStressScenarioType } from "./AppSchemasStressScenarioType";
import {
  AppSchemasStressScenarioTypeFromJSON,
  AppSchemasStressScenarioTypeFromJSONTyped,
  AppSchemasStressScenarioTypeToJSON,
  AppSchemasStressScenarioTypeToJSONTyped,
} from "./AppSchemasStressScenarioType";
import type { ScenarioStatus } from "./ScenarioStatus";
import {
  ScenarioStatusFromJSON,
  ScenarioStatusFromJSONTyped,
  ScenarioStatusToJSON,
  ScenarioStatusToJSONTyped,
} from "./ScenarioStatus";

/**
 *
 * @export
 * @interface MacroScenarioRead
 */
export interface MacroScenarioRead {
  /**
   *
   * @type {ApprovalTimestamp}
   * @memberof MacroScenarioRead
   */
  approvalTimestamp: ApprovalTimestamp;
  /**
   *
   * @type {ApprovedBy1}
   * @memberof MacroScenarioRead
   */
  approvedBy: ApprovedBy1;
  /**
   *
   * @type {BankId1}
   * @memberof MacroScenarioRead
   */
  bankId: BankId1;
  /**
   *
   * @type {string}
   * @memberof MacroScenarioRead
   */
  code: string;
  /**
   *
   * @type {Date}
   * @memberof MacroScenarioRead
   */
  createdAt: Date;
  /**
   *
   * @type {CreatedBy}
   * @memberof MacroScenarioRead
   */
  createdBy: CreatedBy;
  /**
   *
   * @type {Description}
   * @memberof MacroScenarioRead
   */
  description: Description;
  /**
   *
   * @type {number}
   * @memberof MacroScenarioRead
   */
  horizonYears: number;
  /**
   *
   * @type {string}
   * @memberof MacroScenarioRead
   */
  id: string;
  /**
   *
   * @type {InstitutionTypeApplicability}
   * @memberof MacroScenarioRead
   */
  institutionTypeApplicability: InstitutionTypeApplicability;
  /**
   *
   * @type {string}
   * @memberof MacroScenarioRead
   */
  name: string;
  /**
   *
   * @type {Narrative1}
   * @memberof MacroScenarioRead
   */
  narrative: Narrative1;
  /**
   *
   * @type {string}
   * @memberof MacroScenarioRead
   */
  organizationId: string;
  /**
   *
   * @type {Array<MacroPathRead>}
   * @memberof MacroScenarioRead
   */
  paths: Array<MacroPathRead>;
  /**
   *
   * @type {AppSchemasStressScenarioType}
   * @memberof MacroScenarioRead
   */
  scenarioType: AppSchemasStressScenarioType;
  /**
   *
   * @type {ActionItemInMinSeverity}
   * @memberof MacroScenarioRead
   */
  severity: ActionItemInMinSeverity;
  /**
   *
   * @type {Source2}
   * @memberof MacroScenarioRead
   */
  source: Source2;
  /**
   *
   * @type {ScenarioStatus}
   * @memberof MacroScenarioRead
   */
  status: ScenarioStatus;
  /**
   *
   * @type {Date}
   * @memberof MacroScenarioRead
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof MacroScenarioRead
   */
  version: number;
}

/**
 * Check if a given object implements the MacroScenarioRead interface.
 */
export function instanceOfMacroScenarioRead(
  value: object,
): value is MacroScenarioRead {
  if (
    !("approvalTimestamp" in value) ||
    value["approvalTimestamp"] === undefined
  )
    return false;
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
  if (!("description" in value) || value["description"] === undefined)
    return false;
  if (!("horizonYears" in value) || value["horizonYears"] === undefined)
    return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (
    !("institutionTypeApplicability" in value) ||
    value["institutionTypeApplicability"] === undefined
  )
    return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("narrative" in value) || value["narrative"] === undefined) return false;
  if (!("organizationId" in value) || value["organizationId"] === undefined)
    return false;
  if (!("paths" in value) || value["paths"] === undefined) return false;
  if (!("scenarioType" in value) || value["scenarioType"] === undefined)
    return false;
  if (!("severity" in value) || value["severity"] === undefined) return false;
  if (!("source" in value) || value["source"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  return true;
}

export function MacroScenarioReadFromJSON(json: any): MacroScenarioRead {
  return MacroScenarioReadFromJSONTyped(json, false);
}

export function MacroScenarioReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MacroScenarioRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    approvalTimestamp: ApprovalTimestampFromJSON(json["approval_timestamp"]),
    approvedBy: ApprovedBy1FromJSON(json["approved_by"]),
    bankId: BankId1FromJSON(json["bank_id"]),
    code: json["code"],
    createdAt: new Date(json["created_at"]),
    createdBy: CreatedByFromJSON(json["created_by"]),
    description: DescriptionFromJSON(json["description"]),
    horizonYears: json["horizon_years"],
    id: json["id"],
    institutionTypeApplicability: InstitutionTypeApplicabilityFromJSON(
      json["institution_type_applicability"],
    ),
    name: json["name"],
    narrative: Narrative1FromJSON(json["narrative"]),
    organizationId: json["organization_id"],
    paths: (json["paths"] as Array<any>).map(MacroPathReadFromJSON),
    scenarioType: AppSchemasStressScenarioTypeFromJSON(json["scenario_type"]),
    severity: ActionItemInMinSeverityFromJSON(json["severity"]),
    source: Source2FromJSON(json["source"]),
    status: ScenarioStatusFromJSON(json["status"]),
    updatedAt: new Date(json["updated_at"]),
    version: json["version"],
  };
}

export function MacroScenarioReadToJSON(json: any): MacroScenarioRead {
  return MacroScenarioReadToJSONTyped(json, false);
}

export function MacroScenarioReadToJSONTyped(
  value?: MacroScenarioRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approval_timestamp: ApprovalTimestampToJSON(value["approvalTimestamp"]),
    approved_by: ApprovedBy1ToJSON(value["approvedBy"]),
    bank_id: BankId1ToJSON(value["bankId"]),
    code: value["code"],
    created_at: value["createdAt"].toISOString(),
    created_by: CreatedByToJSON(value["createdBy"]),
    description: DescriptionToJSON(value["description"]),
    horizon_years: value["horizonYears"],
    id: value["id"],
    institution_type_applicability: InstitutionTypeApplicabilityToJSON(
      value["institutionTypeApplicability"],
    ),
    name: value["name"],
    narrative: Narrative1ToJSON(value["narrative"]),
    organization_id: value["organizationId"],
    paths: (value["paths"] as Array<any>).map(MacroPathReadToJSON),
    scenario_type: AppSchemasStressScenarioTypeToJSON(value["scenarioType"]),
    severity: ActionItemInMinSeverityToJSON(value["severity"]),
    source: Source2ToJSON(value["source"]),
    status: ScenarioStatusToJSON(value["status"]),
    updated_at: value["updatedAt"].toISOString(),
    version: value["version"],
  };
}
