/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CreatedBy } from "./CreatedBy";
import {
  CreatedByFromJSON,
  CreatedByFromJSONTyped,
  CreatedByToJSON,
  CreatedByToJSONTyped,
} from "./CreatedBy";
import type { ApprovedBy1 } from "./ApprovedBy1";
import {
  ApprovedBy1FromJSON,
  ApprovedBy1FromJSONTyped,
  ApprovedBy1ToJSON,
  ApprovedBy1ToJSONTyped,
} from "./ApprovedBy1";
import type { BankId1 } from "./BankId1";
import {
  BankId1FromJSON,
  BankId1FromJSONTyped,
  BankId1ToJSON,
  BankId1ToJSONTyped,
} from "./BankId1";
import type { PlanStatus } from "./PlanStatus";
import {
  PlanStatusFromJSON,
  PlanStatusFromJSONTyped,
  PlanStatusToJSON,
  PlanStatusToJSONTyped,
} from "./PlanStatus";

/**
 *
 * @export
 * @interface ManagementActionPlanSummaryRead
 */
export interface ManagementActionPlanSummaryRead {
  /**
   *
   * @type {number}
   * @memberof ManagementActionPlanSummaryRead
   */
  actionCount: number;
  /**
   *
   * @type {ApprovedBy1}
   * @memberof ManagementActionPlanSummaryRead
   */
  approvedBy: ApprovedBy1;
  /**
   *
   * @type {BankId1}
   * @memberof ManagementActionPlanSummaryRead
   */
  bankId: BankId1;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanSummaryRead
   */
  code: string;
  /**
   *
   * @type {Date}
   * @memberof ManagementActionPlanSummaryRead
   */
  createdAt: Date;
  /**
   *
   * @type {CreatedBy}
   * @memberof ManagementActionPlanSummaryRead
   */
  createdBy: CreatedBy;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanSummaryRead
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanSummaryRead
   */
  name: string;
  /**
   *
   * @type {PlanStatus}
   * @memberof ManagementActionPlanSummaryRead
   */
  status: PlanStatus;
  /**
   *
   * @type {Date}
   * @memberof ManagementActionPlanSummaryRead
   */
  updatedAt: Date;
  /**
   *
   * @type {number}
   * @memberof ManagementActionPlanSummaryRead
   */
  version: number;
}

/**
 * Check if a given object implements the ManagementActionPlanSummaryRead interface.
 */
export function instanceOfManagementActionPlanSummaryRead(
  value: object,
): value is ManagementActionPlanSummaryRead {
  if (!("actionCount" in value) || value["actionCount"] === undefined)
    return false;
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("createdBy" in value) || value["createdBy"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  if (!("version" in value) || value["version"] === undefined) return false;
  return true;
}

export function ManagementActionPlanSummaryReadFromJSON(
  json: any,
): ManagementActionPlanSummaryRead {
  return ManagementActionPlanSummaryReadFromJSONTyped(json, false);
}

export function ManagementActionPlanSummaryReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManagementActionPlanSummaryRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    actionCount: json["action_count"],
    approvedBy: ApprovedBy1FromJSON(json["approved_by"]),
    bankId: BankId1FromJSON(json["bank_id"]),
    code: json["code"],
    createdAt: new Date(json["created_at"]),
    createdBy: CreatedByFromJSON(json["created_by"]),
    id: json["id"],
    name: json["name"],
    status: PlanStatusFromJSON(json["status"]),
    updatedAt: new Date(json["updated_at"]),
    version: json["version"],
  };
}

export function ManagementActionPlanSummaryReadToJSON(
  json: any,
): ManagementActionPlanSummaryRead {
  return ManagementActionPlanSummaryReadToJSONTyped(json, false);
}

export function ManagementActionPlanSummaryReadToJSONTyped(
  value?: ManagementActionPlanSummaryRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    action_count: value["actionCount"],
    approved_by: ApprovedBy1ToJSON(value["approvedBy"]),
    bank_id: BankId1ToJSON(value["bankId"]),
    code: value["code"],
    created_at: value["createdAt"].toISOString(),
    created_by: CreatedByToJSON(value["createdBy"]),
    id: value["id"],
    name: value["name"],
    status: PlanStatusToJSON(value["status"]),
    updated_at: value["updatedAt"].toISOString(),
    version: value["version"],
  };
}
