/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Description1 } from "./Description1";
import {
  Description1FromJSON,
  Description1FromJSONTyped,
  Description1ToJSON,
  Description1ToJSONTyped,
} from "./Description1";
import type { ActionItemIn } from "./ActionItemIn";
import {
  ActionItemInFromJSON,
  ActionItemInFromJSONTyped,
  ActionItemInToJSON,
  ActionItemInToJSONTyped,
} from "./ActionItemIn";
import type { BankId } from "./BankId";
import {
  BankIdFromJSON,
  BankIdFromJSONTyped,
  BankIdToJSON,
  BankIdToJSONTyped,
} from "./BankId";

/**
 *
 * @export
 * @interface ManagementActionPlanCreate
 */
export interface ManagementActionPlanCreate {
  /**
   *
   * @type {Array<ActionItemIn>}
   * @memberof ManagementActionPlanCreate
   */
  actions: Array<ActionItemIn>;
  /**
   *
   * @type {BankId}
   * @memberof ManagementActionPlanCreate
   */
  bankId?: BankId;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanCreate
   */
  code: string;
  /**
   *
   * @type {Description1}
   * @memberof ManagementActionPlanCreate
   */
  description?: Description1;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanCreate
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ManagementActionPlanCreate
   */
  reason: string;
}

/**
 * Check if a given object implements the ManagementActionPlanCreate interface.
 */
export function instanceOfManagementActionPlanCreate(
  value: object,
): value is ManagementActionPlanCreate {
  if (!("actions" in value) || value["actions"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function ManagementActionPlanCreateFromJSON(
  json: any,
): ManagementActionPlanCreate {
  return ManagementActionPlanCreateFromJSONTyped(json, false);
}

export function ManagementActionPlanCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ManagementActionPlanCreate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    actions: (json["actions"] as Array<any>).map(ActionItemInFromJSON),
    bankId:
      json["bank_id"] == null ? undefined : BankIdFromJSON(json["bank_id"]),
    code: json["code"],
    description:
      json["description"] == null
        ? undefined
        : Description1FromJSON(json["description"]),
    name: json["name"],
    reason: json["reason"],
  };
}

export function ManagementActionPlanCreateToJSON(
  json: any,
): ManagementActionPlanCreate {
  return ManagementActionPlanCreateToJSONTyped(json, false);
}

export function ManagementActionPlanCreateToJSONTyped(
  value?: ManagementActionPlanCreate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    actions: (value["actions"] as Array<any>).map(ActionItemInToJSON),
    bank_id: BankIdToJSON(value["bankId"]),
    code: value["code"],
    description: Description1ToJSON(value["description"]),
    name: value["name"],
    reason: value["reason"],
  };
}
