/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * Post-onboarding management (§9.3) and credential rotation (§10.4).
 *
 * When ``credentials`` is present the new set is validated against the
 * vendor FIRST; only on success are the stored ciphertext, fingerprint, and
 * expiry swapped in one transaction. On failure nothing changes and the
 * bank-facing error is returned as a 422.
 * @export
 * @interface MarketDataConnectionUpdate
 */
export interface MarketDataConnectionUpdate {
  /**
   *
   * @type {Date}
   * @memberof MarketDataConnectionUpdate
   */
  credentialExpiresAt?: Date | null;
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof MarketDataConnectionUpdate
   */
  credentials?: { [key: string]: any } | null;
  /**
   *
   * @type {string}
   * @memberof MarketDataConnectionUpdate
   */
  displayName?: string | null;
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof MarketDataConnectionUpdate
   */
  schedule?: { [key: string]: string } | null;
  /**
   *
   * @type {Array<string>}
   * @memberof MarketDataConnectionUpdate
   */
  scopes?: Array<string> | null;
}

/**
 * Check if a given object implements the MarketDataConnectionUpdate interface.
 */
export function instanceOfMarketDataConnectionUpdate(
  value: object,
): value is MarketDataConnectionUpdate {
  return true;
}

export function MarketDataConnectionUpdateFromJSON(
  json: any,
): MarketDataConnectionUpdate {
  return MarketDataConnectionUpdateFromJSONTyped(json, false);
}

export function MarketDataConnectionUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MarketDataConnectionUpdate {
  if (json == null) {
    return json;
  }
  return {
    credentialExpiresAt:
      json["credential_expires_at"] == null
        ? undefined
        : new Date(json["credential_expires_at"]),
    credentials: json["credentials"] == null ? undefined : json["credentials"],
    displayName:
      json["display_name"] == null ? undefined : json["display_name"],
    schedule: json["schedule"] == null ? undefined : json["schedule"],
    scopes: json["scopes"] == null ? undefined : json["scopes"],
  };
}

export function MarketDataConnectionUpdateToJSON(
  json: any,
): MarketDataConnectionUpdate {
  return MarketDataConnectionUpdateToJSONTyped(json, false);
}

export function MarketDataConnectionUpdateToJSONTyped(
  value?: MarketDataConnectionUpdate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    credential_expires_at:
      value["credentialExpiresAt"] == null
        ? undefined
        : (value["credentialExpiresAt"] as any).toISOString(),
    credentials: value["credentials"],
    display_name: value["displayName"],
    schedule: value["schedule"],
    scopes: value["scopes"],
  };
}
