/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Metric
 */
export type Metric = string | null;

/**
 * Check if a given object implements the Metric interface.
 */
export function instanceOfMetric(value: unknown): value is Metric {
  return typeof value === "string" || value === null;
}

export function MetricFromJSON(json: any): Metric {
  return MetricFromJSONTyped(json, false);
}

export function MetricFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Metric {
  return json;
}

export function MetricToJSON(json: any): Metric {
  return MetricToJSONTyped(json, false);
}

export function MetricToJSONTyped(
  value?: Metric | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
