/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MinH
 */
export type MinH = number | null;

/**
 * Check if a given object implements the MinH interface.
 */
export function instanceOfMinH(value: unknown): value is MinH {
  return typeof value === "number" || value === null;
}

export function MinHFromJSON(json: any): MinH {
  return MinHFromJSONTyped(json, false);
}

export function MinHFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MinH {
  return json;
}

export function MinHToJSON(json: any): MinH {
  return MinHToJSONTyped(json, false);
}

export function MinHToJSONTyped(
  value?: MinH | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
