/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Narrative1
 */
export type Narrative1 = string | null;

/**
 * Check if a given object implements the Narrative1 interface.
 */
export function instanceOfNarrative1(value: unknown): value is Narrative1 {
  return typeof value === "string" || value === null;
}

export function Narrative1FromJSON(json: any): Narrative1 {
  return Narrative1FromJSONTyped(json, false);
}

export function Narrative1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Narrative1 {
  return json;
}

export function Narrative1ToJSON(json: any): Narrative1 {
  return Narrative1ToJSONTyped(json, false);
}

export function Narrative1ToJSONTyped(
  value?: Narrative1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
