/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { OutletNumber1 } from "./OutletNumber1";
import {
  OutletNumber1FromJSON,
  OutletNumber1FromJSONTyped,
  OutletNumber1ToJSON,
  OutletNumber1ToJSONTyped,
} from "./OutletNumber1";
import type { OpenedOn } from "./OpenedOn";
import {
  OpenedOnFromJSON,
  OpenedOnFromJSONTyped,
  OpenedOnToJSON,
  OpenedOnToJSONTyped,
} from "./OpenedOn";
import type { OutletStatus } from "./OutletStatus";
import {
  OutletStatusFromJSON,
  OutletStatusFromJSONTyped,
  OutletStatusToJSON,
  OutletStatusToJSONTyped,
} from "./OutletStatus";
import type { ClosedOn } from "./ClosedOn";
import {
  ClosedOnFromJSON,
  ClosedOnFromJSONTyped,
  ClosedOnToJSON,
  ClosedOnToJSONTyped,
} from "./ClosedOn";
import type { RelocatedFrom1 } from "./RelocatedFrom1";
import {
  RelocatedFrom1FromJSON,
  RelocatedFrom1FromJSONTyped,
  RelocatedFrom1ToJSON,
  RelocatedFrom1ToJSONTyped,
} from "./RelocatedFrom1";
import type { OutletType } from "./OutletType";
import {
  OutletTypeFromJSON,
  OutletTypeFromJSONTyped,
  OutletTypeToJSON,
  OutletTypeToJSONTyped,
} from "./OutletType";

/**
 *
 * @export
 * @interface OutletRead
 */
export interface OutletRead {
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof OutletRead
   */
  address: { [key: string]: any };
  /**
   *
   * @type {string}
   * @memberof OutletRead
   */
  bankId: string;
  /**
   *
   * @type {ClosedOn}
   * @memberof OutletRead
   */
  closedOn: ClosedOn;
  /**
   *
   * @type {Date}
   * @memberof OutletRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof OutletRead
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof OutletRead
   */
  name: string;
  /**
   *
   * @type {OpenedOn}
   * @memberof OutletRead
   */
  openedOn: OpenedOn;
  /**
   *
   * @type {OutletNumber1}
   * @memberof OutletRead
   */
  outletNumber: OutletNumber1;
  /**
   *
   * @type {OutletType}
   * @memberof OutletRead
   */
  outletType: OutletType;
  /**
   *
   * @type {RelocatedFrom1}
   * @memberof OutletRead
   */
  relocatedFrom: RelocatedFrom1;
  /**
   *
   * @type {OutletStatus}
   * @memberof OutletRead
   */
  status: OutletStatus;
  /**
   *
   * @type {Date}
   * @memberof OutletRead
   */
  updatedAt: Date;
}

/**
 * Check if a given object implements the OutletRead interface.
 */
export function instanceOfOutletRead(value: object): value is OutletRead {
  if (!("address" in value) || value["address"] === undefined) return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("closedOn" in value) || value["closedOn"] === undefined) return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("name" in value) || value["name"] === undefined) return false;
  if (!("openedOn" in value) || value["openedOn"] === undefined) return false;
  if (!("outletNumber" in value) || value["outletNumber"] === undefined)
    return false;
  if (!("outletType" in value) || value["outletType"] === undefined)
    return false;
  if (!("relocatedFrom" in value) || value["relocatedFrom"] === undefined)
    return false;
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
  return true;
}

export function OutletReadFromJSON(json: any): OutletRead {
  return OutletReadFromJSONTyped(json, false);
}

export function OutletReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OutletRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    address: json["address"],
    bankId: json["bank_id"],
    closedOn: ClosedOnFromJSON(json["closed_on"]),
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    name: json["name"],
    openedOn: OpenedOnFromJSON(json["opened_on"]),
    outletNumber: OutletNumber1FromJSON(json["outlet_number"]),
    outletType: OutletTypeFromJSON(json["outlet_type"]),
    relocatedFrom: RelocatedFrom1FromJSON(json["relocated_from"]),
    status: OutletStatusFromJSON(json["status"]),
    updatedAt: new Date(json["updated_at"]),
  };
}

export function OutletReadToJSON(json: any): OutletRead {
  return OutletReadToJSONTyped(json, false);
}

export function OutletReadToJSONTyped(
  value?: OutletRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: value["address"],
    bank_id: value["bankId"],
    closed_on: ClosedOnToJSON(value["closedOn"]),
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    name: value["name"],
    opened_on: OpenedOnToJSON(value["openedOn"]),
    outlet_number: OutletNumber1ToJSON(value["outletNumber"]),
    outlet_type: OutletTypeToJSON(value["outletType"]),
    relocated_from: RelocatedFrom1ToJSON(value["relocatedFrom"]),
    status: OutletStatusToJSON(value["status"]),
    updated_at: value["updatedAt"].toISOString(),
  };
}
