/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OverrideReason
 */
export type OverrideReason = string | null;

/**
 * Check if a given object implements the OverrideReason interface.
 */
export function instanceOfOverrideReason(
  value: unknown,
): value is OverrideReason {
  return typeof value === "string" || value === null;
}

export function OverrideReasonFromJSON(json: any): OverrideReason {
  return OverrideReasonFromJSONTyped(json, false);
}

export function OverrideReasonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OverrideReason {
  return json;
}

export function OverrideReasonToJSON(json: any): OverrideReason {
  return OverrideReasonToJSONTyped(json, false);
}

export function OverrideReasonToJSONTyped(
  value?: OverrideReason | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
