/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OverlayCreateTenorMonths
 */
export type OverlayCreateTenorMonths = number | null;

/**
 * Check if a given object implements the OverlayCreateTenorMonths interface.
 */
export function instanceOfOverlayCreateTenorMonths(
  value: unknown,
): value is OverlayCreateTenorMonths {
  return typeof value === "number" || value === null;
}

export function OverlayCreateTenorMonthsFromJSON(
  json: any,
): OverlayCreateTenorMonths {
  return OverlayCreateTenorMonthsFromJSONTyped(json, false);
}

export function OverlayCreateTenorMonthsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OverlayCreateTenorMonths {
  return json;
}

export function OverlayCreateTenorMonthsToJSON(
  json: any,
): OverlayCreateTenorMonths {
  return OverlayCreateTenorMonthsToJSONTyped(json, false);
}

export function OverlayCreateTenorMonthsToJSONTyped(
  value?: OverlayCreateTenorMonths | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
