/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Overlay
 */
export type Overlay = boolean | null;

/**
 * Check if a given object implements the Overlay interface.
 */
export function instanceOfOverlay(value: unknown): value is Overlay {
  return typeof value === "boolean" || value === null;
}

export function OverlayFromJSON(json: any): Overlay {
  return OverlayFromJSONTyped(json, false);
}

export function OverlayFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Overlay {
  return json;
}

export function OverlayToJSON(json: any): Overlay {
  return OverlayToJSONTyped(json, false);
}

export function OverlayToJSONTyped(
  value?: Overlay | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
