/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OwnershipForeignPct
 */
export type OwnershipForeignPct = number | string | null;

/**
 * Check if a given object implements the OwnershipForeignPct interface.
 */
export function instanceOfOwnershipForeignPct(
  value: unknown,
): value is OwnershipForeignPct {
  return (
    typeof value === "number" || typeof value === "string" || value === null
  );
}

export function OwnershipForeignPctFromJSON(json: any): OwnershipForeignPct {
  return OwnershipForeignPctFromJSONTyped(json, false);
}

export function OwnershipForeignPctFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OwnershipForeignPct {
  return json;
}

export function OwnershipForeignPctToJSON(json: any): OwnershipForeignPct {
  return OwnershipForeignPctToJSONTyped(json, false);
}

export function OwnershipForeignPctToJSONTyped(
  value?: OwnershipForeignPct | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
