/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SignatureFieldPlacement } from "./SignatureFieldPlacement";
import {
  SignatureFieldPlacementFromJSON,
  SignatureFieldPlacementFromJSONTyped,
  SignatureFieldPlacementToJSON,
  SignatureFieldPlacementToJSONTyped,
} from "./SignatureFieldPlacement";

/**
 * Place this package's fields. An empty list clears the override.
 * @export
 * @interface PackageSignaturePlacementRequest
 */
export interface PackageSignaturePlacementRequest {
  /**
   *
   * @type {Array<SignatureFieldPlacement>}
   * @memberof PackageSignaturePlacementRequest
   */
  placements: Array<SignatureFieldPlacement>;
  /**
   *
   * @type {string}
   * @memberof PackageSignaturePlacementRequest
   */
  reason: string;
}

/**
 * Check if a given object implements the PackageSignaturePlacementRequest interface.
 */
export function instanceOfPackageSignaturePlacementRequest(
  value: object,
): value is PackageSignaturePlacementRequest {
  if (!("placements" in value) || value["placements"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function PackageSignaturePlacementRequestFromJSON(
  json: any,
): PackageSignaturePlacementRequest {
  return PackageSignaturePlacementRequestFromJSONTyped(json, false);
}

export function PackageSignaturePlacementRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PackageSignaturePlacementRequest {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    placements: (json["placements"] as Array<any>).map(
      SignatureFieldPlacementFromJSON,
    ),
    reason: json["reason"],
  };
}

export function PackageSignaturePlacementRequestToJSON(
  json: any,
): PackageSignaturePlacementRequest {
  return PackageSignaturePlacementRequestToJSONTyped(json, false);
}

export function PackageSignaturePlacementRequestToJSONTyped(
  value?: PackageSignaturePlacementRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    placements: (value["placements"] as Array<any>).map(
      SignatureFieldPlacementToJSON,
    ),
    reason: value["reason"],
  };
}
