/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParentCountryCode1
 */
export type ParentCountryCode1 = string | null;

/**
 * Check if a given object implements the ParentCountryCode1 interface.
 */
export function instanceOfParentCountryCode1(
  value: unknown,
): value is ParentCountryCode1 {
  return typeof value === "string" || value === null;
}

export function ParentCountryCode1FromJSON(json: any): ParentCountryCode1 {
  return ParentCountryCode1FromJSONTyped(json, false);
}

export function ParentCountryCode1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ParentCountryCode1 {
  return json;
}

export function ParentCountryCode1ToJSON(json: any): ParentCountryCode1 {
  return ParentCountryCode1ToJSONTyped(json, false);
}

export function ParentCountryCode1ToJSONTyped(
  value?: ParentCountryCode1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
