/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PipelineState
 */
export type PipelineState = string | null;

/**
 * Check if a given object implements the PipelineState interface.
 */
export function instanceOfPipelineState(
  value: unknown,
): value is PipelineState {
  return typeof value === "string" || value === null;
}

export function PipelineStateFromJSON(json: any): PipelineState {
  return PipelineStateFromJSONTyped(json, false);
}

export function PipelineStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PipelineState {
  return json;
}

export function PipelineStateToJSON(json: any): PipelineState {
  return PipelineStateToJSONTyped(json, false);
}

export function PipelineStateToJSONTyped(
  value?: PipelineState | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
