/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const PlanStatus = {
  Draft: "draft",
  PendingApproval: "pending_approval",
  Approved: "approved",
  Archived: "archived",
} as const;
export type PlanStatus = (typeof PlanStatus)[keyof typeof PlanStatus];

export function instanceOfPlanStatus(value: any): boolean {
  for (const key in PlanStatus) {
    if (Object.prototype.hasOwnProperty.call(PlanStatus, key)) {
      if (PlanStatus[key as keyof typeof PlanStatus] === value) {
        return true;
      }
    }
  }
  return false;
}

export function PlanStatusFromJSON(json: any): PlanStatus {
  return PlanStatusFromJSONTyped(json, false);
}

export function PlanStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlanStatus {
  return json as PlanStatus;
}

export function PlanStatusToJSON(value?: PlanStatus | null): any {
  return value as any;
}

export function PlanStatusToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): PlanStatus {
  return value as PlanStatus;
}
