/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PlaneAttributionRead } from "./PlaneAttributionRead";
import {
  PlaneAttributionReadFromJSON,
  PlaneAttributionReadFromJSONTyped,
  PlaneAttributionReadToJSON,
  PlaneAttributionReadToJSONTyped,
} from "./PlaneAttributionRead";
import type { PlaneIndexHorizonMonths } from "./PlaneIndexHorizonMonths";
import {
  PlaneIndexHorizonMonthsFromJSON,
  PlaneIndexHorizonMonthsFromJSONTyped,
  PlaneIndexHorizonMonthsToJSON,
  PlaneIndexHorizonMonthsToJSONTyped,
} from "./PlaneIndexHorizonMonths";

/**
 * One reference index resolved under a plane (percent-valued).
 * @export
 * @interface PlaneIndexItemRead
 */
export interface PlaneIndexItemRead {
  /**
   *
   * @type {Date}
   * @memberof PlaneIndexItemRead
   */
  asOfDate: Date;
  /**
   *
   * @type {PlaneAttributionRead}
   * @memberof PlaneIndexItemRead
   */
  attribution: PlaneAttributionRead;
  /**
   *
   * @type {PlaneIndexHorizonMonths}
   * @memberof PlaneIndexItemRead
   */
  horizonMonths?: PlaneIndexHorizonMonths;
  /**
   *
   * @type {string}
   * @memberof PlaneIndexItemRead
   */
  indexCode: string;
  /**
   *
   * @type {string}
   * @memberof PlaneIndexItemRead
   */
  kind?: string;
  /**
   *
   * @type {string}
   * @memberof PlaneIndexItemRead
   */
  scenario: string;
  /**
   *
   * @type {string}
   * @memberof PlaneIndexItemRead
   */
  value: string;
}

/**
 * Check if a given object implements the PlaneIndexItemRead interface.
 */
export function instanceOfPlaneIndexItemRead(
  value: object,
): value is PlaneIndexItemRead {
  if (!("asOfDate" in value) || value["asOfDate"] === undefined) return false;
  if (!("attribution" in value) || value["attribution"] === undefined)
    return false;
  if (!("indexCode" in value) || value["indexCode"] === undefined) return false;
  if (!("scenario" in value) || value["scenario"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function PlaneIndexItemReadFromJSON(json: any): PlaneIndexItemRead {
  return PlaneIndexItemReadFromJSONTyped(json, false);
}

export function PlaneIndexItemReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlaneIndexItemRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    asOfDate: new Date(json["as_of_date"]),
    attribution: PlaneAttributionReadFromJSON(json["attribution"]),
    horizonMonths:
      json["horizon_months"] == null
        ? undefined
        : PlaneIndexHorizonMonthsFromJSON(json["horizon_months"]),
    indexCode: json["index_code"],
    kind: json["kind"] == null ? undefined : json["kind"],
    scenario: json["scenario"],
    value: json["value"],
  };
}

export function PlaneIndexItemReadToJSON(json: any): PlaneIndexItemRead {
  return PlaneIndexItemReadToJSONTyped(json, false);
}

export function PlaneIndexItemReadToJSONTyped(
  value?: PlaneIndexItemRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of_date: value["asOfDate"].toISOString().substring(0, 10),
    attribution: PlaneAttributionReadToJSON(value["attribution"]),
    horizon_months: PlaneIndexHorizonMonthsToJSON(value["horizonMonths"]),
    index_code: value["indexCode"],
    kind: value["kind"],
    scenario: value["scenario"],
    value: value["value"],
  };
}
