/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { Value1 } from "./Value1";
import {
  Value1FromJSON,
  Value1FromJSONTyped,
  Value1ToJSON,
  Value1ToJSONTyped,
} from "./Value1";

/**
 *
 * @export
 * @interface PositionSnapshotOverrideCreate
 */
export interface PositionSnapshotOverrideCreate {
  /**
   *
   * @type {string}
   * @memberof PositionSnapshotOverrideCreate
   */
  field: PositionSnapshotOverrideCreateFieldEnum;
  /**
   *
   * @type {string}
   * @memberof PositionSnapshotOverrideCreate
   */
  reason: string;
  /**
   *
   * @type {Value1}
   * @memberof PositionSnapshotOverrideCreate
   */
  value: Value1 | null;
}

/**
 * @export
 */
export const PositionSnapshotOverrideCreateFieldEnum = {
  Balance: "balance",
  InterestRate: "interest_rate",
  Ifrs9Stage: "ifrs9_stage",
  BehavioralMaturityMonths: "behavioral_maturity_months",
  Encumbered: "encumbered",
  EncumbranceReason: "encumbrance_reason",
  OwningEntity: "owning_entity",
  AssetLocation: "asset_location",
  OperationalPurpose: "operational_purpose",
  RedeemableWithinTwoDays: "redeemable_within_two_days",
  PledgedAsCollateral: "pledged_as_collateral",
  LienReference: "lien_reference",
  DepositAccountType: "deposit_account_type",
} as const;
export type PositionSnapshotOverrideCreateFieldEnum =
  (typeof PositionSnapshotOverrideCreateFieldEnum)[keyof typeof PositionSnapshotOverrideCreateFieldEnum];

/**
 * Check if a given object implements the PositionSnapshotOverrideCreate interface.
 */
export function instanceOfPositionSnapshotOverrideCreate(
  value: object,
): value is PositionSnapshotOverrideCreate {
  if (!("field" in value) || value["field"] === undefined) return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  if (!("value" in value) || value["value"] === undefined) return false;
  return true;
}

export function PositionSnapshotOverrideCreateFromJSON(
  json: any,
): PositionSnapshotOverrideCreate {
  return PositionSnapshotOverrideCreateFromJSONTyped(json, false);
}

export function PositionSnapshotOverrideCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PositionSnapshotOverrideCreate {
  if (json == null) {
    return json;
  }
  return {
    field: json["field"],
    reason: json["reason"],
    value: Value1FromJSON(json["value"]),
  };
}

export function PositionSnapshotOverrideCreateToJSON(
  json: any,
): PositionSnapshotOverrideCreate {
  return PositionSnapshotOverrideCreateToJSONTyped(json, false);
}

export function PositionSnapshotOverrideCreateToJSONTyped(
  value?: PositionSnapshotOverrideCreate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    field: value["field"],
    reason: value["reason"],
    value: Value1ToJSON(value["value"]),
  };
}
