/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PresetFXDepreciationPct
 */
export type PresetFXDepreciationPct = number | string;

/**
 * Check if a given object implements the PresetFXDepreciationPct interface.
 */
export function instanceOfPresetFXDepreciationPct(
  value: unknown,
): value is PresetFXDepreciationPct {
  return typeof value === "number" || typeof value === "string";
}

export function PresetFXDepreciationPctFromJSON(
  json: any,
): PresetFXDepreciationPct {
  return PresetFXDepreciationPctFromJSONTyped(json, false);
}

export function PresetFXDepreciationPctFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PresetFXDepreciationPct {
  return json;
}

export function PresetFXDepreciationPctToJSON(
  json: any,
): PresetFXDepreciationPct {
  return PresetFXDepreciationPctToJSONTyped(json, false);
}

export function PresetFXDepreciationPctToJSONTyped(
  value?: PresetFXDepreciationPct | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
