/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PriorValue1
 */
export type PriorValue1 = number | string | null;

/**
 * Check if a given object implements the PriorValue1 interface.
 */
export function instanceOfPriorValue1(value: unknown): value is PriorValue1 {
  return (
    typeof value === "number" || typeof value === "string" || value === null
  );
}

export function PriorValue1FromJSON(json: any): PriorValue1 {
  return PriorValue1FromJSONTyped(json, false);
}

export function PriorValue1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PriorValue1 {
  return json;
}

export function PriorValue1ToJSON(json: any): PriorValue1 {
  return PriorValue1ToJSONTyped(json, false);
}

export function PriorValue1ToJSONTyped(
  value?: PriorValue1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
