/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ProjectionYearROEPct } from "./ProjectionYearROEPct";
import {
  ProjectionYearROEPctFromJSON,
  ProjectionYearROEPctFromJSONTyped,
  ProjectionYearROEPctToJSON,
  ProjectionYearROEPctToJSONTyped,
} from "./ProjectionYearROEPct";

/**
 *
 * @export
 * @interface ProjectionYearRead
 */
export interface ProjectionYearRead {
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  borrowingsPlug: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  carPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  cash: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  cet1RatioPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  creditLosses: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  deposits: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  dividends: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  equity: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  fees: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  lcrPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  loans: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  netIncome: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  nii: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  nsfrPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  opex: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  periodLabel: string;
  /**
   *
   * @type {ProjectionYearROEPct}
   * @memberof ProjectionYearRead
   */
  roePct: ProjectionYearROEPct;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  securities: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  tier1RatioPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  totalAssets: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionYearRead
   */
  totalIncome: string;
  /**
   *
   * @type {number}
   * @memberof ProjectionYearRead
   */
  year: number;
}

/**
 * Check if a given object implements the ProjectionYearRead interface.
 */
export function instanceOfProjectionYearRead(
  value: object,
): value is ProjectionYearRead {
  if (!("borrowingsPlug" in value) || value["borrowingsPlug"] === undefined)
    return false;
  if (!("carPct" in value) || value["carPct"] === undefined) return false;
  if (!("cash" in value) || value["cash"] === undefined) return false;
  if (!("cet1RatioPct" in value) || value["cet1RatioPct"] === undefined)
    return false;
  if (!("creditLosses" in value) || value["creditLosses"] === undefined)
    return false;
  if (!("deposits" in value) || value["deposits"] === undefined) return false;
  if (!("dividends" in value) || value["dividends"] === undefined) return false;
  if (!("equity" in value) || value["equity"] === undefined) return false;
  if (!("fees" in value) || value["fees"] === undefined) return false;
  if (!("lcrPct" in value) || value["lcrPct"] === undefined) return false;
  if (!("loans" in value) || value["loans"] === undefined) return false;
  if (!("netIncome" in value) || value["netIncome"] === undefined) return false;
  if (!("nii" in value) || value["nii"] === undefined) return false;
  if (!("nsfrPct" in value) || value["nsfrPct"] === undefined) return false;
  if (!("opex" in value) || value["opex"] === undefined) return false;
  if (!("periodLabel" in value) || value["periodLabel"] === undefined)
    return false;
  if (!("roePct" in value) || value["roePct"] === undefined) return false;
  if (!("securities" in value) || value["securities"] === undefined)
    return false;
  if (!("tier1RatioPct" in value) || value["tier1RatioPct"] === undefined)
    return false;
  if (!("totalAssets" in value) || value["totalAssets"] === undefined)
    return false;
  if (!("totalIncome" in value) || value["totalIncome"] === undefined)
    return false;
  if (!("year" in value) || value["year"] === undefined) return false;
  return true;
}

export function ProjectionYearReadFromJSON(json: any): ProjectionYearRead {
  return ProjectionYearReadFromJSONTyped(json, false);
}

export function ProjectionYearReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectionYearRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    borrowingsPlug: json["borrowings_plug"],
    carPct: json["car_pct"],
    cash: json["cash"],
    cet1RatioPct: json["cet1_ratio_pct"],
    creditLosses: json["credit_losses"],
    deposits: json["deposits"],
    dividends: json["dividends"],
    equity: json["equity"],
    fees: json["fees"],
    lcrPct: json["lcr_pct"],
    loans: json["loans"],
    netIncome: json["net_income"],
    nii: json["nii"],
    nsfrPct: json["nsfr_pct"],
    opex: json["opex"],
    periodLabel: json["period_label"],
    roePct: ProjectionYearROEPctFromJSON(json["roe_pct"]),
    securities: json["securities"],
    tier1RatioPct: json["tier1_ratio_pct"],
    totalAssets: json["total_assets"],
    totalIncome: json["total_income"],
    year: json["year"],
  };
}

export function ProjectionYearReadToJSON(json: any): ProjectionYearRead {
  return ProjectionYearReadToJSONTyped(json, false);
}

export function ProjectionYearReadToJSONTyped(
  value?: ProjectionYearRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    borrowings_plug: value["borrowingsPlug"],
    car_pct: value["carPct"],
    cash: value["cash"],
    cet1_ratio_pct: value["cet1RatioPct"],
    credit_losses: value["creditLosses"],
    deposits: value["deposits"],
    dividends: value["dividends"],
    equity: value["equity"],
    fees: value["fees"],
    lcr_pct: value["lcrPct"],
    loans: value["loans"],
    net_income: value["netIncome"],
    nii: value["nii"],
    nsfr_pct: value["nsfrPct"],
    opex: value["opex"],
    period_label: value["periodLabel"],
    roe_pct: ProjectionYearROEPctToJSON(value["roePct"]),
    securities: value["securities"],
    tier1_ratio_pct: value["tier1RatioPct"],
    total_assets: value["totalAssets"],
    total_income: value["totalIncome"],
    year: value["year"],
  };
}
