/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ProjectionSummaryRead
 */
export interface ProjectionSummaryRead {
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  avgRoePct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  cumulativeNetIncome: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  minCarPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  minLcrPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  minNsfrPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  year5CarPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  year5LcrPct: string;
  /**
   *
   * @type {string}
   * @memberof ProjectionSummaryRead
   */
  year5NsfrPct: string;
}

/**
 * Check if a given object implements the ProjectionSummaryRead interface.
 */
export function instanceOfProjectionSummaryRead(
  value: object,
): value is ProjectionSummaryRead {
  if (!("avgRoePct" in value) || value["avgRoePct"] === undefined) return false;
  if (
    !("cumulativeNetIncome" in value) ||
    value["cumulativeNetIncome"] === undefined
  )
    return false;
  if (!("minCarPct" in value) || value["minCarPct"] === undefined) return false;
  if (!("minLcrPct" in value) || value["minLcrPct"] === undefined) return false;
  if (!("minNsfrPct" in value) || value["minNsfrPct"] === undefined)
    return false;
  if (!("year5CarPct" in value) || value["year5CarPct"] === undefined)
    return false;
  if (!("year5LcrPct" in value) || value["year5LcrPct"] === undefined)
    return false;
  if (!("year5NsfrPct" in value) || value["year5NsfrPct"] === undefined)
    return false;
  return true;
}

export function ProjectionSummaryReadFromJSON(
  json: any,
): ProjectionSummaryRead {
  return ProjectionSummaryReadFromJSONTyped(json, false);
}

export function ProjectionSummaryReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProjectionSummaryRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    avgRoePct: json["avg_roe_pct"],
    cumulativeNetIncome: json["cumulative_net_income"],
    minCarPct: json["min_car_pct"],
    minLcrPct: json["min_lcr_pct"],
    minNsfrPct: json["min_nsfr_pct"],
    year5CarPct: json["year5_car_pct"],
    year5LcrPct: json["year5_lcr_pct"],
    year5NsfrPct: json["year5_nsfr_pct"],
  };
}

export function ProjectionSummaryReadToJSON(json: any): ProjectionSummaryRead {
  return ProjectionSummaryReadToJSONTyped(json, false);
}

export function ProjectionSummaryReadToJSONTyped(
  value?: ProjectionSummaryRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    avg_roe_pct: value["avgRoePct"],
    cumulative_net_income: value["cumulativeNetIncome"],
    min_car_pct: value["minCarPct"],
    min_lcr_pct: value["minLcrPct"],
    min_nsfr_pct: value["minNsfrPct"],
    year5_car_pct: value["year5CarPct"],
    year5_lcr_pct: value["year5LcrPct"],
    year5_nsfr_pct: value["year5NsfrPct"],
  };
}
