/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProposalReason
 */
export type ProposalReason = string | null;

/**
 * Check if a given object implements the ProposalReason interface.
 */
export function instanceOfProposalReason(
  value: unknown,
): value is ProposalReason {
  return typeof value === "string" || value === null;
}

export function ProposalReasonFromJSON(json: any): ProposalReason {
  return ProposalReasonFromJSONTyped(json, false);
}

export function ProposalReasonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ProposalReason {
  return json;
}

export function ProposalReasonToJSON(json: any): ProposalReason {
  return ProposalReasonToJSONTyped(json, false);
}

export function ProposalReasonToJSONTyped(
  value?: ProposalReason | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
