/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApprovedByUserId } from "./ApprovedByUserId";
import {
  ApprovedByUserIdFromJSON,
  ApprovedByUserIdFromJSONTyped,
  ApprovedByUserIdToJSON,
  ApprovedByUserIdToJSONTyped,
} from "./ApprovedByUserId";
import type { EffectiveTo } from "./EffectiveTo";
import {
  EffectiveToFromJSON,
  EffectiveToFromJSONTyped,
  EffectiveToToJSON,
  EffectiveToToJSONTyped,
} from "./EffectiveTo";
import type { MaxGapFraction } from "./MaxGapFraction";
import {
  MaxGapFractionFromJSON,
  MaxGapFractionFromJSONTyped,
  MaxGapFractionToJSON,
  MaxGapFractionToJSONTyped,
} from "./MaxGapFraction";

/**
 * Record an approved exception to a fail-closed reconciliation control.
 *
 * Four-eyes is enforced in the service (``grant_exception``): the officer who
 * requested the exception may not be the approver. ``approved_by_user_id`` is
 * what makes that check possible, so supplying it is how a caller proves the
 * second pair of eyes exists rather than asserting it.
 * @export
 * @interface ReconciliationExceptionCreate
 */
export interface ReconciliationExceptionCreate {
  /**
   *
   * @type {string}
   * @memberof ReconciliationExceptionCreate
   */
  approvedBy: string;
  /**
   *
   * @type {ApprovedByUserId}
   * @memberof ReconciliationExceptionCreate
   */
  approvedByUserId?: ApprovedByUserId;
  /**
   *
   * @type {Date}
   * @memberof ReconciliationExceptionCreate
   */
  effectiveFrom: Date;
  /**
   *
   * @type {EffectiveTo}
   * @memberof ReconciliationExceptionCreate
   */
  effectiveTo?: EffectiveTo;
  /**
   *
   * @type {MaxGapFraction}
   * @memberof ReconciliationExceptionCreate
   */
  maxGapFraction: MaxGapFraction;
  /**
   *
   * @type {string}
   * @memberof ReconciliationExceptionCreate
   */
  reason: string;
}

/**
 * Check if a given object implements the ReconciliationExceptionCreate interface.
 */
export function instanceOfReconciliationExceptionCreate(
  value: object,
): value is ReconciliationExceptionCreate {
  if (!("approvedBy" in value) || value["approvedBy"] === undefined)
    return false;
  if (!("effectiveFrom" in value) || value["effectiveFrom"] === undefined)
    return false;
  if (!("maxGapFraction" in value) || value["maxGapFraction"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function ReconciliationExceptionCreateFromJSON(
  json: any,
): ReconciliationExceptionCreate {
  return ReconciliationExceptionCreateFromJSONTyped(json, false);
}

export function ReconciliationExceptionCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReconciliationExceptionCreate {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    approvedBy: json["approved_by"],
    approvedByUserId:
      json["approved_by_user_id"] == null
        ? undefined
        : ApprovedByUserIdFromJSON(json["approved_by_user_id"]),
    effectiveFrom: new Date(json["effective_from"]),
    effectiveTo:
      json["effective_to"] == null
        ? undefined
        : EffectiveToFromJSON(json["effective_to"]),
    maxGapFraction: MaxGapFractionFromJSON(json["max_gap_fraction"]),
    reason: json["reason"],
  };
}

export function ReconciliationExceptionCreateToJSON(
  json: any,
): ReconciliationExceptionCreate {
  return ReconciliationExceptionCreateToJSONTyped(json, false);
}

export function ReconciliationExceptionCreateToJSONTyped(
  value?: ReconciliationExceptionCreate | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    approved_by: value["approvedBy"],
    approved_by_user_id: ApprovedByUserIdToJSON(value["approvedByUserId"]),
    effective_from: value["effectiveFrom"].toISOString().substring(0, 10),
    effective_to: EffectiveToToJSON(value["effectiveTo"]),
    max_gap_fraction: MaxGapFractionToJSON(value["maxGapFraction"]),
    reason: value["reason"],
  };
}
