/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RecoveryPlanReference1
 */
export type RecoveryPlanReference1 = string | null;

/**
 * Check if a given object implements the RecoveryPlanReference1 interface.
 */
export function instanceOfRecoveryPlanReference1(
  value: unknown,
): value is RecoveryPlanReference1 {
  return typeof value === "string" || value === null;
}

export function RecoveryPlanReference1FromJSON(
  json: any,
): RecoveryPlanReference1 {
  return RecoveryPlanReference1FromJSONTyped(json, false);
}

export function RecoveryPlanReference1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RecoveryPlanReference1 {
  return json;
}

export function RecoveryPlanReference1ToJSON(
  json: any,
): RecoveryPlanReference1 {
  return RecoveryPlanReference1ToJSONTyped(json, false);
}

export function RecoveryPlanReference1ToJSONTyped(
  value?: RecoveryPlanReference1 | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
