/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegisterStateDigest
 */
export type RegisterStateDigest = string | null;

/**
 * Check if a given object implements the RegisterStateDigest interface.
 */
export function instanceOfRegisterStateDigest(
  value: unknown,
): value is RegisterStateDigest {
  return typeof value === "string" || value === null;
}

export function RegisterStateDigestFromJSON(json: any): RegisterStateDigest {
  return RegisterStateDigestFromJSONTyped(json, false);
}

export function RegisterStateDigestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegisterStateDigest {
  return json;
}

export function RegisterStateDigestToJSON(json: any): RegisterStateDigest {
  return RegisterStateDigestToJSONTyped(json, false);
}

export function RegisterStateDigestToJSONTyped(
  value?: RegisterStateDigest | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
