/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ArtifactKind } from "./ArtifactKind";
import {
  ArtifactKindFromJSON,
  ArtifactKindFromJSONTyped,
  ArtifactKindToJSON,
  ArtifactKindToJSONTyped,
} from "./ArtifactKind";

/**
 *
 * @export
 * @interface RegulatoryArtifactRead
 */
export interface RegulatoryArtifactRead {
  /**
   *
   * @type {string}
   * @memberof RegulatoryArtifactRead
   */
  checksumSha256: string;
  /**
   *
   * @type {Date}
   * @memberof RegulatoryArtifactRead
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof RegulatoryArtifactRead
   */
  id: string;
  /**
   *
   * @type {ArtifactKind}
   * @memberof RegulatoryArtifactRead
   */
  kind: ArtifactKind;
  /**
   *
   * @type {string}
   * @memberof RegulatoryArtifactRead
   */
  objectPath: string;
  /**
   *
   * @type {string}
   * @memberof RegulatoryArtifactRead
   */
  packageId: string;
  /**
   *
   * @type {number}
   * @memberof RegulatoryArtifactRead
   */
  sizeBytes: number;
}

/**
 * Check if a given object implements the RegulatoryArtifactRead interface.
 */
export function instanceOfRegulatoryArtifactRead(
  value: object,
): value is RegulatoryArtifactRead {
  if (!("checksumSha256" in value) || value["checksumSha256"] === undefined)
    return false;
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("id" in value) || value["id"] === undefined) return false;
  if (!("kind" in value) || value["kind"] === undefined) return false;
  if (!("objectPath" in value) || value["objectPath"] === undefined)
    return false;
  if (!("packageId" in value) || value["packageId"] === undefined) return false;
  if (!("sizeBytes" in value) || value["sizeBytes"] === undefined) return false;
  return true;
}

export function RegulatoryArtifactReadFromJSON(
  json: any,
): RegulatoryArtifactRead {
  return RegulatoryArtifactReadFromJSONTyped(json, false);
}

export function RegulatoryArtifactReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegulatoryArtifactRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    checksumSha256: json["checksum_sha256"],
    createdAt: new Date(json["created_at"]),
    id: json["id"],
    kind: ArtifactKindFromJSON(json["kind"]),
    objectPath: json["object_path"],
    packageId: json["package_id"],
    sizeBytes: json["size_bytes"],
  };
}

export function RegulatoryArtifactReadToJSON(
  json: any,
): RegulatoryArtifactRead {
  return RegulatoryArtifactReadToJSONTyped(json, false);
}

export function RegulatoryArtifactReadToJSONTyped(
  value?: RegulatoryArtifactRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    checksum_sha256: value["checksumSha256"],
    created_at: value["createdAt"].toISOString(),
    id: value["id"],
    kind: ArtifactKindToJSON(value["kind"]),
    object_path: value["objectPath"],
    package_id: value["packageId"],
    size_bytes: value["sizeBytes"],
  };
}
