/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RelocatedFrom
 */
export type RelocatedFrom = string | null;

/**
 * Check if a given object implements the RelocatedFrom interface.
 */
export function instanceOfRelocatedFrom(
  value: unknown,
): value is RelocatedFrom {
  return typeof value === "string" || value === null;
}

export function RelocatedFromFromJSON(json: any): RelocatedFrom {
  return RelocatedFromFromJSONTyped(json, false);
}

export function RelocatedFromFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RelocatedFrom {
  return json;
}

export function RelocatedFromToJSON(json: any): RelocatedFrom {
  return RelocatedFromToJSONTyped(json, false);
}

export function RelocatedFromToJSONTyped(
  value?: RelocatedFrom | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
