/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ReportDecision
 */
export interface ReportDecision {
  /**
   *
   * @type {Date}
   * @memberof ReportDecision
   */
  createdAt: Date;
  /**
   *
   * @type {string}
   * @memberof ReportDecision
   */
  decidedBy: string | null;
  /**
   *
   * @type {string}
   * @memberof ReportDecision
   */
  decision: string;
  /**
   *
   * @type {string}
   * @memberof ReportDecision
   */
  previousDecision: string | null;
  /**
   *
   * @type {string}
   * @memberof ReportDecision
   */
  reason: string | null;
}

/**
 * Check if a given object implements the ReportDecision interface.
 */
export function instanceOfReportDecision(
  value: object,
): value is ReportDecision {
  if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
  if (!("decidedBy" in value) || value["decidedBy"] === undefined) return false;
  if (!("decision" in value) || value["decision"] === undefined) return false;
  if (!("previousDecision" in value) || value["previousDecision"] === undefined)
    return false;
  if (!("reason" in value) || value["reason"] === undefined) return false;
  return true;
}

export function ReportDecisionFromJSON(json: any): ReportDecision {
  return ReportDecisionFromJSONTyped(json, false);
}

export function ReportDecisionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReportDecision {
  if (json == null) {
    return json;
  }
  return {
    createdAt: new Date(json["created_at"]),
    decidedBy: json["decided_by"],
    decision: json["decision"],
    previousDecision: json["previous_decision"],
    reason: json["reason"],
  };
}

export function ReportDecisionToJSON(json: any): ReportDecision {
  return ReportDecisionToJSONTyped(json, false);
}

export function ReportDecisionToJSONTyped(
  value?: ReportDecision | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: value["createdAt"].toISOString(),
    decided_by: value["decidedBy"],
    decision: value["decision"],
    previous_decision: value["previousDecision"],
    reason: value["reason"],
  };
}
