/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ComparisonSideRead } from "./ComparisonSideRead";
import {
  ComparisonSideReadFromJSON,
  ComparisonSideReadFromJSONTyped,
  ComparisonSideReadToJSON,
  ComparisonSideReadToJSONTyped,
} from "./ComparisonSideRead";
import type { ComparisonGroupRead } from "./ComparisonGroupRead";
import {
  ComparisonGroupReadFromJSON,
  ComparisonGroupReadFromJSONTyped,
  ComparisonGroupReadToJSON,
  ComparisonGroupReadToJSONTyped,
} from "./ComparisonGroupRead";

/**
 *
 * @export
 * @interface ReportComparisonRead
 */
export interface ReportComparisonRead {
  /**
   *
   * @type {number}
   * @memberof ReportComparisonRead
   */
  adverseCount: number;
  /**
   *
   * @type {number}
   * @memberof ReportComparisonRead
   */
  favorableCount: number;
  /**
   *
   * @type {Array<ComparisonGroupRead>}
   * @memberof ReportComparisonRead
   */
  groups: Array<ComparisonGroupRead>;
  /**
   *
   * @type {ComparisonSideRead}
   * @memberof ReportComparisonRead
   */
  left: ComparisonSideRead;
  /**
   *
   * @type {string}
   * @memberof ReportComparisonRead
   */
  mode: ReportComparisonReadModeEnum;
  /**
   *
   * @type {string}
   * @memberof ReportComparisonRead
   */
  module: ReportComparisonReadModuleEnum;
  /**
   *
   * @type {number}
   * @memberof ReportComparisonRead
   */
  neutralCount: number;
  /**
   *
   * @type {ComparisonSideRead}
   * @memberof ReportComparisonRead
   */
  right: ComparisonSideRead;
}

/**
 * @export
 */
export const ReportComparisonReadModeEnum = {
  Version: "version",
  Period: "period",
} as const;
export type ReportComparisonReadModeEnum =
  (typeof ReportComparisonReadModeEnum)[keyof typeof ReportComparisonReadModeEnum];

/**
 * @export
 */
export const ReportComparisonReadModuleEnum = {
  Liquidity: "liquidity",
  Capital: "capital",
  Irr: "irr",
  Fx: "fx",
  Ftp: "ftp",
  Forecast: "forecast",
} as const;
export type ReportComparisonReadModuleEnum =
  (typeof ReportComparisonReadModuleEnum)[keyof typeof ReportComparisonReadModuleEnum];

/**
 * Check if a given object implements the ReportComparisonRead interface.
 */
export function instanceOfReportComparisonRead(
  value: object,
): value is ReportComparisonRead {
  if (!("adverseCount" in value) || value["adverseCount"] === undefined)
    return false;
  if (!("favorableCount" in value) || value["favorableCount"] === undefined)
    return false;
  if (!("groups" in value) || value["groups"] === undefined) return false;
  if (!("left" in value) || value["left"] === undefined) return false;
  if (!("mode" in value) || value["mode"] === undefined) return false;
  if (!("module" in value) || value["module"] === undefined) return false;
  if (!("neutralCount" in value) || value["neutralCount"] === undefined)
    return false;
  if (!("right" in value) || value["right"] === undefined) return false;
  return true;
}

export function ReportComparisonReadFromJSON(json: any): ReportComparisonRead {
  return ReportComparisonReadFromJSONTyped(json, false);
}

export function ReportComparisonReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReportComparisonRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    adverseCount: json["adverse_count"],
    favorableCount: json["favorable_count"],
    groups: (json["groups"] as Array<any>).map(ComparisonGroupReadFromJSON),
    left: ComparisonSideReadFromJSON(json["left"]),
    mode: json["mode"],
    module: json["module"],
    neutralCount: json["neutral_count"],
    right: ComparisonSideReadFromJSON(json["right"]),
  };
}

export function ReportComparisonReadToJSON(json: any): ReportComparisonRead {
  return ReportComparisonReadToJSONTyped(json, false);
}

export function ReportComparisonReadToJSONTyped(
  value?: ReportComparisonRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    adverse_count: value["adverseCount"],
    favorable_count: value["favorableCount"],
    groups: (value["groups"] as Array<any>).map(ComparisonGroupReadToJSON),
    left: ComparisonSideReadToJSON(value["left"]),
    mode: value["mode"],
    module: value["module"],
    neutral_count: value["neutralCount"],
    right: ComparisonSideReadToJSON(value["right"]),
  };
}
