/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { CoverageNote } from "./CoverageNote";
import {
  CoverageNoteFromJSON,
  CoverageNoteFromJSONTyped,
  CoverageNoteToJSON,
  CoverageNoteToJSONTyped,
} from "./CoverageNote";
import type { ReportingObligationRead } from "./ReportingObligationRead";
import {
  ReportingObligationReadFromJSON,
  ReportingObligationReadFromJSONTyped,
  ReportingObligationReadToJSON,
  ReportingObligationReadToJSONTyped,
} from "./ReportingObligationRead";
import type { ReportingObligationSummaryRead } from "./ReportingObligationSummaryRead";
import {
  ReportingObligationSummaryReadFromJSON,
  ReportingObligationSummaryReadFromJSONTyped,
  ReportingObligationSummaryReadToJSON,
  ReportingObligationSummaryReadToJSONTyped,
} from "./ReportingObligationSummaryRead";

/**
 *
 * @export
 * @interface ReportingObligationListRead
 */
export interface ReportingObligationListRead {
  /**
   *
   * @type {Date}
   * @memberof ReportingObligationListRead
   */
  asOf: Date;
  /**
   *
   * @type {string}
   * @memberof ReportingObligationListRead
   */
  bankId: string;
  /**
   *
   * @type {CoverageNote}
   * @memberof ReportingObligationListRead
   */
  coverageNote?: CoverageNote;
  /**
   *
   * @type {boolean}
   * @memberof ReportingObligationListRead
   */
  hasMore: boolean;
  /**
   *
   * @type {number}
   * @memberof ReportingObligationListRead
   */
  horizonMonths: number;
  /**
   *
   * @type {number}
   * @memberof ReportingObligationListRead
   */
  limit: number;
  /**
   *
   * @type {Array<ReportingObligationRead>}
   * @memberof ReportingObligationListRead
   */
  obligations: Array<ReportingObligationRead>;
  /**
   *
   * @type {number}
   * @memberof ReportingObligationListRead
   */
  offset: number;
  /**
   *
   * @type {ReportingObligationSummaryRead}
   * @memberof ReportingObligationListRead
   */
  summary: ReportingObligationSummaryRead;
  /**
   *
   * @type {number}
   * @memberof ReportingObligationListRead
   */
  total: number;
}

/**
 * Check if a given object implements the ReportingObligationListRead interface.
 */
export function instanceOfReportingObligationListRead(
  value: object,
): value is ReportingObligationListRead {
  if (!("asOf" in value) || value["asOf"] === undefined) return false;
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("hasMore" in value) || value["hasMore"] === undefined) return false;
  if (!("horizonMonths" in value) || value["horizonMonths"] === undefined)
    return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("obligations" in value) || value["obligations"] === undefined)
    return false;
  if (!("offset" in value) || value["offset"] === undefined) return false;
  if (!("summary" in value) || value["summary"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  return true;
}

export function ReportingObligationListReadFromJSON(
  json: any,
): ReportingObligationListRead {
  return ReportingObligationListReadFromJSONTyped(json, false);
}

export function ReportingObligationListReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ReportingObligationListRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    asOf: new Date(json["as_of"]),
    bankId: json["bank_id"],
    coverageNote:
      json["coverage_note"] == null
        ? undefined
        : CoverageNoteFromJSON(json["coverage_note"]),
    hasMore: json["has_more"],
    horizonMonths: json["horizon_months"],
    limit: json["limit"],
    obligations: (json["obligations"] as Array<any>).map(
      ReportingObligationReadFromJSON,
    ),
    offset: json["offset"],
    summary: ReportingObligationSummaryReadFromJSON(json["summary"]),
    total: json["total"],
  };
}

export function ReportingObligationListReadToJSON(
  json: any,
): ReportingObligationListRead {
  return ReportingObligationListReadToJSONTyped(json, false);
}

export function ReportingObligationListReadToJSONTyped(
  value?: ReportingObligationListRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    as_of: value["asOf"].toISOString().substring(0, 10),
    bank_id: value["bankId"],
    coverage_note: CoverageNoteToJSON(value["coverageNote"]),
    has_more: value["hasMore"],
    horizon_months: value["horizonMonths"],
    limit: value["limit"],
    obligations: (value["obligations"] as Array<any>).map(
      ReportingObligationReadToJSON,
    ),
    offset: value["offset"],
    summary: ReportingObligationSummaryReadToJSON(value["summary"]),
    total: value["total"],
  };
}
