/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RevokedAt
 */
export type RevokedAt = string | null;

/**
 * Check if a given object implements the RevokedAt interface.
 */
export function instanceOfRevokedAt(value: unknown): value is RevokedAt {
  return typeof value === "string" || value === null;
}

export function RevokedAtFromJSON(json: any): RevokedAt {
  return RevokedAtFromJSONTyped(json, false);
}

export function RevokedAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RevokedAt {
  return json;
}

export function RevokedAtToJSON(json: any): RevokedAt {
  return RevokedAtToJSONTyped(json, false);
}

export function RevokedAtToJSONTyped(
  value?: RevokedAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
