/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Rhs
 */
export type Rhs = string | null;

/**
 * Check if a given object implements the Rhs interface.
 */
export function instanceOfRhs(value: unknown): value is Rhs {
  return typeof value === "string" || value === null;
}

export function RhsFromJSON(json: any): Rhs {
  return RhsFromJSONTyped(json, false);
}

export function RhsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rhs {
  return json;
}

export function RhsToJSON(json: any): Rhs {
  return RhsToJSONTyped(json, false);
}

export function RhsToJSONTyped(
  value?: Rhs | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
