/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SavedAnalysisSummaryRead } from "./SavedAnalysisSummaryRead";
import {
  SavedAnalysisSummaryReadFromJSON,
  SavedAnalysisSummaryReadFromJSONTyped,
  SavedAnalysisSummaryReadToJSON,
  SavedAnalysisSummaryReadToJSONTyped,
} from "./SavedAnalysisSummaryRead";

/**
 *
 * @export
 * @interface SavedAnalysisListRead
 */
export interface SavedAnalysisListRead {
  /**
   *
   * @type {Array<SavedAnalysisSummaryRead>}
   * @memberof SavedAnalysisListRead
   */
  analyses: Array<SavedAnalysisSummaryRead>;
  /**
   *
   * @type {number}
   * @memberof SavedAnalysisListRead
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof SavedAnalysisListRead
   */
  offset: number;
  /**
   *
   * @type {number}
   * @memberof SavedAnalysisListRead
   */
  total: number;
}

/**
 * Check if a given object implements the SavedAnalysisListRead interface.
 */
export function instanceOfSavedAnalysisListRead(
  value: object,
): value is SavedAnalysisListRead {
  if (!("analyses" in value) || value["analyses"] === undefined) return false;
  if (!("limit" in value) || value["limit"] === undefined) return false;
  if (!("offset" in value) || value["offset"] === undefined) return false;
  if (!("total" in value) || value["total"] === undefined) return false;
  return true;
}

export function SavedAnalysisListReadFromJSON(
  json: any,
): SavedAnalysisListRead {
  return SavedAnalysisListReadFromJSONTyped(json, false);
}

export function SavedAnalysisListReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SavedAnalysisListRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    analyses: (json["analyses"] as Array<any>).map(
      SavedAnalysisSummaryReadFromJSON,
    ),
    limit: json["limit"],
    offset: json["offset"],
    total: json["total"],
  };
}

export function SavedAnalysisListReadToJSON(json: any): SavedAnalysisListRead {
  return SavedAnalysisListReadToJSONTyped(json, false);
}

export function SavedAnalysisListReadToJSONTyped(
  value?: SavedAnalysisListRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    analyses: (value["analyses"] as Array<any>).map(
      SavedAnalysisSummaryReadToJSON,
    ),
    limit: value["limit"],
    offset: value["offset"],
    total: value["total"],
  };
}
