/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ScenarioId
 */
export type ScenarioId = string | null;

/**
 * Check if a given object implements the ScenarioId interface.
 */
export function instanceOfScenarioId(value: unknown): value is ScenarioId {
  return typeof value === "string" || value === null;
}

export function ScenarioIdFromJSON(json: any): ScenarioId {
  return ScenarioIdFromJSONTyped(json, false);
}

export function ScenarioIdFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ScenarioId {
  return json;
}

export function ScenarioIdToJSON(json: any): ScenarioId {
  return ScenarioIdToJSONTyped(json, false);
}

export function ScenarioIdToJSONTyped(
  value?: ScenarioId | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
