/* tslint:disable */
/* eslint-disable */
/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ScenarioReadinessRead
 */
export interface ScenarioReadinessRead {
  /**
   *
   * @type {string}
   * @memberof ScenarioReadinessRead
   */
  caseId: string;
  /**
   *
   * @type {number}
   * @memberof ScenarioReadinessRead
   */
  completeScenarioCount: number;
  /**
   *
   * @type {Array<string>}
   * @memberof ScenarioReadinessRead
   */
  incompleteScenarioIds: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof ScenarioReadinessRead
   */
  ready: boolean;
  /**
   *
   * @type {number}
   * @memberof ScenarioReadinessRead
   */
  scenarioCount: number;
}

/**
 * Check if a given object implements the ScenarioReadinessRead interface.
 */
export function instanceOfScenarioReadinessRead(
  value: object,
): value is ScenarioReadinessRead {
  if (!("caseId" in value) || value["caseId"] === undefined) return false;
  if (
    !("completeScenarioCount" in value) ||
    value["completeScenarioCount"] === undefined
  )
    return false;
  if (
    !("incompleteScenarioIds" in value) ||
    value["incompleteScenarioIds"] === undefined
  )
    return false;
  if (!("ready" in value) || value["ready"] === undefined) return false;
  if (!("scenarioCount" in value) || value["scenarioCount"] === undefined)
    return false;
  return true;
}

export function ScenarioReadinessReadFromJSON(
  json: any,
): ScenarioReadinessRead {
  return ScenarioReadinessReadFromJSONTyped(json, false);
}

export function ScenarioReadinessReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ScenarioReadinessRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    caseId: json["case_id"],
    completeScenarioCount: json["complete_scenario_count"],
    incompleteScenarioIds: json["incomplete_scenario_ids"],
    ready: json["ready"],
    scenarioCount: json["scenario_count"],
  };
}

export function ScenarioReadinessReadToJSON(json: any): ScenarioReadinessRead {
  return ScenarioReadinessReadToJSONTyped(json, false);
}

export function ScenarioReadinessReadToJSONTyped(
  value?: ScenarioReadinessRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    case_id: value["caseId"],
    complete_scenario_count: value["completeScenarioCount"],
    incomplete_scenario_ids: value["incompleteScenarioIds"],
    ready: value["ready"],
    scenario_count: value["scenarioCount"],
  };
}
