/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SeverityFactorsAnyOfValue } from "./SeverityFactorsAnyOfValue";
import {
  SeverityFactorsAnyOfValueFromJSON,
  SeverityFactorsAnyOfValueFromJSONTyped,
  SeverityFactorsAnyOfValueToJSON,
  SeverityFactorsAnyOfValueToJSONTyped,
} from "./SeverityFactorsAnyOfValue";

/**
 *
 * @export
 * @interface SeverityFactors
 */
export type SeverityFactors = { [key: string]: any } | null;

/**
 * Check if a given object implements the SeverityFactors interface.
 */
export function instanceOfSeverityFactors(
  value: unknown,
): value is SeverityFactors {
  return (
    (typeof value === "object" && value !== null && !Array.isArray(value)) ||
    value === null
  );
}

export function SeverityFactorsFromJSON(json: any): SeverityFactors {
  return SeverityFactorsFromJSONTyped(json, false);
}

export function SeverityFactorsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SeverityFactors {
  return json;
}

export function SeverityFactorsToJSON(json: any): SeverityFactors {
  return SeverityFactorsToJSONTyped(json, false);
}

export function SeverityFactorsToJSONTyped(
  value?: SeverityFactors | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
