/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SnapshotLineDiffRead } from "./SnapshotLineDiffRead";
import {
  SnapshotLineDiffReadFromJSON,
  SnapshotLineDiffReadFromJSONTyped,
  SnapshotLineDiffReadToJSON,
  SnapshotLineDiffReadToJSONTyped,
} from "./SnapshotLineDiffRead";
import type { SnapshotSectionChange } from "./SnapshotSectionChange";
import {
  SnapshotSectionChangeFromJSON,
  SnapshotSectionChangeFromJSONTyped,
  SnapshotSectionChangeToJSON,
  SnapshotSectionChangeToJSONTyped,
} from "./SnapshotSectionChange";
import type { SnapshotSectionOrigin } from "./SnapshotSectionOrigin";
import {
  SnapshotSectionOriginFromJSON,
  SnapshotSectionOriginFromJSONTyped,
  SnapshotSectionOriginToJSON,
  SnapshotSectionOriginToJSONTyped,
} from "./SnapshotSectionOrigin";

/**
 *
 * @export
 * @interface SnapshotSectionDiffRead
 */
export interface SnapshotSectionDiffRead {
  /**
   *
   * @type {SnapshotSectionChange}
   * @memberof SnapshotSectionDiffRead
   */
  change: SnapshotSectionChange;
  /**
   *
   * @type {string}
   * @memberof SnapshotSectionDiffRead
   */
  code: string;
  /**
   *
   * @type {Array<SnapshotLineDiffRead>}
   * @memberof SnapshotSectionDiffRead
   */
  lines: Array<SnapshotLineDiffRead>;
  /**
   *
   * @type {SnapshotSectionOrigin}
   * @memberof SnapshotSectionDiffRead
   */
  origin: SnapshotSectionOrigin;
  /**
   *
   * @type {string}
   * @memberof SnapshotSectionDiffRead
   */
  title: string;
  /**
   *
   * @type {number}
   * @memberof SnapshotSectionDiffRead
   */
  unchangedLineCount: number;
}

/**
 * Check if a given object implements the SnapshotSectionDiffRead interface.
 */
export function instanceOfSnapshotSectionDiffRead(
  value: object,
): value is SnapshotSectionDiffRead {
  if (!("change" in value) || value["change"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("lines" in value) || value["lines"] === undefined) return false;
  if (!("origin" in value) || value["origin"] === undefined) return false;
  if (!("title" in value) || value["title"] === undefined) return false;
  if (
    !("unchangedLineCount" in value) ||
    value["unchangedLineCount"] === undefined
  )
    return false;
  return true;
}

export function SnapshotSectionDiffReadFromJSON(
  json: any,
): SnapshotSectionDiffRead {
  return SnapshotSectionDiffReadFromJSONTyped(json, false);
}

export function SnapshotSectionDiffReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SnapshotSectionDiffRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    change: SnapshotSectionChangeFromJSON(json["change"]),
    code: json["code"],
    lines: (json["lines"] as Array<any>).map(SnapshotLineDiffReadFromJSON),
    origin: SnapshotSectionOriginFromJSON(json["origin"]),
    title: json["title"],
    unchangedLineCount: json["unchanged_line_count"],
  };
}

export function SnapshotSectionDiffReadToJSON(
  json: any,
): SnapshotSectionDiffRead {
  return SnapshotSectionDiffReadToJSONTyped(json, false);
}

export function SnapshotSectionDiffReadToJSONTyped(
  value?: SnapshotSectionDiffRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    change: SnapshotSectionChangeToJSON(value["change"]),
    code: value["code"],
    lines: (value["lines"] as Array<any>).map(SnapshotLineDiffReadToJSON),
    origin: SnapshotSectionOriginToJSON(value["origin"]),
    title: value["title"],
    unchanged_line_count: value["unchangedLineCount"],
  };
}
