/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SodPolicyFindingRead
 */
export interface SodPolicyFindingRead {
  /**
   *
   * @type {string}
   * @memberof SodPolicyFindingRead
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof SodPolicyFindingRead
   */
  message: string;
}

/**
 * Check if a given object implements the SodPolicyFindingRead interface.
 */
export function instanceOfSodPolicyFindingRead(
  value: object,
): value is SodPolicyFindingRead {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  return true;
}

export function SodPolicyFindingReadFromJSON(json: any): SodPolicyFindingRead {
  return SodPolicyFindingReadFromJSONTyped(json, false);
}

export function SodPolicyFindingReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SodPolicyFindingRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    code: json["code"],
    message: json["message"],
  };
}

export function SodPolicyFindingReadToJSON(json: any): SodPolicyFindingRead {
  return SodPolicyFindingReadToJSONTyped(json, false);
}

export function SodPolicyFindingReadToJSONTyped(
  value?: SodPolicyFindingRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    message: value["message"],
  };
}
