/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SourcePack
 */
export type SourcePack = string | null;

/**
 * Check if a given object implements the SourcePack interface.
 */
export function instanceOfSourcePack(value: unknown): value is SourcePack {
  return typeof value === "string" || value === null;
}

export function SourcePackFromJSON(json: any): SourcePack {
  return SourcePackFromJSONTyped(json, false);
}

export function SourcePackFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SourcePack {
  return json;
}

export function SourcePackToJSON(json: any): SourcePack {
  return SourcePackToJSONTyped(json, false);
}

export function SourcePackToJSONTyped(
  value?: SourcePack | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
