/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StorageVersionId
 */
export type StorageVersionId = string | null;

/**
 * Check if a given object implements the StorageVersionId interface.
 */
export function instanceOfStorageVersionId(
  value: unknown,
): value is StorageVersionId {
  return typeof value === "string" || value === null;
}

export function StorageVersionIdFromJSON(json: any): StorageVersionId {
  return StorageVersionIdFromJSONTyped(json, false);
}

export function StorageVersionIdFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StorageVersionId {
  return json;
}

export function StorageVersionIdToJSON(json: any): StorageVersionId {
  return StorageVersionIdToJSONTyped(json, false);
}

export function StorageVersionIdToJSONTyped(
  value?: StorageVersionId | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
