/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const StressScenarioType = {
  Base: "base",
  Adverse: "adverse",
  Historical: "historical",
  Hypothetical: "hypothetical",
  Reverse: "reverse",
  Supervisory: "supervisory",
} as const;
export type StressScenarioType =
  (typeof StressScenarioType)[keyof typeof StressScenarioType];

export function instanceOfStressScenarioType(value: any): boolean {
  for (const key in StressScenarioType) {
    if (Object.prototype.hasOwnProperty.call(StressScenarioType, key)) {
      if (
        StressScenarioType[key as keyof typeof StressScenarioType] === value
      ) {
        return true;
      }
    }
  }
  return false;
}

export function StressScenarioTypeFromJSON(json: any): StressScenarioType {
  return StressScenarioTypeFromJSONTyped(json, false);
}

export function StressScenarioTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StressScenarioType {
  return json as StressScenarioType;
}

export function StressScenarioTypeToJSON(
  value?: StressScenarioType | null,
): any {
  return value as any;
}

export function StressScenarioTypeToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): StressScenarioType {
  return value as StressScenarioType;
}
