/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Supersedes
 */
export type Supersedes = string | null;

/**
 * Check if a given object implements the Supersedes interface.
 */
export function instanceOfSupersedes(value: unknown): value is Supersedes {
  return typeof value === "string" || value === null;
}

export function SupersedesFromJSON(json: any): Supersedes {
  return SupersedesFromJSONTyped(json, false);
}

export function SupersedesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Supersedes {
  return json;
}

export function SupersedesToJSON(json: any): Supersedes {
  return SupersedesToJSONTyped(json, false);
}

export function SupersedesToJSONTyped(
  value?: Supersedes | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
