/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TargetValue
 */
export type TargetValue = string | null;

/**
 * Check if a given object implements the TargetValue interface.
 */
export function instanceOfTargetValue(value: unknown): value is TargetValue {
  return typeof value === "string" || value === null;
}

export function TargetValueFromJSON(json: any): TargetValue {
  return TargetValueFromJSONTyped(json, false);
}

export function TargetValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TargetValue {
  return json;
}

export function TargetValueToJSON(json: any): TargetValue {
  return TargetValueToJSONTyped(json, false);
}

export function TargetValueToJSONTyped(
  value?: TargetValue | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
