/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 * The enqueued pull job(s).
 * @export
 * @interface TemenosPullTriggerRead
 */
export interface TemenosPullTriggerRead {
  /**
   *
   * @type {number}
   * @memberof TemenosPullTriggerRead
   */
  count: number;
  /**
   *
   * @type {Array<string>}
   * @memberof TemenosPullTriggerRead
   */
  jobIds: Array<string>;
}

/**
 * Check if a given object implements the TemenosPullTriggerRead interface.
 */
export function instanceOfTemenosPullTriggerRead(
  value: object,
): value is TemenosPullTriggerRead {
  if (!("count" in value) || value["count"] === undefined) return false;
  if (!("jobIds" in value) || value["jobIds"] === undefined) return false;
  return true;
}

export function TemenosPullTriggerReadFromJSON(
  json: any,
): TemenosPullTriggerRead {
  return TemenosPullTriggerReadFromJSONTyped(json, false);
}

export function TemenosPullTriggerReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TemenosPullTriggerRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    count: json["count"],
    jobIds: json["job_ids"],
  };
}

export function TemenosPullTriggerReadToJSON(
  json: any,
): TemenosPullTriggerRead {
  return TemenosPullTriggerReadToJSONTyped(json, false);
}

export function TemenosPullTriggerReadToJSONTyped(
  value?: TemenosPullTriggerRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    count: value["count"],
    job_ids: value["jobIds"],
  };
}
