/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TestPullError
 */
export type TestPullError = string | null;

/**
 * Check if a given object implements the TestPullError interface.
 */
export function instanceOfTestPullError(
  value: unknown,
): value is TestPullError {
  return typeof value === "string" || value === null;
}

export function TestPullErrorFromJSON(json: any): TestPullError {
  return TestPullErrorFromJSONTyped(json, false);
}

export function TestPullErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TestPullError {
  return json;
}

export function TestPullErrorToJSON(json: any): TestPullError {
  return TestPullErrorToJSONTyped(json, false);
}

export function TestPullErrorToJSONTyped(
  value?: TestPullError | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
