/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ThresholdsSource
 */
export type ThresholdsSource = string | null;

/**
 * Check if a given object implements the ThresholdsSource interface.
 */
export function instanceOfThresholdsSource(
  value: unknown,
): value is ThresholdsSource {
  return typeof value === "string" || value === null;
}

export function ThresholdsSourceFromJSON(json: any): ThresholdsSource {
  return ThresholdsSourceFromJSONTyped(json, false);
}

export function ThresholdsSourceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ThresholdsSource {
  return json;
}

export function ThresholdsSourceToJSON(json: any): ThresholdsSource {
  return ThresholdsSourceToJSONTyped(json, false);
}

export function ThresholdsSourceToJSONTyped(
  value?: ThresholdsSource | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
