/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Tolerance
 */
export type Tolerance = string | null;

/**
 * Check if a given object implements the Tolerance interface.
 */
export function instanceOfTolerance(value: unknown): value is Tolerance {
  return typeof value === "string" || value === null;
}

export function ToleranceFromJSON(json: any): Tolerance {
  return ToleranceFromJSONTyped(json, false);
}

export function ToleranceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Tolerance {
  return json;
}

export function ToleranceToJSON(json: any): Tolerance {
  return ToleranceToJSONTyped(json, false);
}

export function ToleranceToJSONTyped(
  value?: Tolerance | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
