/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TotalAmountAtAsOf
 */
export type TotalAmountAtAsOf = string | null;

/**
 * Check if a given object implements the TotalAmountAtAsOf interface.
 */
export function instanceOfTotalAmountAtAsOf(
  value: unknown,
): value is TotalAmountAtAsOf {
  return typeof value === "string" || value === null;
}

export function TotalAmountAtAsOfFromJSON(json: any): TotalAmountAtAsOf {
  return TotalAmountAtAsOfFromJSONTyped(json, false);
}

export function TotalAmountAtAsOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TotalAmountAtAsOf {
  return json;
}

export function TotalAmountAtAsOfToJSON(json: any): TotalAmountAtAsOf {
  return TotalAmountAtAsOfToJSONTyped(json, false);
}

export function TotalAmountAtAsOfToJSONTyped(
  value?: TotalAmountAtAsOf | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
