/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdatedAt
 */
export type UpdatedAt = string | null;

/**
 * Check if a given object implements the UpdatedAt interface.
 */
export function instanceOfUpdatedAt(value: unknown): value is UpdatedAt {
  return typeof value === "string" || value === null;
}

export function UpdatedAtFromJSON(json: any): UpdatedAt {
  return UpdatedAtFromJSONTyped(json, false);
}

export function UpdatedAtFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdatedAt {
  return json;
}

export function UpdatedAtToJSON(json: any): UpdatedAt {
  return UpdatedAtToJSONTyped(json, false);
}

export function UpdatedAtToJSONTyped(
  value?: UpdatedAt | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
