/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ValidationSeverity } from "./ValidationSeverity";
import {
  ValidationSeverityFromJSON,
  ValidationSeverityFromJSONTyped,
  ValidationSeverityToJSON,
  ValidationSeverityToJSONTyped,
} from "./ValidationSeverity";

/**
 *
 * @export
 * @interface ValidationFindingRead
 */
export interface ValidationFindingRead {
  /**
   *
   * @type {string}
   * @memberof ValidationFindingRead
   */
  detail: string;
  /**
   *
   * @type {string}
   * @memberof ValidationFindingRead
   */
  rule: string;
  /**
   *
   * @type {ValidationSeverity}
   * @memberof ValidationFindingRead
   */
  severity: ValidationSeverity;
}

/**
 * Check if a given object implements the ValidationFindingRead interface.
 */
export function instanceOfValidationFindingRead(
  value: object,
): value is ValidationFindingRead {
  if (!("detail" in value) || value["detail"] === undefined) return false;
  if (!("rule" in value) || value["rule"] === undefined) return false;
  if (!("severity" in value) || value["severity"] === undefined) return false;
  return true;
}

export function ValidationFindingReadFromJSON(
  json: any,
): ValidationFindingRead {
  return ValidationFindingReadFromJSONTyped(json, false);
}

export function ValidationFindingReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ValidationFindingRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    detail: json["detail"],
    rule: json["rule"],
    severity: ValidationSeverityFromJSON(json["severity"]),
  };
}

export function ValidationFindingReadToJSON(json: any): ValidationFindingRead {
  return ValidationFindingReadToJSONTyped(json, false);
}

export function ValidationFindingReadToJSONTyped(
  value?: ValidationFindingRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    detail: value["detail"],
    rule: value["rule"],
    severity: ValidationSeverityToJSON(value["severity"]),
  };
}
