/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface VintagePointRead
 */
export interface VintagePointRead {
  /**
   *
   * @type {string}
   * @memberof VintagePointRead
   */
  exposureGhs: string;
  /**
   *
   * @type {number}
   * @memberof VintagePointRead
   */
  loanCount: number;
  /**
   *
   * @type {number}
   * @memberof VintagePointRead
   */
  monthsOnBook: number;
  /**
   *
   * @type {string}
   * @memberof VintagePointRead
   */
  par30Pct: string;
}

/**
 * Check if a given object implements the VintagePointRead interface.
 */
export function instanceOfVintagePointRead(
  value: object,
): value is VintagePointRead {
  if (!("exposureGhs" in value) || value["exposureGhs"] === undefined)
    return false;
  if (!("loanCount" in value) || value["loanCount"] === undefined) return false;
  if (!("monthsOnBook" in value) || value["monthsOnBook"] === undefined)
    return false;
  if (!("par30Pct" in value) || value["par30Pct"] === undefined) return false;
  return true;
}

export function VintagePointReadFromJSON(json: any): VintagePointRead {
  return VintagePointReadFromJSONTyped(json, false);
}

export function VintagePointReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): VintagePointRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    exposureGhs: json["exposure_ghs"],
    loanCount: json["loan_count"],
    monthsOnBook: json["months_on_book"],
    par30Pct: json["par30_pct"],
  };
}

export function VintagePointReadToJSON(json: any): VintagePointRead {
  return VintagePointReadToJSONTyped(json, false);
}

export function VintagePointReadToJSONTyped(
  value?: VintagePointRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    exposure_ghs: value["exposureGhs"],
    loan_count: value["loanCount"],
    months_on_book: value["monthsOnBook"],
    par30_pct: value["par30Pct"],
  };
}
