/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WhatIfYearDeltaRead
 */
export interface WhatIfYearDeltaRead {
  /**
   *
   * @type {string}
   * @memberof WhatIfYearDeltaRead
   */
  carDeltaPp: string;
  /**
   *
   * @type {string}
   * @memberof WhatIfYearDeltaRead
   */
  lcrDeltaPp: string;
  /**
   *
   * @type {string}
   * @memberof WhatIfYearDeltaRead
   */
  netIncomeDelta: string;
  /**
   *
   * @type {string}
   * @memberof WhatIfYearDeltaRead
   */
  nsfrDeltaPp: string;
  /**
   *
   * @type {number}
   * @memberof WhatIfYearDeltaRead
   */
  year: number;
}

/**
 * Check if a given object implements the WhatIfYearDeltaRead interface.
 */
export function instanceOfWhatIfYearDeltaRead(
  value: object,
): value is WhatIfYearDeltaRead {
  if (!("carDeltaPp" in value) || value["carDeltaPp"] === undefined)
    return false;
  if (!("lcrDeltaPp" in value) || value["lcrDeltaPp"] === undefined)
    return false;
  if (!("netIncomeDelta" in value) || value["netIncomeDelta"] === undefined)
    return false;
  if (!("nsfrDeltaPp" in value) || value["nsfrDeltaPp"] === undefined)
    return false;
  if (!("year" in value) || value["year"] === undefined) return false;
  return true;
}

export function WhatIfYearDeltaReadFromJSON(json: any): WhatIfYearDeltaRead {
  return WhatIfYearDeltaReadFromJSONTyped(json, false);
}

export function WhatIfYearDeltaReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WhatIfYearDeltaRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    carDeltaPp: json["car_delta_pp"],
    lcrDeltaPp: json["lcr_delta_pp"],
    netIncomeDelta: json["net_income_delta"],
    nsfrDeltaPp: json["nsfr_delta_pp"],
    year: json["year"],
  };
}

export function WhatIfYearDeltaReadToJSON(json: any): WhatIfYearDeltaRead {
  return WhatIfYearDeltaReadToJSONTyped(json, false);
}

export function WhatIfYearDeltaReadToJSONTyped(
  value?: WhatIfYearDeltaRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    car_delta_pp: value["carDeltaPp"],
    lcr_delta_pp: value["lcrDeltaPp"],
    net_income_delta: value["netIncomeDelta"],
    nsfr_delta_pp: value["nsfrDeltaPp"],
    year: value["year"],
  };
}
