/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WindowStart
 */
export type WindowStart = string | null;

/**
 * Check if a given object implements the WindowStart interface.
 */
export function instanceOfWindowStart(value: unknown): value is WindowStart {
  return typeof value === "string" || value === null;
}

export function WindowStartFromJSON(json: any): WindowStart {
  return WindowStartFromJSONTyped(json, false);
}

export function WindowStartFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WindowStart {
  return json;
}

export function WindowStartToJSON(json: any): WindowStart {
  return WindowStartToJSONTyped(json, false);
}

export function WindowStartToJSONTyped(
  value?: WindowStart | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
