/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { WindowDailyStatRead } from "./WindowDailyStatRead";
import {
  WindowDailyStatReadFromJSON,
  WindowDailyStatReadFromJSONTyped,
  WindowDailyStatReadToJSON,
  WindowDailyStatReadToJSONTyped,
} from "./WindowDailyStatRead";
import type { WindowRatioStatRead } from "./WindowRatioStatRead";
import {
  WindowRatioStatReadFromJSON,
  WindowRatioStatReadFromJSONTyped,
  WindowRatioStatReadToJSON,
  WindowRatioStatReadToJSONTyped,
} from "./WindowRatioStatRead";

/**
 *
 * @export
 * @interface WindowAnalyticsRead
 */
export interface WindowAnalyticsRead {
  /**
   *
   * @type {string}
   * @memberof WindowAnalyticsRead
   */
  bankId: string;
  /**
   *
   * @type {Array<WindowDailyStatRead>}
   * @memberof WindowAnalyticsRead
   */
  daily: Array<WindowDailyStatRead>;
  /**
   *
   * @type {Date}
   * @memberof WindowAnalyticsRead
   */
  endDate: Date;
  /**
   *
   * @type {number}
   * @memberof WindowAnalyticsRead
   */
  periodCount: number;
  /**
   *
   * @type {Array<WindowRatioStatRead>}
   * @memberof WindowAnalyticsRead
   */
  ratios: Array<WindowRatioStatRead>;
  /**
   *
   * @type {Date}
   * @memberof WindowAnalyticsRead
   */
  startDate: Date;
}

/**
 * Check if a given object implements the WindowAnalyticsRead interface.
 */
export function instanceOfWindowAnalyticsRead(
  value: object,
): value is WindowAnalyticsRead {
  if (!("bankId" in value) || value["bankId"] === undefined) return false;
  if (!("daily" in value) || value["daily"] === undefined) return false;
  if (!("endDate" in value) || value["endDate"] === undefined) return false;
  if (!("periodCount" in value) || value["periodCount"] === undefined)
    return false;
  if (!("ratios" in value) || value["ratios"] === undefined) return false;
  if (!("startDate" in value) || value["startDate"] === undefined) return false;
  return true;
}

export function WindowAnalyticsReadFromJSON(json: any): WindowAnalyticsRead {
  return WindowAnalyticsReadFromJSONTyped(json, false);
}

export function WindowAnalyticsReadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WindowAnalyticsRead {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    bankId: json["bank_id"],
    daily: (json["daily"] as Array<any>).map(WindowDailyStatReadFromJSON),
    endDate: new Date(json["end_date"]),
    periodCount: json["period_count"],
    ratios: (json["ratios"] as Array<any>).map(WindowRatioStatReadFromJSON),
    startDate: new Date(json["start_date"]),
  };
}

export function WindowAnalyticsReadToJSON(json: any): WindowAnalyticsRead {
  return WindowAnalyticsReadToJSONTyped(json, false);
}

export function WindowAnalyticsReadToJSONTyped(
  value?: WindowAnalyticsRead | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    bank_id: value["bankId"],
    daily: (value["daily"] as Array<any>).map(WindowDailyStatReadToJSON),
    end_date: value["endDate"].toISOString().substring(0, 10),
    period_count: value["periodCount"],
    ratios: (value["ratios"] as Array<any>).map(WindowRatioStatReadToJSON),
    start_date: value["startDate"].toISOString().substring(0, 10),
  };
}
