/**
 * risk-service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WorstScenarioLabel
 */
export type WorstScenarioLabel = string | null;

/**
 * Check if a given object implements the WorstScenarioLabel interface.
 */
export function instanceOfWorstScenarioLabel(
  value: unknown,
): value is WorstScenarioLabel {
  return typeof value === "string" || value === null;
}

export function WorstScenarioLabelFromJSON(json: any): WorstScenarioLabel {
  return WorstScenarioLabelFromJSONTyped(json, false);
}

export function WorstScenarioLabelFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorstScenarioLabel {
  return json;
}

export function WorstScenarioLabelToJSON(json: any): WorstScenarioLabel {
  return WorstScenarioLabelToJSONTyped(json, false);
}

export function WorstScenarioLabelToJSONTyped(
  value?: WorstScenarioLabel | null,
  ignoreDiscriminator: boolean = false,
): any {
  return value;
}
